/* Stateful exploration: canonical Field-tag runtime. */
function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,random=Math.random){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function validRun(r){return r&&hc().regions[r.dungeon]&&Number.isInteger(r.floor)&&r.floor>=1&&r.floor<=3&&Array.isArray(r.floors)&&r.floors.length===3&&r.floors.every(f=>Array.isArray(f.nodes)&&f.nodes.length>=10&&f.nodes.length<=12&&Array.isArray(f.open)&&f.nodes.every(n=>Number.isInteger(n.id)&&n.id>=0&&n.id<12&&Array.isArray(n.links)&&n.links.every(id=>Number.isInteger(id)&&id>=0&&id<f.nodes.length)))}
const PLACE_KINDS=['廃屋','狭路・通路','広間','分岐路','高所・低所','水辺・特殊地形','崩落・障害区域','遺構・人工物','隠し区画・脇道','深部・主室'];
const PLACE_SHORT=['廃屋','狭路','広間','分岐路','高所','水辺','崩落跡','遺構','脇道','主室'];
function placeLabel(theme,kind){const short=PLACE_SHORT[PLACE_KINDS.indexOf(kind)]||'地点';const prefix={'森林':'森','洞窟':'岩窟','廃墟都市':'廃都','山岳':'山路','沼地':'沼','砂漠遺跡':'砂都','海上・船':'船','地下神殿':'神殿'}[theme]||theme;return prefix+'の'+short}
function fieldDb(){return window.RPG_FIELD_SKILLS_437||{skills:{},byId:{},rows:[]}}
function fieldDef(name){return fieldDb().skills[name]||null}
function fieldDefById(id){return fieldDb().byId[id]||null}
function tacticalCost(name){const d=fieldDef(name)||rules().meta(name);return Math.max(1,Number(d?.tpCost)||(Number(d?.unlocks?.[0]?.rank||d?.rank||1)>=9?2:1))}
function fieldTier(s){const d=fieldDef(s.name);if(!d)return 1;const rank=ranksFor(s.i)[d.mastery]||0,idx={PHY:0,SKL:1,ARC:2,MND:3},stat=stats[s.i]?.[idx[d.stat]??1]||0;return Math.max(1,Math.min(3,1+Number(rank>=8||stat>=40)+Number(rank>=10||stat>=60)))}
function fieldTagIcon(t){return ({鉱物:'◆',植物:'♣',獣:'◇',水域:'≈',機械:'⚙',遺物:'▣',聖域:'✦',呪い:'☾'})[t]||'•'}
function fieldTagsText(n){return (n?.fieldTags||[]).map(t=>fieldTagIcon(t)+' '+t).join(' / ')||'Fieldタグなし'}
function pickFieldTags(theme,place,type,random){const base={森林:['植物','獣'],洞窟:['鉱物','水域'],廃墟都市:['遺物','機械'],山岳:['鉱物','獣'],沼地:['植物','水域','呪い'],砂漠遺跡:['遺物','鉱物','聖域'],'海上・船':['水域','獣'],地下神殿:['遺物','聖域','呪い']}[theme]||[];const a=[...base];if(/水辺/.test(place))a.push('水域');if(/遺構|廃屋/.test(place))a.push('遺物');if(/崩落|高所/.test(place))a.push('鉱物');if(type==='forge')a.push('機械');const pool=[...new Set(a)];const count=random()<.2?0:random()<.72?1:2;return shuffle(pool,random).slice(0,Math.min(count,pool.length))}
function nodeExtras(type,random){if(type==='boss')return[];const out=[];if(random()<.24)out.push('treasure');if(random()<.16)out.push('trap');if(random()<.08)out.push('npc');return out}
function edgeSkillForTag(tag,random){if(tag==='水域')return'水の導き';if(tag==='植物')return'鳥瞰';if(tag==='聖域'||tag==='呪い')return'招霊';if(tag==='機械'||tag==='遺物')return random()<.7?'遺構解析':'扉解錠';return null}
function makeFieldEdge(nodes,random){const froms=shuffle(nodes.filter(n=>n.id>=2&&n.id<=7&&!n.hidden&&n.fieldTags?.length),random);for(const a of froms){for(const tag of shuffle(a.fieldTags,random)){const skill=edgeSkillForTag(tag,random);if(!skill)continue;const targets=nodes.filter(b=>!b.hidden&&b.id>a.id+1&&b.id!==9&&!a.links.includes(b.id));if(!targets.length)continue;const b=targets[Math.floor(random()*targets.length)];return {from:a.id,to:b.id,skill,tag,unlocked:false}}}return null}
function outgoingLinks(f,n){const extra=(f.fieldEdges||[]).filter(e=>e.unlocked&&e.from===n.id).map(e=>e.to);return [...new Set([...(n.links||[]),...extra])]}
function gainTP(amount,source){if(!H.run||amount<=0)return;H.run.tp=(H.run.tp||0)+amount;logRun(source+'：TP +'+amount)}
function tacticalEligible(i,n){const d=rules().meta(n);if(!H.run||!d?.unlocks?.length||learned[i].includes(n)||(H.run.temporarySkills?.[i]||[]).includes(n))return false;return d.unlocks.some(u=>{const category=rules().masteries[u.mastery]?.category;return rules().canLearn(n,u.mastery,ranksFor(i),stats[i])&&(!['源泉','術法','技能'].includes(category)||masteryOwned[i][category]?.includes(u.mastery))})}
function tacticalMenu(){if(!H.run)return dungeon();show('<h2>Tactical Pt / TP</h2>'+HT('残り '+(H.run.tp||0)+' TP','条件を満たす未習得スキルを、この探索中だけ取得。帰還時に消失。')+names.map((name,i)=>HB(name,'一時習得 '+(H.run.temporarySkills?.[i]?.length||0)+'件','tacticalSkills',[i])).join(''))}
function tacticalSkills(i){if(!H.run||!Number.isInteger(i)||i<0||i>=6)return;const options=Object.keys(rules().skills).filter(n=>tacticalEligible(i,n));show('<h2>'+hesc(names[i])+' / 一時習得</h2>'+HT('残り '+(H.run.tp||0)+' TP','必要TPは正本の習得Rankに応じて1～2。取得後にスキル画面でセット。')+(options.length?options.map(n=>{const cost=tacticalCost(n);return HB(n,'必要 '+cost+' TP / '+skillDescription(rules().meta(n)),'tacticalAcquire',[i,n],H.run.tp<cost)}).join(''):HT('取得できるスキルはありません','Mastery Rankと能力条件を確認してください')))}
function tacticalAcquire(i,n){const cost=tacticalCost(n);if(!H.run||H.run.battle||H.run.tp<cost||!tacticalEligible(i,n))return;H.run.tp-=cost;H.run.temporarySkills[i].push(n);logRun(names[i]+'：'+n+'を一時習得（TP '+cost+'）');persist();tacticalSkills(i)}
function makeRun(id,themes){
 const seed=(Math.random()*0xffffffff)>>>0,random=rng(seed),reg=hc().regions[id];
 const selected=(themes&&themes.length===3?themes:shuffle(reg.themes,random).slice(0,3)).map(x=>reg.themes.includes(x)?x:reg.themes[0]);
 const r={id:Date.now().toString(36)+'-'+seed.toString(36),dungeon:id,seed,floor:1,themes:selected,floors:[],pending:null,phase:null,battle:null,camped:{},mechanisms:{},research:0,hazard:0,buff:'なし',morale:'なし',stealth:hasSkill('潜伏')?1:0,log:[],baseline:resourceSnapshot(),finds:{materials:{},tools:{},weapons:[],armors:[]},startedAt:Date.now(),routeCount:0,battles:0,escapes:0,rescues:[],events:[],treasures:[],questStart:[],lastNode:null,tp:0,temporarySkills:names.map(()=>[]),pendingExp:0,fieldSkillUses:{},crafted:{},fieldBuffs:{}};
 let pool=shuffle(hc().events.filter(e=>e.region===id),random),pi=0;
 for(let f=1;f<=3;f++){
  const links=cp([[[2,3],[3,4],[5,6],[6,7],[5,7],[8],[8],[8],[9],[]],[[2,4],[2,3],[5,6],[6,7],[5,7],[8],[8],[8],[9],[]]][Math.floor(random()*2)]);
  const types=['battle','explore','event','camp','elite','merchant',random()<.5?'event':'battle','forge','explore','boss'];
  const places=shuffle(PLACE_KINDS.slice(0,9),random).concat(PLACE_KINDS[9]),tpool=terrainPool(selected[f-1]);
  const nodes=types.map((type,i)=>{const placeType=places[i],terrain=tpool[Math.floor(random()*tpool.length)];return {id:i,type,placeType,place:placeLabel(selected[f-1],placeType),returnPoint:type==='camp',links:links[i],terrain,fieldTags:pickFieldTags(selected[f-1],placeType,type,random),extras:nodeExtras(type,random),threat:1+Math.floor(random()*3),done:false,entered:false,eventId:type==='event'?pool[(pi++)%pool.length].id:null,roll:random(),stock:null,used:false}});
  let targetCount=10+Math.floor(random()*3);if(f===3)targetCount=Math.max(11,targetCount);
  for(let idn=10;idn<targetCount;idn++){
   const secret=f===3&&idn===10,placeType=secret?'隠し区画・脇道':PLACE_KINDS[Math.floor(random()*(PLACE_KINDS.length-1))],type=secret?'secret':(random()<.16?'camp':random()<.38?'event':random()<.65?'explore':'battle'),terrain=tpool[Math.floor(random()*tpool.length)],source=[2,4,5,6,7][Math.floor(random()*5)];
   const node={id:idn,type,placeType,place:placeLabel(selected[f-1],placeType),returnPoint:type==='camp',links:secret?[]:[8],terrain,fieldTags:pickFieldTags(selected[f-1],placeType,type,random),extras:nodeExtras(type,random),threat:1+Math.floor(random()*3),done:false,entered:false,eventId:type==='event'?pool[(pi++)%pool.length].id:null,roll:random(),stock:null,used:false,hidden:secret};
   nodes.push(node);nodes[source].links.push(idn);
  }
  const edge=random()<.65?makeFieldEdge(nodes,random):null;
  r.floors.push({nodes,open:[0,1],fieldEdges:edge?[edge]:[]});
 }
 return r
}
function currentNode(){return H?.run?.pending!=null?H.run.floors[H.run.floor-1].nodes.find(n=>n.id===H.run.pending):null}
function nodeName(n){return ({battle:'戦闘',explore:'調査',event:'出来事',camp:'野営',elite:'強敵',merchant:'旅商人',forge:'工房',stairs:'次の層',boss:'守護者',secret:'隠し地点'})[n.type]||'地点'}
function nodeIcon(n){return ({battle:'⚔',explore:'◇',event:'？',camp:'△',elite:'☠',merchant:'▤',forge:'⚒',stairs:'↑',boss:'♛',secret:'✦'})[n.type]||'•'}
function forecastType(n,intel){if(n.entered||n.done||intel>=2)return n.type;return ['elite','boss'].includes(n.type)?'battle':n.type}
function explorationPower(effect){return skillSet.some((set,i)=>vitals[i].hp>0&&set.some(n=>skillUsable(i,n)&&(rules().meta(n)?.passive?.[effect]||0)>0))}
function hasSkill(s){const groups={敵察知:'scout',強敵察知:'scout',索敵:'scout',鑑識:'appraise',鑑定:'appraise',素材鑑定:'appraise',弱点鑑識:'appraise',遺物調査:'appraise',罠解除:'unlock',罠外し:'unlock',解錠:'unlock',隠密:'stealth',潜伏:'stealth'};return skillSet.some((set,i)=>vitals[i].hp>0&&set.some(n=>skillUsable(i,n)&&(n===s||(groups[s]&&(rules().meta(n)?.passive?.[groups[s]]||0)>0))))}
function intelLevel(){return Math.min(2,Number(hasSkill('強敵察知')||hasSkill('索敵'))+Number(hasSkill('素材鑑定')||hasSkill('弱点鑑識')||hasSkill('鑑識')))}
function enemyIntelLine(name,level){const d=journal.enemyData[name]||{},bits=[];if(level>=1)bits.push('遭遇 '+(d.seen||0)+'回');if(level>=2){const attrs=Object.entries(d.attributes||{}).filter(([,v])=>v!==1).map(([k,v])=>k+' '+({0:'無効',.5:'耐性',2:'弱点'}[v]||v));if(attrs.length)bits.push(attrs.join(' / '));const st=Object.entries(d.statuses||{}).slice(0,4).map(([k,v])=>k+' '+v);if(st.length)bits.push('状態 '+st.join(' / '));if(d.parts?.length)bits.push('部位 '+d.parts.map(p=>p.name).join('・'))}return name+'：'+(bits.join(' / ')||'記録なし')}
function dungeon(){if(activeRun())return expeditionMenu();show('<h2>行き先</h2>'+Object.keys(hc().regions).map(id=>{const reg=hc().regions[id],p=dungeonProgress[id],d=H.discoveries[id]||{events:[],secrets:[]},qs=hc().quests.filter(q=>q.d===id&&[1,2].includes(qstate(q).state)).length,locked=!unlocked.includes(id);return HB(reg.title+' / '+id,locked?'前章の結果をギルドで報告すると開放':'全3層 · 踏破 '+p.clear+'回 · 最高'+p.best+'層 · 発見 '+d.events.length+'/6'+(qs?' · 依頼 '+qs+'件':''),'deployment',[id],locked)}).join('')+back())}
function deployment(id){if(activeRun())return expeditionMenu();if(!hc().regions[id]||!unlocked.includes(id))return note('この地域はまだ開放されていません');dungeonId=id;H.selected=id;const reg=hc().regions[id],active=hc().quests.filter(q=>q.d===id&&qstate(q).state===1);show('<h2>'+hesc(id)+'</h2><p class="message">'+hesc(reg.intro)+'</p>'+HT('出撃 '+H.formation.filter(i=>i!==null).length+'人 / 最大6人',reg.mechanism+'を調べ、3層目の守護者へ')+HT('受注中の依頼',active.map(q=>q.n).join(' / ')||'なし')+HB('装備・スキルを確認','出撃前の準備を整える','partyMenu')+HB('準備診断','重量・資源・スキル・携行具','readiness')+ha(HB('戻る','','dungeon'),HB('出撃','','startDungeon')))}
function startDungeon(){if(activeRun())return expeditionMenu();if(!unlocked.includes(dungeonId))return note('未開放の地域です');ensureFormation();const deployed=H.formation.filter(i=>i!==null);if(!deployed.length)return note('出撃メンバーを選んでください');for(const i of deployed)if(!skillFits(i))return note(names[i]+'のセットCostを確認してください');H.run=makeRun(dungeonId);H.totalRuns++;H.run.questStart=hc().quests.filter(q=>qstate(q).state===1).map(q=>q.id);logRun('出撃：'+dungeonId);H.story.intro=true;syncRun();persist();closeM();drawDungeon()}
const THEME_BACKGROUNDS=Object.freeze({
  '森林':'theme-forest-official.webp',
  '洞窟':'theme-cave-official.webp',
  '廃墟都市':'theme-ruins-official.webp',
  '山岳':'theme-mountain-official.webp',
  '沼地':'theme-swamp-official.webp',
  '砂漠遺跡':'theme-desert-official.webp',
  '海上・船':'theme-sea-official.webp',
  '地下神殿':'theme-temple-official.webp'
});
function themeBackground(theme){return THEME_BACKGROUNDS[theme]||THEME_BACKGROUNDS['森林']}
function themeData(){const t=H.run?.themes[(H.run?.floor||1)-1]||floorThemes[floor-1]||'森林';const d={森林:['茂み・高低差','獣・弓兵・精霊','斬・突・遠距離'],洞窟:['狭所・暗闇','ゴーレム・獣・怪異','壊・索敵'],廃墟都市:['路地・瓦礫','軽装兵・魔術師・機械','近遠の切替'],山岳:['高低差・崖','飛行・重装・獣','突・遠距離'],沼地:['悪路・瘴気','毒獣・植物・呪術師','状態回復'],砂漠遺跡:['砂塵・日陰','神官・亡者・機械','水場・相性'],'海上・船':['甲板・船倉','海賊・海獣・飛行','中距離・索敵'],地下神殿:['結界・祭壇','死霊・魔術師','封じ・探索']}[t];return {t,terrain:d[0],enemy:d[1],tactic:d[2]}}
function placeHint(n,intel){
 const level=Math.max(intel,n.scouted||0);let hint;
 if(n.done)hint='✓';
 else if(n.entered)hint=nodeName(n);
 else if(level>=2)hint=({boss:'強大な気配',elite:'強敵の気配',battle:'敵の気配',merchant:'人の痕跡',camp:'安全な気配',explore:'調査の気配',event:'不明な気配',forge:'人工物の気配'})[n.type]||'未知';
 else if(level===1)hint=n.threat>=3?'危険度 高':n.threat===2?'危険度 中':'危険度 低';
 else hint=n.threat>=3?'危険':'不明';
 if(n.treasureRevealed)hint+='・宝の気配';
 return hint+' · '+fieldTagsText(n);
}
function drawDungeon(){
 if(!activeRun())return town();syncRun();
 const r=H.run,f=r.floors[r.floor-1],theme=r.themes[r.floor-1],bg=themeBackground(theme),coords=[[25,82],[75,82],[15,65],[50,65],[85,65],[18,46],[50,46],[82,46],[50,28],[50,9],[14,22],[86,22]],intel=intelLevel();
 document.querySelector('h1').textContent=r.dungeon;document.querySelector('header .small').textContent='第'+r.floor+'層 / '+theme;
 const edges=f.nodes.flatMap(n=>n.hidden?[]:n.links.filter(id=>!f.nodes.find(x=>x.id===id)?.hidden).map(id=>{const a=coords[n.id],b=coords[id];return '<path d="M'+a[0]+' '+a[1]+' L'+b[0]+' '+b[1]+'"/>'})).join('');
 const buttons=f.nodes.filter(n=>!n.hidden).map(n=>{const pos=coords[n.id],available=f.open.includes(n.id)&&!n.done,pend=r.pending===n.id;return '<button class="map-node '+(n.done?'done':pend?'pending':available?'available':'locked')+'" style="left:'+pos[0]+'%;top:'+pos[1]+'%" data-hub="routeNode" data-args="['+n.id+']" '+(!available&&!pend?'disabled':'')+' aria-label="'+hesc((n.place||nodeName(n))+' / '+placeHint(n,intel))+(n.done?' 済':'')+'"><i>'+nodeIcon({type:forecastType(n,intel)})+'</i><b>'+hesc(n.place||nodeName(n))+'</b><small>'+hesc(placeHint(n,intel))+'</small></button>'}).join('');
 const shortcuts=[['道具','itemCategory','["道具"]'],['探索スキル','fieldExplorationSkills','[]'],['スキルセット','fieldSkillSet','[]'],['戦利品','fieldLoot','[]']].map(([label,action,args])=>'<button type="button" class="field-shortcut" data-hub="'+action+'" data-args="'+hesc(args)+'">'+label+'</button>').join('');
 document.getElementById('screen').innerHTML='<section class="expedition" data-theme="'+hesc(theme)+'" style="--explore-bg:url(../images/'+bg+')"><div class="field-head"><div><b>'+hesc(region().meter)+' '+r.hazard+'/4</b><span class="small">記録 '+r.research+' / '+r.routeCount+'地点 · TP '+(r.tp||0)+'</span></div></div><div class="map"><svg viewBox="0 0 100 100" preserveAspectRatio="none" class="route-svg" aria-hidden="true">'+edges+'</svg>'+buttons+'</div><div class="field-actions">'+shortcuts+'</div></section>';renderRoster();renderSaveStatus()
}
function setExplorationSkills(){const best=new Map();skillSet.forEach((set,i)=>{if(vitals[i].hp<=0)return;for(const n of set){if(!skillUsable(i,n))continue;const meta=rules().meta(n),d=fieldDef(n)||fieldDefById(meta?.id);if(!d)continue;const s={name:d.name,sourceName:n,user:names[i],i,mode:d.mode,def:d},old=best.get(d.id);if(!old||fieldTier(s)>fieldTier(old))best.set(d.id,s)}});return [...best.values()]}
function fieldExplorationSkills(){if(!activeRun())return dungeon();const skills=setExplorationSkills();show('<h2>探索スキル</h2>'+HT('場所Fieldタグ','地図・地点画面で確認できます。探索Mastery以外のField Skillも対象です。')+(skills.length?skills.map(s=>HT(s.name,s.user+' / '+s.def.mastery+'・'+s.def.branch+' / '+(s.mode==='Passive'?'自動':'地点で使用')+' / 対応 '+s.def.fieldTags.join('・'))).join(''):HT('使用できる探索スキルはありません','誰かのスキルセットにField Skillを入れてください。'))+back())}
function fieldSkillApplies(s,n){const d=s.def;if(!n||!d||d.mode==='Passive')return false;if(d.scene==='戦闘'&&!['battle','elite','boss'].includes(n.type))return false;if(d.fieldTags.includes('汎用')||d.fieldTags.includes('素材依存'))return true;return d.fieldTags.some(t=>(n.fieldTags||[]).includes(t))}
function fieldSkillEdge(s,n){const f=H.run.floors[H.run.floor-1];return (f.fieldEdges||[]).find(e=>!e.unlocked&&e.from===n.id&&(e.skill===s.name||e.skill===s.sourceName||s.def.fieldTags.includes(e.tag)))}
function fieldNodeSkills(){const n=currentNode();if(!n||n.done||H.run.battle)return resumeNode();const skills=setExplorationSkills().filter(s=>fieldSkillApplies(s,n)),used=H.run.fieldSkillUses||{};show('<h2>この地点で使う探索スキル</h2>'+HT('場所Fieldタグ',fieldTagsText(n))+(skills.length?skills.map(s=>{const key=H.run.floor+':'+n.id+':'+s.def.id,tier=fieldTier(s),edge=fieldSkillEdge(s,n);return HB(s.name,s.user+' / 段階 '+tier+' / '+(edge?'特殊経路あり':'対応 '+s.def.fieldTags.join('・'))+' / '+s.def.description,'activateFieldSkill',[s.name],!!used[key]||vitals[s.i].sp<(s.def.spCost||0))}).join(''):HT('この地点で使えるField Skillはありません','対応Fieldタグかスキルセットを確認してください。'))+back())}
function activateFieldSkill(name){const n=currentNode(),r=H.run;if(!n||n.done||r.battle||!setExplorationSkills().some(s=>s.name===name&&(s.mode==='Field'||s.mode==='Active')))return;const key=r.floor+':'+n.id+':'+name;r.fieldSkillUses||={};if(r.fieldSkillUses[key])return;r.fieldSkillUses[key]=true;let result='周囲の様子を確かめた。';if(['索敵','強敵察知','弱点鑑識'].includes(name)){result='気配：'+nodeName(n)+' / 危険度 '+(n.threat||1)+'。'+(['battle','elite','boss'].includes(n.type)?'戦闘地点で敵編成を確認できます。':'ここでは戦闘の気配は薄い。')}else if(['解錠','罠外し'].includes(name)){result='仕掛けの構造が分かった。調査地点では「周囲の仕掛けを調べる」から作動できます。'}else if(name==='潜伏'){r.stealth=(r.stealth||0)+1;result='隠密で通過できる機会を1回確保した。'}else if(name==='奇襲回避'){r.buff='先制';result='次の戦闘に先制の恩恵を得た。'}else if(name==='素材鑑定'){result='この地域で見つかる素材：'+(hc().labels[region().material]||region().material)+'。'}else if(name==='隠し道発見'){const secret=r.floors[r.floor-1].nodes.find(x=>x.hidden&&x.type==='secret');if(secret){secret.hidden=false;const f=r.floors[r.floor-1];if(!f.open.includes(secret.id))f.open.push(secret.id);result='隠し地点への道を発見した。'}else result='この層の隠し道はすでに判明している。'}logRun(name+'を使用');persist();drawDungeon();checkpointResult(name,result,'resumeNode')}
function fieldSkillSet(){if(!activeRun())return dungeon();show('<h2>スキルセット</h2>'+HT('探索中の設定','習得済みと一時習得スキルをセットできます。')+names.map((name,i)=>HB(name,'Cost '+skillCost(i)+' / '+skillCap(i)+' · セット中 '+skillSet[i].length+'件','skills',[i])).join('')+HB('Tactical Ptで一時習得',(H.run.tp||0)+' TP','tacticalMenu')+back())}
function fieldLoot(){if(!activeRun())return dungeon();const f=H.run.finds||{},named=(items,labels)=>Object.entries(items||{}).filter(([,q])=>q>0).map(([n,q])=>(labels?.[n]||n)+' ×'+q).join(' / ')||'まだありません';show('<h2>今回の戦利品</h2>'+HT('素材',named(f.materials,hc().labels))+HT('道具',named(f.tools))+HT('武器',(f.weapons||[]).join(' / ')||'まだありません')+HT('防具',(f.armors||[]).join(' / ')||'まだありません')+HT('収支',moneyText(gold-H.run.baseline.gold)+' · EXP '+(H.run.pendingExp||0))+HT('鑑定','探索で得た品は帰還後、ギルドで鑑定すると使用できます。')+back())}
function applyExposure(n){const r=H.run;addUnique(journal.terrains,n.terrain);addUnique(journal.terrains,r.themes[r.floor-1]);addUnique(H.discoveries[r.dungeon].terrains,n.terrain);if(['camp','merchant'].includes(n.type)){r.hazard=Math.max(0,r.hazard-1);return}if(r.dungeon==='深淵の樹海'){r.hazard=Math.min(4,r.hazard+(/毒沼|泥濘/.test(n.terrain)?2:1));if(r.hazard>=3&&!explorationPower('appraise')){fieldDamage(.04,'瘴気');logRun('瘴気が濃い。浄化香・泉・野営で取り除ける。')}}if(r.dungeon==='沈黙の砂都'){r.hazard=/岩陰|屋内|地下|遺跡内部|洞窟/.test(n.terrain)?Math.max(0,r.hazard-1):Math.min(4,r.hazard+1);if(r.hazard>=3){vitals.forEach((v,i)=>{if(v.hp>0)v.sp=Math.max(0,v.sp-Math.ceil(rules().derived(stats[i]).sp*.08))});logRun('熱気でSPを消耗。清水か日陰で回避できる。')}}}
function routeNode(id){if(!activeRun())return;const r=H.run;if(r.pending!=null)return resumeNode();const f=r.floors[r.floor-1],n=f.nodes.find(n=>n.id===id);if(!n||n.hidden||n.done||!f.open.includes(id))return;r.pending=id;r.phase='choice';if(!n.entered){n.entered=true;applyExposure(n);logRun('到達：'+nodeName(n)+' / '+n.terrain)}persist();drawDungeon();resumeNode()}
function resumeNode(){const r=H.run,n=currentNode();if(!r||!n)return drawDungeon();if(r.battle)return pendingBattleMenu();if(r.phase==='floorCleared')return stairsMenu();if(r.phase==='blessing')return eliteReward();if(['battle','elite','boss'].includes(n.type))return battlePrep();if(n.type==='explore')return explorationNode();if(n.type==='event')return eventChoice();if(n.type==='camp')return camp();if(n.type==='merchant')return merchantNode();if(n.type==='forge')return dungeonForge();if(n.type==='stairs')return stairsMenu();if(n.type==='secret')return secretNode()}
function completeNode(){const r=H.run,n=currentNode();if(!n||n.done||r.battle)return false;const f=r.floors[r.floor-1];n.done=true;awardExplorationExperience(r,n);r.routeCount++;r.lastNode=n.id;r.pending=null;r.phase=null;f.open=n.links.filter(id=>!f.nodes.find(x=>x.id===id)?.done);const secret=f.nodes.find(x=>x.type==='secret');if(secret&&secret.hidden&&n.id>=5&&n.id<=8&&r.research>=2&&(H.flags['rumor:'+r.dungeon]||hasSkill('鑑定')||Object.keys(r.mechanisms).length>=2)){secret.hidden=false;f.open.push(secret.id);n.links.push(secret.id);logRun('記録がつながり、隠し場所への道を発見した');gainTP(1,'隠し区画を発見')}persist();return true}
function leaveNode(){const n=currentNode();if(!n||!['camp','merchant','forge'].includes(n.type))return resumeNode();if(completeNode()){closeM();drawDungeon()}}
function nodeResult(title,text){persist();drawDungeon();checkpointResult(title,text,'closeM')}
function explorationNode(){const n=currentNode();if(n?.type!=='explore')return;const done=!!H.run.mechanisms[H.run.floor];show('<h2>調査地点</h2><p class="message">'+hesc(H.run.themes[H.run.floor-1]+' / '+n.terrain)+'。足場と遺物を調べ、先へ進む手掛かりを集める。</p>'+HB('周辺を調べる','地域素材・古器・探索記録を獲得','takeExploration')+HB('周囲の仕掛けを調べる',done?'この層では調査済み':'この地点で探索技能・道具を使用','mechanismMenu',[],done)+HB('探索スキルを使う','セット中のアクティブスキル','fieldNodeSkills')+back())}
function takeExploration(){const n=currentNode();if(n?.type!=='explore'||n.done)return;H.run.research++;progress('survey');const extra=hasSkill('鑑定')?2:1,got=grant({materials:{[region().material]:1,古器:extra,皮:1}});if(n.roll>.75)gainTP(1,'特殊な宝');completeNode();nodeResult('調査完了',got.join(' / '))}
function eventForNode(){const n=currentNode();return hc().events.find(e=>e.id===n?.eventId)}
function eventChance(e){const best=Math.max(...stats.filter((_,i)=>vitals[i].hp>0).map(a=>Math.max(a[1],a[2],a[3])),20);return Math.min(90,60+Math.floor((best-20)/3)+(explorationPower(e.skill)?15:0))}
function eventChoice(){const e=eventForNode();if(!e)return;const assist=explorationPower(e.skill),stock=availableStock('tools',e.tool);show('<h2>'+hesc(e.name)+'</h2><p class="message">'+hesc(e.text)+'</p>'+HB(e.safe,'確実に少量の報酬・調査記録','eventReward',[0])+HB(e.risk,'成功率 '+eventChance(e)+'% / 報酬2倍、失敗時HP8%消耗','eventReward',[1])+HB(assist?'技能を活かして調べる':e.tool+'で安全を確保',assist?'セット中の探索技能 / 確実に報酬2倍':'所持 '+stock+' / 1個消費・確実に報酬2倍','eventReward',[2],!assist&&!stock)+HB('立ち去る','報酬なしで次の分岐へ','eventReward',[3])+HB('探索スキルを使う','セット中のアクティブスキル','fieldNodeSkills'))}
function eventReward(choice){const n=currentNode(),e=eventForNode(),r=H.run;if(!n||n.type!=='event'||n.done||!e||![0,1,2,3].includes(choice))return;if(choice===2&&!explorationPower(e.skill)){if(availableStock('tools',e.tool)<1)return note('必要な道具がありません');inventory.tools[e.tool]--}let text='危険を避けて先へ進んだ。';if(choice!==3){const success=choice!==1||n.roll*100<eventChance(e);if(success){const mult=choice===0?1:2,got=grant({materials:{[e.material]:mult}});r.research++;addUnique(r.events,e.id);addUnique(H.discoveries[r.dungeon].events,e.id);progress('event');progress('survey');if(e.tag==='rescue'){gainTP(1,'特殊イベント');r.rescues.push(e.id);H.discoveries[r.dungeon].rescues++;progress('rescue');H.flags['rescued:'+r.dungeon]=true}logRun('成功：'+e.name);text=e.result+'\n'+got.join(' / ')}else{fieldDamage(.08,e.name+'の調査失敗');text='足場の崩落で全員が最大HPの8%を消耗した。戦闘不能者のHPは変化しない。';logRun('失敗：'+e.name)}}completeNode();nodeResult(choice===3?'通過':e.name,text)}
function trapEvent(){return eventChoice()}
function mechanismMenu(){const r=H.run;if(!r)return;if(r.battle)return pendingBattleMenu();if(r.mechanisms[r.floor])return note('この層の仕掛けは調査済みです');const reg=region(),boost=explorationPower(r.dungeon==='辺境遺跡'?'moveSpeed':r.dungeon==='古代迷宮'?'unlock':'appraise'),stock=availableStock('tools',reg.item);const details={'古代迷宮':'封文を読むと共鳴を抑え、奥の回路を開ける。','辺境遺跡':'標石を読み、断崖の迂回路を地図につなぐ。','深淵の樹海':'湧き水の流れを戻すと、周囲の瘴気が薄れる。','沈黙の砂都':'星盤を合わせると、日陰の回廊が見つかる。'};show('<h2>'+hesc(reg.mechanism)+'</h2><p class="message">'+hesc(details[r.dungeon])+'</p>'+HB('じっくり調査する','消費なし / 記録+1・地域素材1・環境負担を軽減','operateMechanism',[0])+HB(boost?'技能を使って作動させる':reg.item+'を使って作動させる',boost?'消費なし / 記録+2・地域素材2・探索恩恵':'所持 '+stock+' / 1個消費・記録+2・探索恩恵','operateMechanism',[1],!boost&&!stock)+back())}
function operateMechanism(mode){const r=H.run;if(!r||r.battle||r.mechanisms[r.floor]||![0,1].includes(mode))return;const reg=region(),boost=explorationPower(r.dungeon==='辺境遺跡'?'moveSpeed':r.dungeon==='古代迷宮'?'unlock':'appraise');if(mode&&!boost){if(availableStock('tools',reg.item)<1)return;inventory.tools[reg.item]--}r.mechanisms[r.floor]=true;r.research+=mode?2:1;progress('mechanism');grant({materials:{[reg.material]:mode?2:1}});if(r.dungeon==='古代迷宮'){r.hazard=Math.min(4,r.hazard+1);if(mode)r.buff='看破'}if(r.dungeon==='辺境遺跡'){r.hazard=Math.min(4,r.hazard+1);if(mode){const f=r.floors[r.floor-1];if(r.pending==null&&f.open.some(i=>i<5)&&!f.nodes[7].done&&!f.open.includes(7))f.open.push(7);r.buff='先制'}}if(r.dungeon==='深淵の樹海'){r.hazard=Math.max(0,r.hazard-(mode?4:2));vitals.forEach(v=>{if(v.hp>0){v.status.poison=0;v.statusPower.poison=0}});if(mode)r.buff='守護'}if(r.dungeon==='沈黙の砂都'){r.hazard=0;if(mode)r.buff='看破'}logRun(reg.mechanism+'を調査した');persist();drawDungeon();checkpointResult('調査完了','記録が増えました。'+(mode?'次戦への探索恩恵を獲得。':'特定の職や道具がなくても調査できます。'),'closeM')}
function secretNode(){if(currentNode()?.type!=='secret')return;const s=hc().secrets.find(s=>s.region===H.run.dungeon);show('<h2>'+hesc(s.name)+'</h2><p class="message">'+hesc(s.text)+'</p>'+HB('遺された記録を受け取る',H.milestones[s.id]?'再調査：地域素材2':'初回：希少武具・全員Mastery Pt +2','claimSecret')+back())}
function claimSecret(){const r=H.run,n=currentNode();if(n?.type!=='secret'||n.done)return;const s=hc().secrets.find(s=>s.region===r.dungeon);let got;if(H.milestones[s.id])got=grant({materials:{[region().material]:2}});else{got=grant({gear:s.gear,proof:s.name+'の記録'},s.id);awardExperience(40,'隠し地点発見',r.dungeon+':secret:'+s.id)}addUnique(H.discoveries[r.dungeon].secrets,s.id);progress('secret');r.research++;completeNode();nodeResult(s.name,got.join(' / '))}
function camp(){const r=H.run;if(currentNode()?.type!=='camp')return;show('<h2>野営</h2>'+HT('HP35% / SP35%','状態異常を解除。戦闘不能者は蘇生しない。')+HB('休息する',r.camped[r.floor]?'この層では休息済み':'各層1回','campHeal',[],!!r.camped[r.floor])+HB('道具を使う','','itemCategory',['道具'])+HB('装備・スキル・隊列','','partyMenu')+HB('士気行動','現在：'+r.morale,'moraleMenu')+ha(HB('野営を終える','','leaveNode')))}
function campHeal(){const r=H.run;if(currentNode()?.type!=='camp'||r.camped[r.floor])return;r.camped[r.floor]=true;vitals.forEach((v,i)=>{const m=rules().derived(stats[i]);if(v.hp>0)v.hp=Math.min(m.hp,v.hp+Math.ceil(m.hp*.35));v.sp=Math.min(m.sp,v.sp+Math.ceil(m.sp*.35));v.status={};v.statusPower={}});r.hazard=0;logRun('野営で休息');persist();camp()}
function moraleMenu(){if(currentNode()?.type!=='camp')return;const options=[['歌唱',['鼓舞歌','回復歌','戦歌']],['舞踏',['回避舞','速度舞','連携舞']],['奏楽',['旋律','律動','SP支援']],['号令',['攻勢号令','防勢号令','追撃号令']]];show('<h2>士気行動</h2>'+options.map(([n,skills])=>HB(n,'対応スキルをセットしている仲間が必要','setMorale',[n],!skills.some(hasSkill))).join('')+ha(HB('戻る','','camp')))}
function setMorale(n){if(currentNode()?.type!=='camp')return;const groups={歌唱:['鼓舞歌','回復歌','戦歌'],舞踏:['回避舞','速度舞','連携舞'],奏楽:['旋律','律動','SP支援'],号令:['攻勢号令','防勢号令','追撃号令']};if(!groups[n]?.some(hasSkill))return;H.run.morale=n;persist();camp()}
function stairsMenu(){const n=currentNode(),r=H.run;if(!n||!(n.type==='boss'&&r.phase==='floorCleared'||n.type==='stairs'))return;show('<h2>第'+r.floor+'層を突破</h2><p class="message">層の守護者を撃破しました。パーティは全回復しています。次は'+hesc(r.themes[r.floor])+'です。</p>'+ha(HB('準備を見直す','','partyMenu'),HB('次の層へ','','nextFloor')))}
function nextFloor(){const r=H.run,n=currentNode();if(!r||r.floor>=3||!(n?.type==='boss'&&r.phase==='floorCleared'||n?.type==='stairs'))return;completeNode();dungeonProgress[r.dungeon].best=Math.max(dungeonProgress[r.dungeon].best,r.floor);r.floor++;r.lastNode=null;r.hazard=Math.max(0,r.hazard-1);logRun('第'+r.floor+'層へ');persist();closeM();drawDungeon()}
const ENCOUNTER_ARCHETYPES={
 '森林':{front:['獣','軽装'],back:['弓','魔術師'],elite:'獣'},
 '洞窟':{front:['ゴーレム','獣'],back:['魔術師'],elite:'ゴーレム'},
 '廃墟都市':{front:['重装','軽装'],back:['魔術師','弓'],elite:'重装'},
 '山岳':{front:['重装','獣'],back:['飛行','弓'],elite:'飛行'},
 '沼地':{front:['獣','軽装'],back:['魔術師'],elite:'獣'},
 '砂漠遺跡':{front:['重装','ゴーレム'],back:['魔術師','弓'],elite:'ゴーレム'},
 '海上・船':{front:['軽装','獣'],back:['弓','飛行'],elite:'軽装'},
 '地下神殿':{front:['ゴーレム','重装'],back:['魔術師'],elite:'魔術師'}
};
function encounterData(){
 const n=currentNode(),r=H.run;if(!n)return {front:[],back:[]};if(n.encounter)return n.encounter;if(n.type==='boss')return n.encounter={front:[region().boss],back:[]};
 const theme=themeData().t,p=ENCOUNTER_ARCHETYPES[theme]||{front:['獣','重装'],back:['魔術師'],elite:'重装'},count=n.type==='elite'?5:n.threat===3?4:3,backCount=Math.min(p.back.length?count>=5?2:1:0,count-1),frontCount=count-backCount,seed=Math.floor((n.roll||0)*97);
 const front=[],back=[];
 for(let i=0;i<frontCount;i++)front.push(p.front[(seed+i)%p.front.length]);
 for(let i=0;i<backCount;i++)back.push(p.back[(seed+i)%p.back.length]);
 if(n.type==='elite'){
  const existing=front.indexOf(p.elite);
  if(existing>0)[front[0],front[existing]]=[front[existing],front[0]];
  else if(existing<0){
   if(['弓','飛行','魔術師'].includes(p.elite)){if(back.length)back[0]=p.elite;else back.push(p.elite)}
   else front[0]=p.elite
  }
 }
 return n.encounter={front,back}
}
function nodeInfo(){return battlePrep()}
function battlePrep(){const r=H.run,n=currentNode();if(!n||!['battle','elite','boss'].includes(n.type))return;if(r.battle)return pendingBattleMenu();const enc=encounterData(),intel=intelLevel(),units=[...new Set([...enc.front,...enc.back])],known=units.map(k=>enemyIntelLine(k,intel));persist();show('<h2>'+hesc(nodeName(n))+'</h2>'+HT(n.terrain,terrainEffect(n.terrain))+HT('敵 '+(enc.front.length+enc.back.length)+'体','前列 '+enc.front.join('・')+' / 後列 '+(enc.back.join('・')||'なし'))+HT('探索情報',intel===0?'探索技能なし：編成だけ確認できます':intel===1?'索敵：危険度と遭遇履歴を確認':'索敵＋鑑定：既知の属性・状態異常・部位まで確認')+(intel?HT('既知情報',known.join('\n')):'')+HB('探索スキルを使う','セット中のアクティブスキル','fieldNodeSkills')+HB('装備・スキル・列を確認',H.formation.filter(i=>i!==null).length+'人 / 資源を持ち越して戦闘','partyMenu',['formation'])+(n.type==='battle'?HB('隠密で通過',r.stealth>0?'潜伏：この探索の残り '+r.stealth+'回':'煙玉1個 / 所持 '+availableStock('tools','煙玉'),'skipBattle',[],!r.stealth&&!availableStock('tools','煙玉')):'')+ha(HB('地図へ','','closeM'),HB('戦闘へ','','battleDemo')))}
function skipBattle(){const r=H.run,n=currentNode();if(!n||n.type!=='battle'||r.battle)return;if(r.stealth>0)r.stealth--;else if(availableStock('tools','煙玉')>0)inventory.tools.煙玉--;else return;r.escapes++;logRun('隠密で戦闘を回避');completeNode();closeM();drawDungeon()}
function prepareBattle(){const r=H.run,n=currentNode();if(!r||!n||!['battle','elite','boss'].includes(n.type))return null;if(r.battle){try{return JSON.parse(RPG_STORE.getItem('rpg.exploreBattle'))}catch(_){return null}}const deployed=H.formation.filter(i=>i!==null);if(!deployed.some(i=>vitals[i].hp>0)){finalizeExpedition('敗北');return null}for(const i of deployed)if(!skillFits(i)){note(names[i]+'のスキルCostを確認してください');return null}const enc=encounterData(),id=r.id+':'+r.floor+':'+n.id+':'+Date.now();r.battle={id,node:n.id,floor:r.floor};const ctx={schema:6,resourceVersion:2,battleId:id,hubRunId:r.id,hubNodeId:n.id,battleType:n.type==='battle'?'normal':n.type,autoPolicy:H.settings.auto||'ガンガン使う',runBuff:r.buff,morale:r.morale,floor:r.floor,theme:r.themes[r.floor-1],backgroundAsset:themeBackground(r.themes[r.floor-1]),themes:r.themes,routeOpen:routeOpen,routeDone:routeDone,routePattern:0,nodeTerrain,nodeThreat,nodeEncounter,campUsed:!!r.camped[r.floor],stealthSkip:r.stealth,expeditionEvents:r.log.map(e=>e.text),expeditionStartLoot:r.baseline,expeditionActive:true,activeMembers:cp(deployed),terrain:n.terrain,enemy:[...enc.front,...enc.back].join('・'),enemyFront:enc.front,enemyBack:enc.back,threat:n.threat,rows:cp(rows),formation:cp(H.formation),stats:cp(stats),vitals:cp(vitals),resist:names.map((_,i)=>calcResist(i)),enemyKnowledge:cp(journal.enemyData),masteryOwned:cp(masteryOwned),masteryRanks:cp(window.masteryRanks),learnedTree:cp(learnedTree),upgrades:cp(upgrades),traits:cp(traits),gearMeta:cp(WM),dungeonId:r.dungeon,armor:eq.map(x=>armorFamily(x[4].split('：')[1])),armorMeta:cp(ARM),equipment:cp(eq),carryInventory:Object.fromEntries(Object.keys(inventory.tools).map(n=>[n,availableStock('tools',n)])),carrySet:eq.map(x=>x[9].split('：')[1]),skillSet:cp(skillSet),boss:n.type==='boss',result:null};persist();RPG_STORE.setItem('rpg.exploreBattle',JSON.stringify(ctx));if(!RPG_STORE.getItem('rpg.exploreBattle')){r.battle=null;note('戦闘準備を保存できません');return null}return ctx}
function battleDemo(){const ctx=prepareBattle();if(ctx)location.href=RPG_NAV.href('../battle-v44.html?from=exploration&v=2',['rpg.exploreBattle',HUB_SAVE,HUB_ACTIVE_SLOT])}
function pendingBattleMenu(){show('<h2>戦闘の記録があります</h2><p class="message">探索の進行は戦闘結果を受け取るまで確定しません。戦闘画面へ戻るか、探索を終了して帰還できます。</p>'+HB('戦闘画面へ','途中のラウンドではなく戦闘開始時からの再開になります','battleDemo')+back())}
function validateBattleResult(c){return c&&['win','lose','escape'].includes(c.result)&&Array.isArray(c.vitals)&&c.vitals.length===6&&c.vitals.every(v=>v&&['hp','sp'].every(k=>Number.isFinite(v[k])&&v[k]>=0)&&(v.mp===undefined||(Number.isFinite(v.mp)&&v.mp>=0)))}
function resumeBattle(){let c;try{c=JSON.parse(RPG_STORE.getItem('rpg.exploreBattle')||'null')}catch(_){return false}if(!c?.result)return false;if(H.receipts.includes(c.battleId)){RPG_STORE.removeItem('rpg.exploreBattle');return false}const r=H.run;if(!r||!r.battle||r.battle.id!==c.battleId||(c.hubRunId&&c.hubRunId!==r.id)){note('現在の探索と一致しない戦闘結果は反映しません。');return false}if(!validateBattleResult(c)){note('戦闘結果を読み取れませんでした。保存データは変更していません。');return false}const n=currentNode();H.receipts.push(c.battleId);H.receipts=H.receipts.slice(-300);vitals=c.vitals.map((v,i)=>{const m=rules().derived(stats[i]);return {...rules().migrateVitals(v,stats[i],c.resourceVersion||0),status:cp(v.status||{}),statusPower:cp(v.statusPower||{})}});for(const[k,v]of Object.entries(c.usedCarry||{}))if(Number.isFinite(v)&&v>0&&inventory.tools[k]!=null)inventory.tools[k]=Math.max(0,inventory.tools[k]-Math.floor(v));let freshWeak=0;for(const w of c.discoveredWeakness||[]){if(typeof w==='string'&&!journal.weakness.includes(w)){journal.weakness.push(w);freshWeak++}}if(freshWeak)progress('weak');for(const[k,v]of Object.entries(c.enemyKnowledge||{})){journal.enemyData[k]={...journal.enemyData[k],...v};addUnique(journal.enemies,k)}r.battle=null;r.buff='なし';r.morale='なし';r.battles++;logRun((c.result==='win'?'勝利':c.result==='escape'?'逃走':'敗北')+'：'+nodeName(n));if(c.result==='lose'){finalizeExpedition('敗北')}else if(c.result==='escape'){if(n.type==='boss'){r.phase='choice';persist();battlePrep()}else{r.escapes++;completeNode();drawDungeon();checkpointResult('逃走成功','報酬なしで探索を続けます。','closeM')}}else{grant({gold:n.type==='boss'?1200:n.type==='elite'?700:300,materials:{[region().material]:1}});if(n.type==='elite'){gainTP(1,'強敵を撃破');progress('elite');grant({materials:{結晶:1}},r.dungeon+':elite:'+r.floor);awardExperience(40,'強敵撃破',r.dungeon+':elite:'+r.floor);dropRare();r.phase='blessing';persist();drawDungeon();eliteReward()}else if(n.type==='boss'){progress('boss');awardExperience(80,'層ボス撃破',r.dungeon+':boss:'+r.floor);grant({gold:r.floor===3?2500+Object.keys(hc().regions).indexOf(r.dungeon)*750:900,materials:{結晶:1},...(r.floor===3?{proof:region().clue}:{})});fullRestSilent(false);logRun('層ボス撃破：全員を全回復');if(r.floor<3){gainTP(2,'第'+r.floor+'層ボス');r.phase='floorCleared';persist();drawDungeon();stairsMenu()}else{progress('clear');completeNode();if(grantResetToken('respec-boss:'+r.dungeon))logRun('再配分の書を入手');dungeonProgress[r.dungeon].clear++;dungeonProgress[r.dungeon].best=3;if(!H.story.completed.includes(r.dungeon))addUnique(H.story.pending,r.dungeon);finalizeExpedition('踏破')}}else{completeNode();drawDungeon();checkpointResult('戦闘勝利','資源と状態異常を持ち越して、次の分岐へ進みます。','closeM')}}persist();RPG_STORE.removeItem('rpg.exploreBattle');return true}
function eliteReward(){if(H.run?.phase!=='blessing')return;show('<h2>強敵撃破</h2><p class="message">戦利品を獲得しました。次の戦闘で使う探索恩恵を一つ選んでください。</p>'+['先制','看破','守護'].map(n=>HB(n,({先制:'行動速度を補助',看破:'弱点攻撃を補助',守護:'被ダメージを軽減'})[n],'selectBlessing',[n])).join(''))}
function selectBlessing(name){if(H.run?.phase!=='blessing'||!['先制','看破','守護'].includes(name))return;H.run.buff=name;logRun('探索恩恵：'+name);completeNode();closeM();drawDungeon()}
function returnAvailable(){const r=H.run;if(!r||r.battle)return false;const f=r.floors[r.floor-1],n=currentNode()||f.nodes.find(x=>x.id===r.lastNode);return !!n?.returnPoint}
function askReturn(){if(!activeRun())return town();if(!returnAvailable())return note('帰還できる場所にいるときだけ街へ戻れます。地図の休息地を探してください。');confirmAction('探索を終了して帰還','この場所から街へ戻ります。取得済み戦利品とEXPを持ち帰り、HP・SPと状態は保持します。','returnTown',['自主帰還'])}
function returnTown(reason){if(!activeRun())return town();if(!reason)return askReturn();if(!returnAvailable())return note('この場所からは帰還できません。');finalizeExpedition(reason)}
function finishExpedition(reason){return finalizeExpedition(reason||'自主帰還')}
function finalizeExpedition(result){const r=H.run;if(!r)return;const record={id:r.id,dungeon:r.dungeon,result,floor:r.floor,themes:r.themes,events:r.log.map(e=>'第'+e.floor+'層 '+e.text),loot:[],gold:gold-r.baseline.gold,nodes:r.routeCount,battles:r.battles,rescues:r.rescues.length,started:r.startedAt,ended:Date.now()};for(const[k,v]of Object.entries(loot)){const gain=v-(r.baseline.materials?.[k]||0);if(gain>0)record.loot.push((hc().labels[k]||k)+'×'+gain)}record.loot.push('収支 '+moneyText(record.gold));H.history.unshift(record);H.history=H.history.slice(0,40);record.exp=settleRunExperience(r);lastExpedition=cp(record);for(const kind of ['materials','tools'])for(const [name,count] of Object.entries(r.finds?.[kind]||{})){const bag=kind==='tools'?inventory.tools:loot;H.unappraised[kind][name]=(H.unappraised[kind][name]||0)+Math.min(count,Math.max(0,(bag[name]||0)-(H.unappraised[kind][name]||0)))}for(const name of r.finds?.weapons||[])if(inventory.weapons.includes(name))addUnique(H.unappraised.weapons,name);for(const name of r.finds?.armors||[])if(inventory.armor.includes(name))addUnique(H.unappraised.armors,name);dungeonProgress[r.dungeon].best=Math.max(dungeonProgress[r.dungeon].best,r.floor);for(let i=0;i<skillSet.length;i++){const temporary=r.temporarySkills?.[i]||[];skillSet[i]=skillSet[i].filter(n=>!temporary.includes(n)||learned[i].includes(n))}H.run=null;expeditionActive=false;expeditionStartLoot=null;RPG_STORE.removeItem('rpg.exploreBattle');persist();town()}
function innRest(){if(!requireTown())return;const p=H.pendingGrowth||{stat:0,mastery:0},stat=Math.max(0,Math.floor(p.stat||0)),mastery=Math.max(0,Math.floor(p.mastery||0));fullRestSilent(false);if(stat)statPt=statPt.map(v=>v+stat);if(mastery)masteryPt=masteryPt.map(v=>v+mastery);H.pendingGrowth={stat:0,mastery:0};persist();show('<h2>休む</h2>'+HT('全回復','HP / SP / 状態異常')+(stat||mastery?HT('成長ポイントを精算',(stat?'全員 Stat Pt +'+stat:'')+(stat&&mastery?' / ':'')+(mastery?'全員 Mastery Pt +'+mastery:'')):HT('未精算ポイント','なし'))+back())}
function fullRest(){return innRest()}
function fullRestSilent(save=true){vitals=stats.map(a=>({...rules().derived(a),status:{},statusPower:{}}));if(save&&H&&!hubLoading)persist()}
function expeditionMenu(){if(!activeRun())return dungeon();const r=H.run;show('<h2>探索状況</h2>'+HT(r.dungeon+' / 第'+r.floor+'層',r.themes[r.floor-1]+' / '+r.routeCount+'場所 · EXP '+(r.pendingExp||0)+' · TP '+(r.tp||0))+HB(r.pending!=null?'進行中の場所へ':'地図へ','','resumeExpedition')+HB('持ち物・回復','','items')+HB('探索の記録',r.log.slice(-1)[0]?.text||'','runJournal')+HB('Tactical Ptで一時習得',r.tp+' TP / 遠征終了時に消失','tacticalMenu')+HB('探索を終了して帰還',returnAvailable()?'戦利品とEXPを持って街へ戻る':'帰還可能な場所でのみ選択できます','askReturn',[],!returnAvailable())+back())}
function resumeExpedition(){closeM();drawDungeon();if(H.run?.pending!=null)resumeNode()}
function runJournal(){if(!H.run)return;show('<h2>今回の探索</h2>'+H.run.log.slice().reverse().map(e=>HT('第'+e.floor+'層',e.text)).join('')+back())}
