/* Stateful exploration: a node is completed only after its outcome is committed. */
function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296}}
function shuffle(a,random=Math.random){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function validRun(r){return r&&hc().regions[r.dungeon]&&Number.isInteger(r.floor)&&r.floor>=1&&r.floor<=3&&Array.isArray(r.floors)&&r.floors.length===3&&r.floors.every(f=>Array.isArray(f.nodes)&&f.nodes.length>=9&&f.nodes.length<=10&&Array.isArray(f.open)&&f.nodes.every(n=>Number.isInteger(n.id)&&n.id>=0&&n.id<=9&&Array.isArray(n.links)))}
function makeRun(id,themes){const seed=(Math.random()*0xffffffff)>>>0,random=rng(seed),reg=hc().regions[id];const selected=(themes&&themes.length===3?themes:shuffle(reg.themes,random).slice(0,3)).map(x=>reg.themes.includes(x)?x:reg.themes[0]);const r={id:Date.now().toString(36)+'-'+seed.toString(36),dungeon:id,seed,floor:1,themes:selected,floors:[],pending:null,phase:null,battle:null,camped:{},mechanisms:{},research:0,hazard:0,buff:'なし',morale:'なし',stealth:hasSkill('潜伏')?1:0,log:[],baseline:resourceSnapshot(),startedAt:Date.now(),routeCount:0,battles:0,escapes:0,rescues:[],events:[],treasures:[],questStart:[]};let pool=shuffle(hc().events.filter(e=>e.region===id),random),pi=0;for(let f=1;f<=3;f++){const links=[[[2,3],[3,4],[5,6],[6,7],[5,7],[8],[8],[8],[]],[[2,4],[2,3],[5,6],[6,7],[5,7],[8],[8],[8],[]]][Math.floor(random()*2)];const types=['battle','explore','event','camp','elite','merchant',random()<.5?'event':'battle','forge',f===3?'boss':'stairs'];const tpool=terrainPool(selected[f-1]);const nodes=types.map((type,i)=>({id:i,type,links:links[i],terrain:tpool[Math.floor(random()*tpool.length)],threat:1+Math.floor(random()*3),done:false,entered:false,eventId:type==='event'?pool[(pi++)%pool.length].id:null,roll:random(),stock:null,used:false}));if(f===3)nodes.push({id:9,type:'secret',links:[8],terrain:tpool[0],threat:1,done:false,entered:false,hidden:true,roll:random()});r.floors.push({nodes,open:[0,1]})}return r}
function currentNode(){return H?.run?.pending!=null?H.run.floors[H.run.floor-1].nodes.find(n=>n.id===H.run.pending):null}
function nodeName(n){return ({battle:'戦闘',explore:'調査',event:'出来事',camp:'野営',elite:'強敵',merchant:'旅商人',forge:'工房',stairs:'次の層',boss:'守護者',secret:'隠し地点'})[n.type]||'地点'}
function nodeIcon(n){return ({battle:'⚔',explore:'◇',event:'？',camp:'△',elite:'☠',merchant:'▤',forge:'⚒',stairs:'↑',boss:'♛',secret:'✦'})[n.type]||'•'}
function explorationPower(effect){return skillSet.some((set,i)=>vitals[i].hp>0&&set.some(n=>skillUsable(i,n)&&(rules().meta(n)?.passive?.[effect]||0)>0))}
function hasSkill(s){const groups={敵察知:'scout',索敵:'scout',鑑識:'appraise',鑑定:'appraise',遺物調査:'appraise',罠解除:'unlock',解錠:'unlock',隠密:'stealth',潜伏:'stealth'};return skillSet.some((set,i)=>vitals[i].hp>0&&set.some(n=>skillUsable(i,n)&&(n===s||(groups[s]&&(rules().meta(n)?.passive?.[groups[s]]||0)>0))))}
function intelLevel(){return Math.min(2,Number(hasSkill('敵察知')||hasSkill('索敵'))+Number(hasSkill('鑑定')||hasSkill('弱点看破')||hasSkill('鑑識')))}
function enemyIntelLine(name,level){const d=journal.enemyData[name]||{},bits=[];if(level>=1)bits.push('遭遇 '+(d.seen||0)+'回');if(level>=2){const attrs=Object.entries(d.attributes||{}).filter(([,v])=>v!==1).map(([k,v])=>k+' '+({0:'無効',.5:'耐性',2:'弱点'}[v]||v));if(attrs.length)bits.push(attrs.join(' / '));const st=Object.entries(d.statuses||{}).slice(0,4).map(([k,v])=>k+' '+v);if(st.length)bits.push('状態 '+st.join(' / '));if(d.parts?.length)bits.push('部位 '+d.parts.map(p=>p.name).join('・'))}return name+'：'+(bits.join(' / ')||'記録なし')}
function dungeon(){if(activeRun())return expeditionMenu();show('<h2>行き先</h2>'+Object.keys(hc().regions).map(id=>{const reg=hc().regions[id],p=dungeonProgress[id],d=H.discoveries[id]||{events:[],secrets:[]},qs=hc().quests.filter(q=>q.d===id&&[1,2].includes(qstate(q).state)).length,locked=!unlocked.includes(id);return HB(reg.title+' / '+id,locked?'前章の結果をギルドで報告すると開放':'全3層 · 踏破 '+p.clear+'回 · 最高'+p.best+'層 · 発見 '+d.events.length+'/6'+(qs?' · 依頼 '+qs+'件':''),'deployment',[id],locked)}).join('')+back())}
function deployment(id){if(activeRun())return expeditionMenu();if(!hc().regions[id]||!unlocked.includes(id))return note('この地域はまだ開放されていません');dungeonId=id;H.selected=id;const reg=hc().regions[id],active=hc().quests.filter(q=>q.d===id&&qstate(q).state===1);show('<h2>'+hesc(id)+'</h2><p class="message">'+hesc(reg.intro)+'</p>'+HT('前列3人 / 後列3人',reg.mechanism+'を調べ、3層目の守護者へ')+HT('受注中の依頼',active.map(q=>q.n).join(' / ')||'なし')+HB('装備・スキルを確認','6人の準備を整える','partyMenu')+HB('準備診断','重量・資源・スキル・携行具','readiness')+ha(HB('戻る','','dungeon'),HB('出撃','','startDungeon')))}
function startDungeon(){if(activeRun())return expeditionMenu();if(!unlocked.includes(dungeonId))return note('未開放の地域です');if(rows.filter(x=>x==='前列').length!==3)return note('前列・後列を3人ずつにしてください');for(let i=0;i<6;i++)if(!rules().fits(stats[i],skillSet[i]))return note(names[i]+'のセットCostを確認してください');H.run=makeRun(dungeonId);H.totalRuns++;H.run.questStart=hc().quests.filter(q=>qstate(q).state===1).map(q=>q.id);logRun('出撃：'+dungeonId);H.story.intro=true;syncRun();persist();closeM();drawDungeon()}
function themeData(){const t=H.run?.themes[(H.run?.floor||1)-1]||floorThemes[floor-1]||'森林';const d={森林:['茂み・高低差','獣・弓兵・精霊','斬・突・遠距離'],洞窟:['狭所・暗闇','ゴーレム・獣・怪異','壊・索敵'],廃墟都市:['路地・瓦礫','軽装兵・魔術師・機械','近遠の切替'],山岳:['高低差・崖','飛行・重装・獣','突・遠距離'],沼地:['悪路・瘴気','毒獣・植物・呪術師','状態回復'],砂漠遺跡:['砂塵・日陰','神官・亡者・機械','水場・相性'],'海上・船':['甲板・船倉','海賊・海獣・飛行','中距離・索敵'],地下神殿:['結界・祭壇','死霊・魔術師','封じ・探索']}[t];return {t,terrain:d[0],enemy:d[1],tactic:d[2]}}
function drawDungeon(){if(!activeRun())return town();syncRun();const r=H.run,f=r.floors[r.floor-1],coords=[[25,82],[75,82],[15,60],[50,60],[85,60],[18,37],[50,37],[82,37],[45,13],[85,13]],intel=intelLevel();document.querySelector('h1').textContent=r.dungeon;document.querySelector('header .small').textContent='第'+r.floor+'層 / '+r.themes[r.floor-1];const edges=f.nodes.flatMap(n=>n.hidden?[]:n.links.filter(id=>!f.nodes.find(x=>x.id===id)?.hidden).map(id=>{const a=coords[n.id],b=coords[id];return '<path d="M'+a[0]+' '+a[1]+' L'+b[0]+' '+b[1]+'"/>'})).join('');const buttons=f.nodes.filter(n=>!n.hidden).map(n=>{const pos=coords[n.id],available=f.open.includes(n.id)&&!n.done,pend=r.pending===n.id;return '<button class="map-node '+(n.done?'done':pend?'pending':available?'available':'locked')+'" style="left:'+pos[0]+'%;top:'+pos[1]+'%" data-hub="routeNode" data-args="['+n.id+']" '+(!available&&!pend?'disabled':'')+' aria-label="'+nodeName(n)+(n.done?' 済':'')+'"><i>'+nodeIcon(n)+'</i><b>'+nodeName(n)+'</b><small>'+(n.done?'✓':intel>=2?'危険 '+n.threat+' · '+n.terrain:intel===1?'危険 '+n.threat:'')+'</small></button>'}).join('');document.getElementById('screen').innerHTML='<section class="expedition"><div class="field-head"><div><b>'+hesc(region().meter)+' '+r.hazard+'/4</b><span class="small">記録 '+r.research+' / '+r.routeCount+'地点</span></div><button data-hub="expeditionMenu" class="mini">記録・帰還</button></div><div class="map"><svg viewBox="0 0 100 100" preserveAspectRatio="none" class="route-svg" aria-hidden="true">'+edges+'</svg>'+buttons+'</div><div class="field-actions">'+HB(r.pending!=null?'進行中の地点へ':'地図の明るい地点を選択',r.pending!=null?nodeName(currentNode()):'選んだ先へ進むと、別の分岐には戻れません',r.pending!=null?'resumeNode':null)+HB(region().mechanism,!!r.mechanisms[r.floor]?'この層では調査済み':'各層1回 / 経路と隠し地点の手掛かり','mechanismMenu',[],!!r.mechanisms[r.floor]||!!r.battle)+'</div></section>';renderRoster();renderSaveStatus()}
function applyExposure(n){const r=H.run;addUnique(journal.terrains,n.terrain);addUnique(journal.terrains,r.themes[r.floor-1]);addUnique(H.discoveries[r.dungeon].terrains,n.terrain);if(['camp','merchant'].includes(n.type)){r.hazard=Math.max(0,r.hazard-1);return}if(r.dungeon==='深淵の樹海'){r.hazard=Math.min(4,r.hazard+(/毒沼|泥濘/.test(n.terrain)?2:1));if(r.hazard>=3&&!explorationPower('appraise')){fieldDamage(.04,'瘴気');logRun('瘴気が濃い。浄化香・泉・野営で取り除ける。')}}if(r.dungeon==='沈黙の砂都'){r.hazard=/岩陰|屋内|地下|遺跡内部|洞窟/.test(n.terrain)?Math.max(0,r.hazard-1):Math.min(4,r.hazard+1);if(r.hazard>=3){vitals.forEach((v,i)=>{if(v.hp>0)v.sp=Math.max(0,v.sp-Math.ceil(rules().derived(stats[i]).sp*.08))});logRun('熱気でSPを消耗。清水か日陰で回避できる。')}}}
function routeNode(id){if(!activeRun())return;const r=H.run;if(r.pending!=null)return resumeNode();const f=r.floors[r.floor-1],n=f.nodes.find(n=>n.id===id);if(!n||n.hidden||n.done||!f.open.includes(id))return;r.pending=id;r.phase='choice';if(!n.entered){n.entered=true;applyExposure(n);logRun('到達：'+nodeName(n)+' / '+n.terrain)}persist();drawDungeon();resumeNode()}
function resumeNode(){const r=H.run,n=currentNode();if(!r||!n)return drawDungeon();if(r.battle)return pendingBattleMenu();if(r.phase==='blessing')return eliteReward();if(['battle','elite','boss'].includes(n.type))return battlePrep();if(n.type==='explore')return explorationNode();if(n.type==='event')return eventChoice();if(n.type==='camp')return camp();if(n.type==='merchant')return merchantNode();if(n.type==='forge')return dungeonForge();if(n.type==='stairs')return stairsMenu();if(n.type==='secret')return secretNode()}
function completeNode(){const r=H.run,n=currentNode();if(!n||n.done||r.battle)return false;const f=r.floors[r.floor-1];n.done=true;awardExplorationExperience(r,n);r.routeCount++;r.pending=null;r.phase=null;f.open=n.links.filter(id=>!f.nodes.find(x=>x.id===id)?.done);const secret=f.nodes.find(x=>x.id===9);if(secret&&secret.hidden&&n.id>=5&&n.id<=7&&r.research>=2&&(H.flags['rumor:'+r.dungeon]||hasSkill('鑑定')||Object.keys(r.mechanisms).length>=2)){secret.hidden=false;f.open.push(9);n.links.push(9);logRun('記録がつながり、隠し地点への道を発見した')}persist();return true}
function leaveNode(){const n=currentNode();if(!n||!['camp','merchant','forge'].includes(n.type))return resumeNode();if(completeNode()){closeM();drawDungeon()}}
function nodeResult(title,text){persist();drawDungeon();checkpointResult(title,text,'closeM')}
function explorationNode(){const n=currentNode();if(n?.type!=='explore')return;show('<h2>調査地点</h2><p class="message">'+hesc(H.run.themes[H.run.floor-1]+' / '+n.terrain)+'。足場と遺物を調べ、先へ進む手掛かりを集める。</p>'+HB('周辺を調べる','地域素材・古器・探索記録を獲得','takeExploration')+back())}
function takeExploration(){const n=currentNode();if(n?.type!=='explore'||n.done)return;H.run.research++;progress('survey');const extra=hasSkill('鑑定')?2:1,got=grant({materials:{[region().material]:1,古器:extra,皮:1}});completeNode();nodeResult('調査完了',got.join(' / '))}
function eventForNode(){const n=currentNode();return hc().events.find(e=>e.id===n?.eventId)}
function eventChance(e){const best=Math.max(...stats.filter((_,i)=>vitals[i].hp>0).map(a=>Math.max(a[1],a[2],a[3])),20);return Math.min(90,60+Math.floor((best-20)/3)+(explorationPower(e.skill)?15:0))}
function eventChoice(){const e=eventForNode();if(!e)return;const assist=explorationPower(e.skill),stock=inventory.tools[e.tool]||0;show('<h2>'+hesc(e.name)+'</h2><p class="message">'+hesc(e.text)+'</p>'+HB(e.safe,'確実に少量の報酬・調査記録','eventReward',[0])+HB(e.risk,'成功率 '+eventChance(e)+'% / 報酬2倍、失敗時HP8%消耗','eventReward',[1])+HB(assist?'技能を活かして調べる':e.tool+'で安全を確保',assist?'セット中の探索技能 / 確実に報酬2倍':'所持 '+stock+' / 1個消費・確実に報酬2倍','eventReward',[2],!assist&&!stock)+HB('立ち去る','報酬なしで次の分岐へ','eventReward',[3]))}
function eventReward(choice){const n=currentNode(),e=eventForNode(),r=H.run;if(!n||n.type!=='event'||n.done||!e||![0,1,2,3].includes(choice))return;if(choice===2&&!explorationPower(e.skill)){if(!(inventory.tools[e.tool]>0))return note('必要な道具がありません');inventory.tools[e.tool]--}let text='危険を避けて先へ進んだ。';if(choice!==3){const success=choice!==1||n.roll*100<eventChance(e);if(success){const mult=choice===0?1:2,got=grant({materials:{[e.material]:mult}});r.research++;addUnique(r.events,e.id);addUnique(H.discoveries[r.dungeon].events,e.id);progress('event');progress('survey');if(e.tag==='rescue'){r.rescues.push(e.id);H.discoveries[r.dungeon].rescues++;progress('rescue');H.flags['rescued:'+r.dungeon]=true}logRun('成功：'+e.name);text=e.result+'\n'+got.join(' / ')}else{fieldDamage(.08,e.name+'の調査失敗');text='足場の崩落で全員が最大HPの8%を消耗した。戦闘不能者のHPは変化しない。';logRun('失敗：'+e.name)}}completeNode();nodeResult(choice===3?'通過':e.name,text)}
function trapEvent(){return eventChoice()}
function mechanismMenu(){const r=H.run;if(!r)return;if(r.battle)return pendingBattleMenu();if(r.mechanisms[r.floor])return note('この層の仕掛けは調査済みです');const reg=region(),boost=explorationPower(r.dungeon==='辺境遺跡'?'moveSpeed':r.dungeon==='古代迷宮'?'unlock':'appraise'),stock=inventory.tools[reg.item]||0;const details={'古代迷宮':'封文を読むと共鳴を抑え、奥の回路を開ける。','辺境遺跡':'標石を読み、断崖の迂回路を地図につなぐ。','深淵の樹海':'湧き水の流れを戻すと、周囲の瘴気が薄れる。','沈黙の砂都':'星盤を合わせると、日陰の回廊が見つかる。'};show('<h2>'+hesc(reg.mechanism)+'</h2><p class="message">'+hesc(details[r.dungeon])+'</p>'+HB('じっくり調査する','消費なし / 記録+1・地域素材1・環境負担を軽減','operateMechanism',[0])+HB(boost?'技能を使って作動させる':reg.item+'を使って作動させる',boost?'消費なし / 記録+2・地域素材2・探索恩恵':'所持 '+stock+' / 1個消費・記録+2・探索恩恵','operateMechanism',[1],!boost&&!stock)+back())}
function operateMechanism(mode){const r=H.run;if(!r||r.battle||r.mechanisms[r.floor]||![0,1].includes(mode))return;const reg=region(),boost=explorationPower(r.dungeon==='辺境遺跡'?'moveSpeed':r.dungeon==='古代迷宮'?'unlock':'appraise');if(mode&&!boost){if(!(inventory.tools[reg.item]>0))return;inventory.tools[reg.item]--}r.mechanisms[r.floor]=true;r.research+=mode?2:1;progress('mechanism');grant({materials:{[reg.material]:mode?2:1}});if(r.dungeon==='古代迷宮'){r.hazard=Math.min(4,r.hazard+1);if(mode)r.buff='看破'}if(r.dungeon==='辺境遺跡'){r.hazard=Math.min(4,r.hazard+1);if(mode){const f=r.floors[r.floor-1];if(r.pending==null&&f.open.some(i=>i<5)&&!f.nodes[7].done&&!f.open.includes(7))f.open.push(7);r.buff='先制'}}if(r.dungeon==='深淵の樹海'){r.hazard=Math.max(0,r.hazard-(mode?4:2));vitals.forEach(v=>{if(v.hp>0){v.status.poison=0;v.statusPower.poison=0}});if(mode)r.buff='守護'}if(r.dungeon==='沈黙の砂都'){r.hazard=0;if(mode)r.buff='看破'}logRun(reg.mechanism+'を調査した');persist();drawDungeon();checkpointResult('調査完了','記録が増えました。'+(mode?'次戦への探索恩恵を獲得。':'特定の職や道具がなくても調査できます。'),'closeM')}
function secretNode(){if(currentNode()?.type!=='secret')return;const s=hc().secrets.find(s=>s.region===H.run.dungeon);show('<h2>'+hesc(s.name)+'</h2><p class="message">'+hesc(s.text)+'</p>'+HB('遺された記録を受け取る',H.milestones[s.id]?'再調査：地域素材2':'初回：希少武具・全員Mastery Pt +2','claimSecret')+back())}
function claimSecret(){const r=H.run,n=currentNode();if(n?.type!=='secret'||n.done)return;const s=hc().secrets.find(s=>s.region===r.dungeon);let got;if(H.milestones[s.id])got=grant({materials:{[region().material]:2}});else got=grant({gear:s.gear,mastery:2,proof:s.name+'の記録'},s.id);addUnique(H.discoveries[r.dungeon].secrets,s.id);progress('secret');r.research++;completeNode();nodeResult(s.name,got.join(' / '))}
function camp(){const r=H.run;if(currentNode()?.type!=='camp')return;show('<h2>野営</h2>'+HT('HP35% / SP35%','状態異常を解除。戦闘不能者は蘇生しない。')+HB('休息する',r.camped[r.floor]?'この層では休息済み':'各層1回','campHeal',[],!!r.camped[r.floor])+HB('道具を使う','','itemCategory',['道具'])+HB('装備・スキル・隊列','','partyMenu')+HB('士気行動','現在：'+r.morale,'moraleMenu')+ha(HB('野営を終える','','leaveNode')))}
function campHeal(){const r=H.run;if(currentNode()?.type!=='camp'||r.camped[r.floor])return;r.camped[r.floor]=true;vitals.forEach((v,i)=>{const m=rules().derived(stats[i]);if(v.hp>0)v.hp=Math.min(m.hp,v.hp+Math.ceil(m.hp*.35));v.sp=Math.min(m.sp,v.sp+Math.ceil(m.sp*.35));v.mp=0;v.status={};v.statusPower={}});r.hazard=0;logRun('野営で休息');persist();camp()}
function moraleMenu(){if(currentNode()?.type!=='camp')return;const options=[['歌唱',['鼓舞歌','回復歌','戦歌']],['舞踏',['回避舞','速度舞','連携舞']],['奏楽',['旋律','律動','SP支援']],['号令',['攻勢号令','防勢号令','追撃号令']]];show('<h2>士気行動</h2>'+options.map(([n,skills])=>HB(n,'対応スキルをセットしている仲間が必要','setMorale',[n],!skills.some(hasSkill))).join('')+ha(HB('戻る','','camp')))}
function setMorale(n){if(currentNode()?.type!=='camp')return;const groups={歌唱:['鼓舞歌','回復歌','戦歌'],舞踏:['回避舞','速度舞','連携舞'],奏楽:['旋律','律動','SP支援'],号令:['攻勢号令','防勢号令','追撃号令']};if(!groups[n]?.some(hasSkill))return;H.run.morale=n;persist();camp()}
function stairsMenu(){if(currentNode()?.type!=='stairs')return;show('<h2>第'+H.run.floor+'層の出口</h2><p class="message">この先は'+hesc(H.run.themes[H.run.floor])+'。HP・SPと残った状態異常は持ち越します。</p>'+ha(HB('準備を見直す','','partyMenu'),HB('次の層へ','','nextFloor')))}
function nextFloor(){const r=H.run;if(!r||r.floor>=3||currentNode()?.type!=='stairs')return;grant({stat:2,mastery:1},r.dungeon+':floor:'+r.floor);dungeonProgress[r.dungeon].best=Math.max(dungeonProgress[r.dungeon].best,r.floor);currentNode().done=true;r.pending=null;r.phase=null;r.floor++;r.hazard=Math.max(0,r.hazard-1);logRun('第'+r.floor+'層へ');persist();closeM();drawDungeon()}
function encounterData(){const n=currentNode(),r=H.run;if(!n)return {front:[],back:[]};if(n.encounter)return n.encounter;if(n.type==='boss')return n.encounter={front:[region().boss],back:[]};const td=themeData(),tags=td.enemy.split('・'),front=tags.filter(x=>!/弓|飛行|魔術|神官|精霊|呪術/.test(x)),back=tags.filter(x=>/弓|飛行|魔術|神官|精霊|呪術/.test(x));const count=n.type==='elite'?5:n.threat===3?4:3;const ef=[],eb=[];for(let i=0;i<count;i++){if((i===2||i===4)&&back.length)eb.push(back[(i+Math.floor(n.roll*5))%back.length]);else ef.push((front.length?front:tags)[i%(front.length||tags.length)])}return n.encounter={front:ef,back:eb}}
function nodeInfo(){return battlePrep()}
function battlePrep(){const r=H.run,n=currentNode();if(!n||!['battle','elite','boss'].includes(n.type))return;if(r.battle)return pendingBattleMenu();const enc=encounterData(),intel=intelLevel(),units=[...new Set([...enc.front,...enc.back])],known=units.map(k=>enemyIntelLine(k,intel));persist();show('<h2>'+hesc(nodeName(n))+'</h2>'+HT(n.terrain,terrainEffect(n.terrain))+HT('敵 '+(enc.front.length+enc.back.length)+'体','前列 '+enc.front.join('・')+' / 後列 '+(enc.back.join('・')||'なし'))+HT('探索情報',intel===0?'探索技能なし：編成だけ確認できます':intel===1?'索敵：危険度と遭遇履歴を確認':'索敵＋鑑定：既知の属性・状態異常・部位まで確認')+(intel?HT('既知情報',known.join('\n')):'')+HB('装備・スキル・列を確認','6人 / 資源を持ち越して戦闘','partyMenu')+(n.type==='battle'?HB('隠密で通過',r.stealth>0?'潜伏：この探索の残り '+r.stealth+'回':'煙玉1個 / 所持 '+inventory.tools.煙玉,'skipBattle',[],!r.stealth&&!inventory.tools.煙玉):'')+ha(HB('地図へ','','closeM'),HB('戦闘へ','','battleDemo')))}
function skipBattle(){const r=H.run,n=currentNode();if(!n||n.type!=='battle'||r.battle)return;if(r.stealth>0)r.stealth--;else if(inventory.tools.煙玉>0)inventory.tools.煙玉--;else return;r.escapes++;logRun('隠密で戦闘を回避');completeNode();closeM();drawDungeon()}
function prepareBattle(){const r=H.run,n=currentNode();if(!r||!n||!['battle','elite','boss'].includes(n.type))return null;if(r.battle){try{return JSON.parse(RPG_STORE.getItem('rpg.exploreBattle'))}catch(_){return null}}if(!vitals.some(v=>v.hp>0)){finalizeExpedition('敗北');return null}for(let i=0;i<6;i++)if(!rules().fits(stats[i],skillSet[i])){note(names[i]+'のスキルCostを確認してください');return null}const enc=encounterData(),id=r.id+':'+r.floor+':'+n.id+':'+Date.now();r.battle={id,node:n.id,floor:r.floor};const ctx={schema:6,resourceVersion:1,battleId:id,hubRunId:r.id,hubNodeId:n.id,battleType:n.type==='battle'?'normal':n.type,runBuff:r.buff,morale:r.morale,floor:r.floor,themes:r.themes,routeOpen:routeOpen,routeDone:routeDone,routePattern:0,nodeTerrain,nodeThreat,nodeEncounter,campUsed:!!r.camped[r.floor],stealthSkip:r.stealth,expeditionEvents:r.log.map(e=>e.text),expeditionStartLoot:r.baseline,expeditionActive:true,activeMembers:[0,1,2,3,4,5],terrain:n.terrain,enemy:[...enc.front,...enc.back].join('・'),enemyFront:enc.front,enemyBack:enc.back,threat:n.threat,rows:cp(rows),formation:cp(H.formation),stats:cp(stats),vitals:cp(vitals),resist:names.map((_,i)=>calcResist(i)),enemyKnowledge:cp(journal.enemyData),masteryOwned:cp(masteryOwned),masteryRanks:cp(window.masteryRanks),learnedTree:cp(learnedTree),upgrades:cp(upgrades),traits:cp(traits),gearMeta:cp(WM),dungeonId:r.dungeon,armor:eq.map(x=>armorFamily(x[4].split('：')[1])),armorMeta:cp(ARM),equipment:cp(eq),carryInventory:cp(inventory.tools),carrySet:eq.map(x=>x[9].split('：')[1]),skillSet:cp(skillSet),boss:n.type==='boss',result:null};persist();RPG_STORE.setItem('rpg.exploreBattle',JSON.stringify(ctx));if(!RPG_STORE.getItem('rpg.exploreBattle')){r.battle=null;note('戦闘準備を保存できません');return null}return ctx}
function battleDemo(){const ctx=prepareBattle();if(ctx)location.href=RPG_NAV.href('../index.html',['rpg.exploreBattle',HUB_SAVE])}
function pendingBattleMenu(){show('<h2>戦闘の記録があります</h2><p class="message">探索の進行は戦闘結果を受け取るまで確定しません。戦闘画面へ戻るか、探索を終了して帰還できます。</p>'+HB('戦闘画面へ','途中のラウンドではなく戦闘開始時からの再開になります','battleDemo')+HB('探索を終了して帰還','','askReturn')+back())}
function validateBattleResult(c){return c&&['win','lose','escape'].includes(c.result)&&Array.isArray(c.vitals)&&c.vitals.length===6&&c.vitals.every(v=>v&&['hp','sp','mp'].every(k=>Number.isFinite(v[k])&&v[k]>=0))}
function resumeBattle(){let c;try{c=JSON.parse(RPG_STORE.getItem('rpg.exploreBattle')||'null')}catch(_){return false}if(!c?.result)return false;if(H.receipts.includes(c.battleId)){RPG_STORE.removeItem('rpg.exploreBattle');return false}const r=H.run;if(!r||!r.battle||r.battle.id!==c.battleId||(c.hubRunId&&c.hubRunId!==r.id)){note('現在の探索と一致しない戦闘結果は反映しません。');return false}if(!validateBattleResult(c)){note('戦闘結果を読み取れませんでした。保存データは変更していません。');return false}const n=currentNode();H.receipts.push(c.battleId);H.receipts=H.receipts.slice(-300);vitals=c.vitals.map((v,i)=>{const m=rules().derived(stats[i]);return {...rules().migrateVitals(v,stats[i],c.resourceVersion||0),status:cp(v.status||{}),statusPower:cp(v.statusPower||{})}});for(const[k,v]of Object.entries(c.usedCarry||{}))if(Number.isFinite(v)&&v>0&&inventory.tools[k]!=null)inventory.tools[k]=Math.max(0,inventory.tools[k]-Math.floor(v));let freshWeak=0;for(const w of c.discoveredWeakness||[]){if(typeof w==='string'&&!journal.weakness.includes(w)){journal.weakness.push(w);freshWeak++}}if(freshWeak)progress('weak');for(const[k,v]of Object.entries(c.enemyKnowledge||{})){journal.enemyData[k]={...journal.enemyData[k],...v};addUnique(journal.enemies,k)}r.battle=null;r.buff='なし';r.morale='なし';r.battles++;logRun((c.result==='win'?'勝利':c.result==='escape'?'逃走':'敗北')+'：'+nodeName(n));if(c.result==='lose'){applyDefeatPenalty();finalizeExpedition('敗北')}else if(c.result==='escape'){if(n.type==='boss'){r.phase='choice';persist();battlePrep()}else{r.escapes++;completeNode();drawDungeon();checkpointResult('逃走成功','報酬なしで探索を続けます。','closeM')}}else{grant({gold:n.type==='boss'?1200:n.type==='elite'?700:300,materials:{[region().material]:1}});if(n.type==='elite'){progress('elite');grant({stat:1,mastery:2,materials:{結晶:1}},r.dungeon+':elite:'+r.floor);dropRare();r.phase='blessing';persist();drawDungeon();eliteReward()}else if(n.type==='boss'){progress('boss');progress('clear');grant({stat:2,mastery:2},r.dungeon+':floor:3');grant({gold:2500+Object.keys(hc().regions).indexOf(r.dungeon)*750,materials:{結晶:1},proof:region().clue});dungeonProgress[r.dungeon].clear++;dungeonProgress[r.dungeon].best=3;if(!H.story.completed.includes(r.dungeon))addUnique(H.story.pending,r.dungeon);finalizeExpedition('踏破')}else{completeNode();drawDungeon();checkpointResult('戦闘勝利','資源と状態異常を持ち越して、次の分岐へ進みます。','closeM')}}persist();RPG_STORE.removeItem('rpg.exploreBattle');return true}
function eliteReward(){if(H.run?.phase!=='blessing')return;show('<h2>強敵撃破</h2><p class="message">戦利品を獲得しました。次の戦闘で使う探索恩恵を一つ選んでください。</p>'+['先制','看破','守護'].map(n=>HB(n,({先制:'行動速度を補助',看破:'弱点攻撃を補助',守護:'被ダメージを軽減'})[n],'selectBlessing',[n])).join(''))}
function selectBlessing(name){if(H.run?.phase!=='blessing'||!['先制','看破','守護'].includes(name))return;H.run.buff=name;logRun('探索恩恵：'+name);completeNode();closeM();drawDungeon()}
function applyDefeatPenalty(){const r=H.run;if(!r)return;const lost=[];for(const[k,v]of Object.entries(loot)){const gain=Math.max(0,v-(r.baseline.materials?.[k]||0)),n=Math.floor(gain/2);if(n){loot[k]-=n;lost.push((hc().labels[k]||k)+'×'+n)}}const gained=Math.max(0,rareGear.length-r.baseline.rare),n=Math.floor(gained/2);if(n){rareGear.splice(rareGear.length-n,n);lost.push('希少装備×'+n)}logRun('敗北時の損失：'+(lost.join(' / ')||'なし'))}
function askReturn(){if(!activeRun())return town();confirmAction('探索を終了して帰還','現在の経路は終了します。取得済みの戦利品は保持し、帰還時に全回復します。','returnTown',['自主帰還'])}
function returnTown(reason){if(!activeRun())return town();if(!reason)return askReturn();finalizeExpedition(reason)}
function finishExpedition(reason){return finalizeExpedition(reason||'自主帰還')}
function finalizeExpedition(result){const r=H.run;if(!r)return;const record={id:r.id,dungeon:r.dungeon,result,floor:r.floor,themes:r.themes,events:r.log.map(e=>'第'+e.floor+'層 '+e.text),loot:[],gold:gold-r.baseline.gold,nodes:r.routeCount,battles:r.battles,rescues:r.rescues.length,started:r.startedAt,ended:Date.now()};for(const[k,v]of Object.entries(loot)){const gain=v-(r.baseline.materials?.[k]||0);if(gain>0)record.loot.push((hc().labels[k]||k)+'×'+gain)}record.loot.push('収支 '+moneyText(record.gold));H.history.unshift(record);H.history=H.history.slice(0,40);lastExpedition=cp(record);dungeonProgress[r.dungeon].best=Math.max(dungeonProgress[r.dungeon].best,r.floor);H.run=null;expeditionActive=false;expeditionStartLoot=null;RPG_STORE.removeItem('rpg.exploreBattle');persist();town()}
function innRest(){if(!requireTown())return;const p=H.pendingGrowth||{stat:0,mastery:0},stat=Math.max(0,Math.floor(p.stat||0)),mastery=Math.max(0,Math.floor(p.mastery||0));fullRestSilent(false);if(stat)statPt=statPt.map(v=>v+stat);if(mastery)mp=mp.map(v=>v+mastery);H.pendingGrowth={stat:0,mastery:0};persist();show('<h2>休む</h2>'+HT('全回復','HP / SP / 状態異常')+(stat||mastery?HT('成長ポイントを精算',(stat?'全員 Stat Pt +'+stat:'')+(stat&&mastery?' / ':'')+(mastery?'全員 Mastery Pt +'+mastery:'')):HT('未精算ポイント','なし'))+back())}
function fullRest(){return innRest()}
function fullRestSilent(save=true){vitals=stats.map(a=>({...rules().derived(a),status:{},statusPower:{}}));if(save&&H&&!hubLoading)persist()}
function expeditionMenu(){if(!activeRun())return dungeon();const r=H.run;show('<h2>探索状況</h2>'+HT(r.dungeon+' / 第'+r.floor+'層',r.themes[r.floor-1]+' / '+r.routeCount+'地点')+HB(r.pending!=null?'進行中の地点へ':'地図へ','','resumeExpedition')+HB('持ち物・回復','','items')+HB('探索の記録',r.log.slice(-1)[0]?.text||'','runJournal')+HB('探索を終了して帰還','取得済みの戦利品を持って街へ戻る','askReturn')+back())}
function resumeExpedition(){closeM();drawDungeon();if(H.run?.pending!=null)resumeNode()}
function runJournal(){if(!H.run)return;show('<h2>今回の探索</h2>'+H.run.log.slice().reverse().map(e=>HT('第'+e.floor+'層',e.text)).join('')+back())}
