/* Equipment fitting is transient. Only fittingApply writes equipment and saves. */
let fittingDraft=null;
const fittingSlots={0:'主武器',1:'副手',2:'予備主武器',3:'予備副手',4:'防具一式',8:'装飾品',9:'携行具'};
function fittingWith(i,items,fn){const saved=eq[i];eq[i]=items.slice();try{return fn()}finally{eq[i]=saved}}
function fittingSession(i){if(!Number.isInteger(i)||i<0||i>=names.length)return null;if(!fittingDraft||fittingDraft.i!==i||JSON.stringify(fittingDraft.base)!==JSON.stringify(eq[i]))fittingDraft={i,base:eq[i].slice(),items:eq[i].slice(),slot:0};return fittingDraft}
function fittingDiscard(){fittingDraft=null}
function fittingHero(i,a,b,overview=false){const portrait=['gald','lize','ern','sena','mirea','yuna'][i];const metric=(name,x,y,lower=false)=>{const delta=y-x;return '<span class="'+(!delta?'same':(lower?delta<0:delta>0)?'up':'down')+'"><small>'+name+'</small><b>'+x+(delta?' <i>→</i> '+y:'')+'</b>'+(delta?'<em>'+(delta>0?'+':'')+delta+'</em>':'')+'</span>'};return '<section class="actor-hero fitting-hero'+(overview?' status-hero':'')+'"><div class="actor-hero-art fitting-art"><img src="../images/'+portrait+'.svg" alt="'+hesc(names[i])+'"></div><div class="fitting-status"><small>'+hesc(battleStyle(i))+'</small><strong>'+hesc(names[i])+'</strong><div class="fitting-resources">HP '+a.hp+'　SP '+a.sp+'</div><div class="equip-compare" aria-live="polite"><small>'+(overview?'主要ステータス':'現在 → 試着後')+'</small><div class="equip-compare-grid">'+metric('物防',a.pdef,b.pdef)+metric('魔防',a.mdef,b.mdef)+metric('重量 / 上限 '+b.limit,a.weight,b.weight,true)+metric('使用可能技',a.usable,b.usable)+'</div></div></div></section>'}
function fittingScreen(i,k=0,preview){if(H.run?.battle)return pendingBattleMenu();if(!Object.hasOwn(fittingSlots,k))return;const s=fittingSession(i);if(!s)return;const changedSlot=s.slot!==k;s.slot=k;
 if(preview!==undefined&&fittingWith(i,s.items,()=>canEquip(i,k,preview))){s.items[k]=s.items[k].split('：')[0]+'：'+preview;if(k===4)for(let z=5;z<=7;z++)s.items[z]=s.items[z].split('：')[0]+'：'+preview;if((k===0||k===2)&&isTwoHanded(preview))s.items[k+1]=s.items[k+1].split('：')[0]+'：なし'}
 const a=equipmentSnapshot(i),b=fittingWith(i,s.items,()=>equipmentSnapshot(i)),dirty=JSON.stringify(s.base)!==JSON.stringify(s.items),current=s.items[k].split('：')[1],list=k<4?['なし',...inventory.weapons]:k===4?inventory.armor:k===9?['なし',...Object.keys(hc().tools).filter(n=>hc().tools[n].battle)]:['なし','護符'];
 const slotButtons=keys=>keys.map(n=>'<button data-hub="equipChoice" data-args="'+hesc(JSON.stringify([i,n]))+'" aria-pressed="'+(n===k)+'"><small>'+fittingSlots[n]+'</small><b>'+hesc(s.items[n].split('：')[1])+'</b></button>').join('');
 const rows=fittingWith(i,s.items,()=>list.map(n=>{const ok=canEquip(i,k,n),m=WM[n];let desc=k<4?n==='なし'?'武器を外します。':weaponDescription(n):k===4?armorDescription(n):k===9?n==='なし'?'携行具を外します。':toolDescription(n):n==='なし'?'装飾品を外します。':'補助効果を持つ装飾品。';if(!ok){const j={PHY:0,SKL:1,ARC:2,MND:3}[m?.[3]];desc=m&&j!=null&&stats[i][j]<m[4]?m[3]+' '+stats[i][j]+' / 必要 '+m[4]:(k===1||k===3)?'副手条件不足：両手武器との併用不可・二刀流はSKL 30必要':'装備条件不足'}else if(n!==current)desc+=' / '+equipmentCompareText(i,k,n);return '<div class="candidate '+(n===current?'selected':'')+'">'+HB(n+(n===current?(n===s.base[k].split('：')[1]?'　装備中':'　試着中'):n===s.base[k].split('：')[1]?'　現在装備':''),desc,'uiEquipPreview',[i,k,n],!ok)+'</div>'}).join(''));
 show('<h2>'+hesc(names[i])+' / 装備</h2>'+fittingHero(i,a,b)+'<div class="fitting-controls"><div class="fitting-slot-group"><small>現在のセット</small><div>'+slotButtons([0,1])+'</div></div><div class="fitting-slot-group"><small>予備セット</small><div>'+slotButtons([2,3])+'</div></div><div class="fitting-other-slots">'+slotButtons([4,8,9])+'</div><p class="fitting-hint screen-hint">'+hesc(b.weightLevel?b.weightText:k===2||k===3?'予備装備は換装するまで戦闘値に反映されません。':dirty?'試着中です。部位・候補を続けて選び、最後に確定。':'装備で使えるスキル・重量が変化。候補をタップして試着。')+'</p></div><div class="fitting-list"><div class="fitting-list-title">'+fittingSlots[k]+'の候補 <small>属性・射程 '+hesc(b.attack)+' / '+hesc(b.stance)+'</small></div>'+rows+HB('主副セットを換装','現在と予備を入れ替えて試着','fittingSwap',[i])+'</div>'+ha(HB('取り消す','','fittingCancel',[i]),HB('装備を確定','','fittingApply',[i],!dirty)));
 if(changedSlot){const body=document.querySelector('#panel .panel-body');if(body)body.scrollTop=0}
}
function fittingCancel(i){if(H.run?.battle)return;const k=fittingDraft?.slot||0;fittingDiscard();equipChoice(i,k)}
function fittingApply(i){if(H.run?.battle||!fittingDraft||fittingDraft.i!==i)return;const s=fittingDraft;if(JSON.stringify(s.base)!==JSON.stringify(eq[i])){fittingDiscard();return equip(i)}const valid=fittingWith(i,s.items,()=>Object.keys(fittingSlots).every(k=>{k=Number(k);return s.items[k]===s.base[k]||canEquip(i,k,s.items[k].split('：')[1])}));if(!valid)return note('装備条件や所持品が変わりました。もう一度選んでください。');eq[i]=s.items.slice();const k=s.slot;fittingDiscard();persist();equipChoice(i,k)}

function fittingSwap(i){if(H.run?.battle)return;const s=fittingSession(i);if(!s)return;const v=s.items.slice(0,4).map(x=>x.split('：')[1]);for(let k=0;k<4;k++)s.items[k]=s.items[k].split('：')[0]+'：'+v[(k+2)%4];equipChoice(i,s.slot)}
