/* Town, journal, inventory and campaign screens. */
function town(){if(activeRun()){closeM();return drawDungeon()}closeM();document.querySelector('h1').textContent='王都レクシア';document.querySelector('header .small').textContent='冒険者区 / '+(H.story.ending?'四封の記録・その後':'第'+Math.min(4,H.story.completed.length+1)+'章');const ready=hc().quests.filter(q=>qstate(q).state===2).length,scenes=H.story.pending.filter(x=>!H.story.completed.includes(x)).length;document.getElementById('screen').innerHTML='<section class="town-scene"><div class="chapter-kicker">'+(H.story.ending?'旅のつづき':'四封の記録')+'</div><div class="objective">'+HB(H.story.intro?storyObjective():'地下から響く鐘',H.story.intro?'次の目的を確認':'王都で始まる、六人の調査行','storyMenu')+'</div><div class="town-view" aria-hidden="true"><span class="tower">♜</span><span class="town-caption">LEXIA</span></div><div class="places">'+place('♨','宿・酒場','会話・旅の記録','inn')+place('⚜','ギルド',scenes?'物語報告 '+scenes+'件':ready?'達成報告 '+ready+'件':'依頼・記録・査定','guild')+place('⚒','市場','武具・道具・加工','market')+place('♜','ダンジョン',unlocked.length+'地域 / 6人で出撃','dungeon')+'</div></section>';document.getElementById('money').textContent=moneyText(gold);renderRoster();renderSaveStatus()}
function place(icon,title,text,act){return '<button class="place" data-hub="'+act+'"><i>'+icon+'</i><b>'+title+'</b><span class="small">'+hesc(text)+'</span></button>'}
function storyMenu(){if(!requireTown())return;let html='<h2>四封の記録</h2>';if(!H.story.intro)html+='<p class="message">止まっていた地下の鐘が、夜ごと鳴り始めた。ギルドが託したのは、異変の調査と、生きて帰ること。六人はそれぞれの道具を確かめ、同じ地図を囲む。</p>'+HB('調査を引き受ける','第1章：沈黙した鐘','startStory');else{html+=HT('次の目的',storyObjective());for(const[id,r]of Object.entries(hc().regions)){const complete=H.story.completed.includes(id),pending=H.story.pending.includes(id)&&!complete;html+=HB('第'+r.chapter+'章 '+r.title,complete?'報告済み':pending?'踏破済み / ギルドへ報告':unlocked.includes(id)?'調査可能':'前章の報告で開放',complete?'readStory':pending?'reportChapter':'deployment',[id],!complete&&!pending&&!unlocked.includes(id))}if(H.story.completed.length===4)html+=HB(H.story.ending?'エピローグを読む':'旅の記録を仕上げる','未達成の依頼や隠し地点は、このあとも探索できます','epilogue')}show(html+back())}
function startStory(){if(!requireTown()||H.story.intro)return;H.story.intro=true;persist();storyMenu()}
function readStory(id){const r=hc().regions[id];if(!r)return;show('<h2>'+hesc(r.title)+'</h2><p class="message">'+hesc(r.intro)+'\n\n'+hesc(r.ending)+'</p>'+HT('残した記録',H.story.choices[id]||'旧版の踏破記録を引き継ぎました')+ha(HB('戻る','','storyMenu')))}
function reportChapter(id){if(!requireTown()||!H.story.pending.includes(id)||H.story.completed.includes(id))return;const r=hc().regions[id];show('<h2>第'+r.chapter+'章の報告</h2><p class="message">'+hesc(r.ending)+'</p>'+HT('イリス','この記録を、どう残しましょう。選択は旅の結びに記録されます。')+HB('人々が読める調査録にする','情報を公開して道を残す','finishChapter',[id,'公開した調査録'])+HB('現地の声を添えて保存する','記録の背景も一緒に残す','finishChapter',[id,'人々の声を添えた記録']))}
function finishChapter(id,choice){if(!requireTown()||!H.story.pending.includes(id)||H.story.completed.includes(id)||!['公開した調査録','人々の声を添えた記録'].includes(choice))return;H.story.completed.push(id);H.story.pending=H.story.pending.filter(x=>x!==id);H.story.choices[id]=choice;H.story.intro=true;const got=grant({stat:4,mastery:3,gold:1000},id+':story'),next=hc().regions[id].next;if(next)addUnique(unlocked,next);H.flags['chapter:'+id]=true;persist();town();checkpointResult('報告完了',got.join(' / ')+'\n'+(next?next+'への道が開きました。':'四つの記録が揃いました。物語の最後を読めます。'),'storyMenu')}
function epilogue(){if(!requireTown()||H.story.completed.length<4)return;let text='鐘は再び静かになった。市場には調査隊の荷が並び、宿の食卓には書きかけの地図が残る。\n\n'+names.join('、')+'。六人の記録は、それぞれ違う景色を映していた。それでも帰り道は、いつも同じ街へ続いている。';if(H.story.ending)text+='\n\n'+(H.story.ending==='街へ'?'調査録はギルドの書架に置かれた。次の冒険者が最初の一頁を開く。':'地図には新しい余白が残された。六人は、次の旅の相談を始めた。');show('<h2>夜明けの食卓</h2><p class="message">'+hesc(text)+'</p>'+HT('残したもの',Object.entries(H.story.choices).map(([r,c])=>r+'：'+c).join('\n'))+(H.story.ending?back():HB('記録を街へ託す','','finishEnding',['街へ'])+HB('次の旅の地図を広げる','','finishEnding',['旅へ'])))}
function finishEnding(choice){if(!requireTown()||H.story.ending||H.story.completed.length<4||!['街へ','旅へ'].includes(choice))return;H.story.ending=choice;persist();epilogue()}
function guild(){if(!requireTown())return;const pending=H.story.pending.filter(x=>!H.story.completed.includes(x)),ready=hc().quests.filter(q=>qstate(q).state===2);show('<h2>冒険者ギルド</h2>'+pending.map(r=>HB('物語の報告：'+hc().regions[r].title,'新しい地域へ','reportChapter',[r])).join('')+(ready.length?HB('依頼をまとめて報告','達成済み '+ready.length+'件','reportAll'):'')+HB('依頼掲示板','受注・進捗・達成報告','questMenu')+HB('探索資料室','地域・敵情報・隠し地点の噂','infoMenu')+HB('遺物の査定','古器 '+loot.古器+' / 未引取武具 '+rareGear.length,'appraiseMenu')+HB('エダと話す','任意の会話','npcTalk',['受付'])+back())}
function questMenu(filter='active'){if(!requireTown())return;const list=hc().quests.filter(q=>filter==='all'||(filter==='active'?[1,2].includes(qstate(q).state):filter==='ready'?qstate(q).state===2:filter==='done'?qstate(q).state===3:qstate(q).state===0));show('<h2>依頼掲示板</h2>'+ha(HB('未受注','','questMenu',['open']),HB('進行中','','questMenu',['active']),HB('完了','','questMenu',['done']))+(list.length?list.map(q=>{const st=qstate(q),allowed=syncQuestAvailability().some(x=>x.id===q.id);return HB((H.tracked===q.id?'★ ':'')+q.n,q.d+' / '+['未受注','進行中','報告待ち','報告済み'][st.state]+' '+st.progress+'/'+q.target,'questSelect',[q.id],st.state===0&&!allowed)}).join(''):HT('該当する依頼はありません','未受注から依頼を選べます。'))+ha(HB('全件','','questMenu',['all']),HB('ギルドへ','','guild')))}
function findQuest(id){return typeof id==='number'?hc().quests[id]:hc().quests.find(q=>q.id===id)}
function questSelect(id){if(!requireTown())return;const q=findQuest(id);if(!q)return;const st=qstate(q),available=syncQuestAvailability().some(x=>x.id===q.id);show('<h2>'+hesc(q.n)+'</h2>'+HT(q.d,q.description)+HT('進捗 '+st.progress+'/'+q.target,'報酬 '+moneyText(q.reward)+' / 全員 Stat Pt '+q.stat+' / Mastery Pt '+q.mastery)+(st.state===0?HB('受注する',available?'受注後の行動が進捗になります':'地域または前提依頼が未達成','acceptQuest',[q.id],!available):st.state===2?HB('達成報告をする','','claimQuest',[q.id]):st.state===3?HT('報告済み','この依頼の報酬は受領済みです。'):HB('この地域へ出撃','','deployment',[q.d]))+(st.state===1?HB('目的として表示','','trackQuest',[q.id])+HB('依頼を取り下げる','進捗はリセットされます','askAbandonQuest',[q.id]):'')+ha(HB('一覧へ','','questMenu',['all'])))}
function acceptQuest(id){if(!requireTown())return;const q=findQuest(id);if(!q||qstate(q).state!==0||!syncQuestAvailability().some(x=>x.id===id))return;qstate(q).state=1;qstate(q).progress=0;H.tracked=id;persist();questSelect(id)}
function trackQuest(id){const q=findQuest(id);if(!q||qstate(q).state!==1)return;H.tracked=id;persist();questSelect(id)}
function askAbandonQuest(id){confirmAction('依頼を取り下げる','進捗をリセットします。あとで再受注できます。','abandonQuest',[id])}
function abandonQuest(id){if(!requireTown())return;const q=findQuest(id);if(q&&qstate(q).state===1){H.quests[id]={state:0,progress:0};persist();questMenu('open')}}
function claimQuest(id,quiet=false){if(!requireTown())return;const q=findQuest(id);if(!q||qstate(q).state!==2)return;qstate(q).state=3;const got=grant({gold:q.reward,stat:q.stat,mastery:q.mastery},'quest:'+id);if(H.tracked===id)H.tracked=null;persist();if(!quiet)checkpointResult('依頼報告',got.join(' / '),'questMenu',['active']);return got}
function reportAll(){if(!requireTown())return;const ready=hc().quests.filter(q=>qstate(q).state===2);if(!ready.length)return note('報告できる依頼はありません');const total=ready.reduce((v,q)=>v+q.reward,0);ready.forEach(q=>claimQuest(q.id,true));persist();checkpointResult('達成報告 '+ready.length+'件',moneyText(total)+'と育成ポイントを受領しました。','guild')}
function inn(){if(!requireTown())return;show('<h2>宿・酒場</h2>'+HB('帰還後の食卓',lastExpedition.result==='なし'?'まだ探索記録はありません':lastExpedition.dungeon+' / '+lastExpedition.result,'returnTalk')+HB('仲間と話す','六人それぞれの旅の話','conversation')+HB('街の人々と話す','依頼・記録・暮らしの話','npcMenu')+HB('仲間同士の会話','探索のあとに開く短い場面','pairMenu')+HB('噂を聞く','隠し地点と探索の手掛かり','rumors')+HT('食事・休息','帰還時に無料で全回復。余分な休息操作は不要です。')+back())}
function returnTalk(){const x=H.history[0]||lastExpedition;if(!x||x.result==='なし')return note('探索から帰還すると、ここで旅を振り返れます');const talk=x.result==='敗北'?'ガルド「帰ってこられた。今度は記録を見て、進む道を選び直そう。」':x.rescues?'ユナ「帰りを待っている人に、良い知らせができるね。」':x.result==='踏破'?'ミレア「記録がつながった。ギルドで、分かったことを話しましょう。」':'セナ「ここまでの道は記録した。次は別の分岐も調べられる。」';show('<h2>帰還後の食卓</h2>'+HT(x.dungeon+' / '+x.result,'第'+(x.floor||1)+'層 / 戦闘 '+(x.battles||0)+'回 / 救助 '+(x.rescues||0)+'件')+'<p class="message">'+hesc(talk)+'</p>'+HT('持ち帰ったもの',(x.loot||[]).join(' / ')||'なし')+HB('探索の全記録','','historyDetail',[x.id])+HB('ギルドへ報告','','guild')+HB('仲間と話す','','conversation')+back())}
function conversation(){if(!requireTown())return;show('<h2>仲間と話す</h2>'+hc().companion.map((c,i)=>{const count=H.companions[i]?.length||0;return HB(c[0]+' / '+c[1],count+'/3場面を記録','memberTalk',[i])}).join('')+ha(HB('宿・酒場へ','','inn')))}
function talkAvailable(stage){return stage===0||(stage===1&&(H.story.completed.length>=1||H.history.some(h=>h.rescues>0)))||(stage===2&&H.story.completed.length>=3)}
function memberTalk(i){if(!requireTown())return;const c=hc().companion[i];if(!c)return;const read=H.companions[i]||[],stage=read.length;if(stage>=3||!talkAvailable(stage)){show('<h2>'+hesc(c[0])+'</h2><p class="message">'+hesc(c[Math.min(4,stage+1)])+'</p>'+HT('会話記録',read.length+'/3 / '+(stage>=3?'全場面を記録済み':'次の場面は物語や救助の進展で開きます'))+HB('これまでの会話','','talkArchive',['companion',i])+ha(HB('戻る','','conversation')));return}show('<h2>'+hesc(c[0]+' / '+c[1])+'</h2><p class="message">'+hesc(c[stage+2])+'</p>'+HB('その考えを聞かせて','話に耳を傾ける','finishCompanion',[i,stage,'話を聞いた'])+HB('自分たちの旅のことを話す','経験を分かち合う','finishCompanion',[i,stage,'旅の話をした']))}
function finishCompanion(i,stage,choice){if(!requireTown()||!hc().companion[i]||!talkAvailable(stage))return;const a=H.companions[i]||(H.companions[i]=[]);if(a.length!==stage)return;a.push({choice,text:hc().companion[i][stage+2]});persist();checkpointResult('会話を記録しました',hc().companion[i][0]+'は、少し表情を和らげた。','conversation')}
function npcMenu(){if(!requireTown())return;show('<h2>街の人々</h2>'+hc().npcs.map(n=>HB(n.name,n.role+' / 会話 '+(H.talks[n.id]?.length||0)+'/3','npcTalk',[n.id])).join('')+back())}
function npcTalk(id){if(!requireTown())return;const n=hc().npcs.find(n=>n.id===id)||hc().npcs[id===0?3:4];if(!n)return;const read=H.talks[n.id]||[],stage=read.length;show('<h2>'+hesc(n.name)+'</h2><p class="message">'+hesc(n.text[Math.min(stage,2)])+'</p>'+(stage<3&&talkAvailable(stage)?HB('旅の記録を共有する','話した内容は記録に残ります','finishNPC',[n.id,stage]):HT(stage>=3?'全場面を記録済み':'次の話題はまだありません','物語や救助の進展で、新しい話題が開きます。'))+HB('会話記録','','talkArchive',['npc',n.id])+ha(HB('人々の一覧へ','','npcMenu')))}
function finishNPC(id,stage){if(!requireTown()||!talkAvailable(stage))return;const n=hc().npcs.find(n=>n.id===id);if(!n)return;const a=H.talks[id]||(H.talks[id]=[]);if(a.length!==stage)return;a.push({text:n.text[stage]});const r=Object.keys(hc().regions)[Math.min(3,H.story.completed.length)];H.flags['rumor:'+r]=true;addUnique(journal.rumors,hc().secrets.find(s=>s.region===r).name+'：調査記録を集めると道が見つかる');persist();checkpointResult('会話を記録しました','探索資料室に、隠し地点の手掛かりを記録しました。','npcMenu')}
function pairMenu(){if(!requireTown())return;show('<h2>仲間同士の会話</h2>'+hc().pairs.map((p,i)=>{const open=H.history.length>0&&H.story.completed.length>=Math.floor(i/2);return HB(p[2],p[0]+' × '+p[1]+(H.pairs[i]?' / 読了':''),'readPair',[i],!open)}).join('')+back())}
function readPair(i){if(!requireTown()||!hc().pairs[i]||!H.history.length||H.story.completed.length<Math.floor(i/2))return;H.pairs[i]=true;persist();const p=hc().pairs[i];show('<h2>'+hesc(p[2])+'</h2><p class="message">'+hesc(p[3])+'</p>'+ha(HB('戻る','','pairMenu')))}
function talkArchive(type,id){const a=type==='npc'?H.talks[id]:H.companions[id];show('<h2>会話記録</h2>'+((a||[]).map((e,i)=>HT('場面 '+(i+1)+(e.choice?' / '+e.choice:''),e.text)).join('')||HT('まだ記録はありません'))+back())}
function rumors(){if(!requireTown())return;show('<h2>噂</h2>'+Object.entries(hc().regions).filter(([id])=>unlocked.includes(id)).map(([id,r])=>HB(hc().secrets.find(s=>s.region===id).name,H.flags['rumor:'+id]?'記録済み':'無料で手掛かりを聞く','addRumor',[id])).join('')+ha(HB('宿・酒場へ','','inn')))}
function addRumor(id){if(!requireTown()||!unlocked.includes(id))return;const s=hc().secrets.find(s=>s.region===id);if(!s)return;H.flags['rumor:'+id]=true;addUnique(journal.rumors,s.name+'：2つ以上の調査記録を集め、第3層の奥を探す');persist();checkpointResult(s.name,'2つ以上の調査記録を集め、第3層の分岐の先へ。仕掛けの調査や鑑識でも道を発見できます。','rumors')}
function infoMenu(){if(!requireTown())return;show('<h2>探索資料室</h2>'+unlocked.map(id=>HB(id,'最高 '+dungeonProgress[id].best+'層 / 踏破 '+dungeonProgress[id].clear+'回','dungeonIntel',[id])).join('')+HB('敵図鑑','戦闘で判明した情報','enemyBook')+HB('噂と隠し地点','','rumors')+ha(HB('ギルドへ','','guild')))}
function dungeonIntel(id){const r=hc().regions[id];if(!r||!unlocked.includes(id))return;const d=H.discoveries[id];show('<h2>'+hesc(id)+'</h2><p class="message">'+hesc(r.intro)+'</p>'+HT('候補テーマ',r.themes.join(' / '))+HT('固有探索',r.mechanism+' / '+r.meter+' / 対応道具：'+r.item)+HT('調査記録','イベント '+d.events.length+'/6 / 隠し地点 '+d.secrets.length+'/1 / 救助 '+d.rescues+'件')+HB('この地域へ','','deployment',[id],activeRun())+back())}
function market(){if(!requireTown())return;show('<h2>市場</h2>'+HB('武器・盾','性能と装備条件を比較','weaponShop')+HB('防具','魔装・軽装・重装','armorShop')+HB('道具','まとめ買い・探索用の道具','toolShop')+HB('加工','地域素材で武具製作・強化・特性付与','craftMenu')+HB('売却','余剰素材・未使用武具・道具','sellMenu')+HB('保管庫','装備・道具・素材を預ける','storageMenu')+HB('バルンと話す','','npcTalk',['鍛冶師'])+back())}
function toolShop(){if(!requireTown())return;show('<h2>道具屋</h2>'+Object.entries(hc().tools).map(([n,d])=>HB(n+' / '+moneyText(d.price),'所持 '+(inventory.tools[n]||0)+' / '+d.desc,'toolQuantity',[n])).join('')+ha(HB('市場へ','','market')))}
function toolQuantity(n){if(!requireTown()||!hc().tools[n])return;show('<h2>'+hesc(n)+'</h2><p class="message">'+hesc(hc().tools[n].desc)+'</p>'+[1,5,10].map(q=>HB(q+'個買う',moneyText(q*hc().tools[n].price),'buyTool',[n,q],gold<q*hc().tools[n].price)).join('')+ha(HB('戻る','','toolShop')))}
function buyTool(n,q=1){if(!requireTown()||!hc().tools[n]||![1,5,10].includes(q))return;const price=hc().tools[n].price*q;if(gold<price)return note('所持金不足');gold-=price;inventory.tools[n]=(inventory.tools[n]||0)+q;persist();toolQuantity(n)}
function weaponPrice(n){return ({拳甲:650,短剣:700,王国剣:900,戦槌:900,戦斧:920,長槍:850,鞭:780,鎌:1050,刀:1100,長弓:900,銃:1200,短杖:780,小盾:600,回刃:760,呪符:780})[n]||1200}
function weaponShop(){if(!requireTown())return;const names=['拳甲','短剣','王国剣','戦槌','戦斧','長槍','鞭','鎌','刀','長弓','銃','短杖','呪符','小盾','回刃'];show('<h2>武器・盾</h2>'+names.map(n=>{const m=WM[n];return HB(n+(inventory.weapons.includes(n)?' ✓':''),m[0]+' / '+m[1]+' / 重量'+m[2]+' / '+moneyText(weaponPrice(n)),'gearDetail',[n])}).join('')+ha(HB('市場へ','','market')))}
function gearDetail(n){if(!WM[n])return;const m=WM[n],own=inventory.weapons.includes(n),recipe=hc().recipes.find(r=>r.name===n);show('<h2>'+hesc(n)+'</h2>'+HT(m[0]+' / '+m[1]+' / 重量 '+m[2],m[3]+' '+m[4]+' / 強化 +'+(upgrades[n]||0)+' / '+(traits[n]||'特性なし'))+HT('装備可能',names.filter((_,i)=>m[3]==='―'||stats[i][{PHY:0,SKL:1,ARC:2,MND:3}[m[3]]]>=m[4]).join(' / ')||'現在は要求値を満たす仲間がいません')+(own?HB('装備を見直す','','partyMenu'):recipe?HB('製作条件を見る','','recipeDetail',[hc().recipes.indexOf(recipe)]):HB('購入する',moneyText(weaponPrice(n)),'buyGear',[n],gold<weaponPrice(n)))+HB(H.favorites.includes(n)?'お気に入りを解除':'お気に入りに登録','','favoriteGear',[n])+back())}
function buyGear(n){if(!requireTown()||!WM[n]||inventory.weapons.includes(n)||hc().recipes.some(r=>r.name===n))return;const price=weaponPrice(n);if(gold<price)return note('所持金不足');gold-=price;inventory.weapons.push(n);persist();gearDetail(n)}
function favoriteGear(n){if(!WM[n])return;H.favorites=H.favorites.includes(n)?H.favorites.filter(x=>x!==n):H.favorites.concat(n);persist();gearDetail(n)}
function armorShop(){if(!requireTown())return;show('<h2>防具</h2>'+Object.entries(ARM).map(([n,m])=>HT(n+' / '+(inventory.armor.includes(n)?'所持済み':'未所持'),'一式：物防+'+m[2]+' / 魔防+'+m[3]+' / 重量'+m[0]*4)).join('')+HB('防具を変更する','現在の戦闘側と同じ一式単位で設定','partyMenu')+back())}
function craftMenu(){if(!requireTown())return;show('<h2>加工</h2>'+HB('地域武具の製作','12種 / 地域素材＋結晶＋G','recipeMenu')+HB('武器強化','300 G ＋ 魔力結晶1 / 上限+3','upgradeMenu')+HB('特性加工','森獣の皮2 / 1武器につき1特性','traitMenu')+back())}
function recipeMenu(){if(!requireTown())return;show('<h2>地域武具</h2>'+hc().recipes.map((r,i)=>HB(r.name+(inventory.weapons.includes(r.name)?' ✓':''),r.region+' / '+r.trait,'recipeDetail',[i],!unlocked.includes(r.region))).join('')+ha(HB('加工へ','','craftMenu')))}
function recipeDetail(i){const r=hc().recipes[i];if(!r||!unlocked.includes(r.region))return;show('<h2>'+hesc(r.name)+'</h2>'+HT(r.region,r.trait+' / 完成時 強化 +'+r.level)+HT('必要素材',Object.entries(r.materials).map(([n,q])=>(hc().labels[n]||n)+' '+(loot[n]||0)+'/'+q).join(' / ')+' / '+moneyText(r.gold))+HB('製作する','所持済みの武具を重複製作しません','craftRecipe',[i],inventory.weapons.includes(r.name)||gold<r.gold||Object.entries(r.materials).some(([n,q])=>(loot[n]||0)<q))+ha(HB('一覧へ','','recipeMenu')))}
function craftRecipe(i){if(!requireTown())return;const r=hc().recipes[i];if(!r||!unlocked.includes(r.region)||inventory.weapons.includes(r.name)||gold<r.gold||Object.entries(r.materials).some(([n,q])=>(loot[n]||0)<q))return;gold-=r.gold;for(const[n,q]of Object.entries(r.materials))loot[n]-=q;grant({gear:r.name});persist();recipeDetail(i)}
function upgradeMenu(){if(!requireTown())return;show('<h2>武器強化</h2>'+inventory.weapons.map(n=>HB(n+' +'+(upgrades[n]||0),'300 G ＋ 魔力結晶1','upgradeGear',[n],(upgrades[n]||0)>=3||gold<300||loot.結晶<1)).join('')+back())}
function upgradeGear(n){if(!requireTown()||!inventory.weapons.includes(n)||(upgrades[n]||0)>=3||gold<300||loot.結晶<1)return;gold-=300;loot.結晶--;upgrades[n]=(upgrades[n]||0)+1;persist();upgradeMenu()}
function traitMenu(){if(!requireTown())return;show('<h2>特性加工</h2>'+inventory.weapons.map(n=>HB(n,traits[n]||'なし','traitChoice',[n])).join('')+back())}
function traitChoice(n){if(!inventory.weapons.includes(n)||!requireTown())return;show('<h2>'+hesc(n)+'</h2>'+['対獣','軽量化','術式補助','重装特効','飛行特効','状態特効'].map(t=>HB(t,'森獣の皮2 / 現在の特性を上書き','setTrait',[n,t],loot.皮<2||traits[n]===t)).join('')+back())}
function setTrait(n,t){if(!requireTown()||!inventory.weapons.includes(n)||loot.皮<2||traits[n]===t||!['対獣','軽量化','術式補助','重装特効','飛行特効','状態特効'].includes(t))return;loot.皮-=2;traits[n]=t;persist();traitChoice(n)}
function dropRare(){const reg=H.run?.dungeon||H.selected||'古代迷宮',pool=hc().recipes.filter(r=>r.region===reg),r=pool[Math.floor(Math.random()*pool.length)];rareGear.push({uid:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),name:r.name,attr:r.meta[0]+'/'+r.meta[1],weight:r.meta[2],req:r.meta[3]+' '+r.meta[4],trait:r.trait,value:1800+hc().regions[reg].chapter*200,source:reg,level:r.level})}
function appraiseMenu(){if(!requireTown())return;show('<h2>査定</h2>'+HB('古器を査定する','所持 '+loot.古器+' / 1回最大20個','appraise',[],loot.古器<=0)+(rareGear.length?rareGear.map((r,i)=>HB(r.name,r.attr+' / '+r.trait+(inventory.weapons.includes(r.name)?' / 所持済み':''),'rareAppraise',[i])).join(''):HT('未引取の希少武具はありません'))+HB('保管庫','','storageMenu')+ha(HB('ギルドへ','','guild')))}
function appraise(){if(!requireTown()||loot.古器<1)return;const n=Math.min(20,loot.古器),before=rareGear.length;loot.古器-=n;let cash=0,crystal=0;for(let i=0;i<n;i++){const r=Math.random();if(r<.3)dropRare();else if(r<.6){loot.結晶++;crystal++}else cash+=250}gold+=cash;persist();checkpointResult('古器 '+n+'個の査定','希少武具 '+(rareGear.length-before)+'点 / 魔力結晶 '+crystal+' / '+moneyText(cash),'appraiseMenu')}
function rareAppraise(i){if(!requireTown()||!rareGear[i])return;const r=rareGear[i];show('<h2>'+hesc(r.name)+'</h2>'+HT(r.attr+' / 重量 '+r.weight,'要求 '+r.req+' / '+r.trait)+HB('武具として引き取る',inventory.weapons.includes(r.name)?'既に所持しています':'装備候補に追加','keepRare',[i],inventory.weapons.includes(r.name))+HB('売却する',moneyText(r.value),'sellRare',[i])+HB('保管庫へ','','storeRare',[i])+ha(HB('一覧へ','','appraiseMenu')))}
function keepRare(i){if(!requireTown()||!rareGear[i])return;const r=rareGear[i];if(inventory.weapons.includes(r.name))return note('既に所持しています。売却か保管を選んでください');WM[r.name]=[...r.attr.split('/'),r.weight,r.req.split(' ')[0],Number(r.req.split(' ')[1])||20];inventory.weapons.push(r.name);traits[r.name]=r.trait;upgrades[r.name]=r.level||1;rareGear.splice(i,1);persist();appraiseMenu()}
function sellRare(i){if(!requireTown()||!rareGear[i])return;gold+=rareGear[i].value;rareGear.splice(i,1);persist();appraiseMenu()}
function storeRare(i){if(!requireTown()||!rareGear[i])return;storage.push(rareGear.splice(i,1)[0]);persist();appraiseMenu()}
function restoreRare(i){if(!requireTown()||!storage[i])return;rareGear.push(storage.splice(i,1)[0]);persist();storageMenu()}
function inUse(n){return eq.some(a=>a.slice(0,9).some(x=>x.split('：')[1]===n))}
function sellMenu(){if(!requireTown())return;show('<h2>売却</h2>'+HB('素材を売る','','materialTrade')+inventory.weapons.map(n=>HB(n,inUse(n)?'装備・予備セットで使用中':moneyText(Math.floor(weaponPrice(n)/2)),'sellWeapon',[n],inUse(n))).join('')+Object.keys(hc().tools).filter(n=>inventory.tools[n]>0).map(n=>HB(n+' ×'+inventory.tools[n],'1個 '+moneyText(Math.floor(hc().tools[n].price/2)),'sellTool',[n])).join('')+back())}
function sellWeapon(n){if(!requireTown()||!inventory.weapons.includes(n)||inUse(n))return;gold+=Math.floor(weaponPrice(n)/2);inventory.weapons=inventory.weapons.filter(x=>x!==n);persist();sellMenu()}
function sellTool(n){if(!requireTown()||!hc().tools[n]||!(inventory.tools[n]>0))return;inventory.tools[n]--;gold+=Math.floor(hc().tools[n].price/2);persist();sellMenu()}
function materialTrade(){if(!requireTown())return;show('<h2>素材取引</h2>'+Object.entries(hc().materialPrices).map(([n,p])=>HB((hc().labels[n]||n)+' ×'+(loot[n]||0),'1個 '+moneyText(p),'materialQuantity',[n],!(loot[n]>0))).join('')+back())}
function materialQuantity(n){if(!hc().materialPrices[n]||!requireTown())return;show('<h2>'+hesc(hc().labels[n]||n)+'</h2>'+[1,5].map(q=>HB(q+'個売る',moneyText(q*hc().materialPrices[n]),'sellMaterial',[n,q],loot[n]<q)).join('')+HB('全て売る',moneyText((loot[n]||0)*hc().materialPrices[n]),'askSellAll',[n])+back())}
function askSellAll(n){if(!hc().materialPrices[n])return;confirmAction('素材を全て売却',(hc().labels[n]||n)+'を全て売ります。製作に使う分もなくなります。','sellMaterial',[n,loot[n]])}
function sellMaterial(n,q){if(!requireTown()||!hc().materialPrices[n]||!Number.isInteger(q)||q<1||q>(loot[n]||0))return;loot[n]-=q;gold+=q*hc().materialPrices[n];persist();materialTrade()}
function storageMenu(){if(!requireTown())return;show('<h2>保管庫</h2>'+HB('道具・素材を預ける','','depositMenu')+storage.map((r,i)=>HB(r.name,'未引取武具 / 引き出す','restoreRare',[i])).join('')+Object.entries(H.stash.tools).filter(([,q])=>q>0).map(([n,q])=>HB(n+' ×'+q,'道具 / 全て引き出す','withdraw',['tools',n])).join('')+Object.entries(H.stash.materials).filter(([,q])=>q>0).map(([n,q])=>HB((hc().labels[n]||n)+' ×'+q,'素材 / 全て引き出す','withdraw',['materials',n])).join('')+H.stash.weapons.map(n=>HB(n,'武具 / 引き出す','withdraw',['weapons',n])).join('')+back())}
function depositMenu(){if(!requireTown())return;show('<h2>保管庫に預ける</h2>'+Object.entries(inventory.tools).filter(([,q])=>q>0).map(([n,q])=>HB(n+' ×'+q,'道具を全て預ける','deposit',['tools',n])).join('')+Object.entries(loot).filter(([,q])=>q>0).map(([n,q])=>HB((hc().labels[n]||n)+' ×'+q,'素材を全て預ける','deposit',['materials',n])).join('')+inventory.weapons.map(n=>HB(n,inUse(n)?'装備中は預けられません':'武具を預ける','deposit',['weapons',n],inUse(n))).join('')+back())}
function deposit(kind,n){if(!requireTown())return;if(kind==='weapons'){if(!inventory.weapons.includes(n)||inUse(n))return;addUnique(H.stash.weapons,n);inventory.weapons=inventory.weapons.filter(x=>x!==n)}else if(['tools','materials'].includes(kind)){const source=kind==='tools'?inventory.tools:loot;if(!(source[n]>0))return;H.stash[kind][n]=(H.stash[kind][n]||0)+source[n];source[n]=0}else return;persist();storageMenu()}
function withdraw(kind,n){if(!requireTown())return;if(kind==='weapons'){if(!H.stash.weapons.includes(n))return;addUnique(inventory.weapons,n);H.stash.weapons=H.stash.weapons.filter(x=>x!==n)}else if(['tools','materials'].includes(kind)){const source=H.stash[kind],target=kind==='tools'?inventory.tools:loot;if(!(source[n]>0))return;target[n]=(target[n]||0)+source[n];source[n]=0}else return;persist();storageMenu()}
function merchantNode(){const n=currentNode();if(n?.type!=='merchant')return;if(!n.stock){n.stock={'回復薬':4,'解毒薬':3,'煙玉':2,'薬瓶':2,'魔力結晶':1,[region().item]:2};persist()}show('<h2>旅商人</h2>'+Object.entries(n.stock).map(([item,q])=>HB(item+' / 残り '+q,moneyText(merchantPrice(item)),'merchantBuy',[item],q<=0||gold<merchantPrice(item))).join('')+ha(HB('探索へ進む','','leaveNode')))}
function merchantPrice(n){return Math.floor((n==='魔力結晶'?500:(hc().tools[n]?.price||0)*1.25)*(hasSkill('窃盗')?.8:1))}
function merchantBuy(item){const n=currentNode();if(n?.type!=='merchant'||!(n.stock?.[item]>0)||gold<merchantPrice(item))return;gold-=merchantPrice(item);n.stock[item]--;if(item==='魔力結晶')loot.結晶++;else inventory.tools[item]=(inventory.tools[item]||0)+1;persist();merchantNode()}
function dungeonForge(){const n=currentNode();if(n?.type!=='forge')return;show('<h2>遺された工房</h2>'+HT('素材消費なしで1回だけ強化','設備の利用は、この地点で一度きりです。')+inventory.weapons.map(x=>HB(x+' +'+(upgrades[x]||0),'強化 +1 / 上限 +3','dungeonUpgrade',[x],n.used||(upgrades[x]||0)>=3)).join('')+ha(HB('探索へ進む','','leaveNode')))}
function dungeonUpgrade(n){const node=currentNode();if(node?.type!=='forge'||node.used||!inventory.weapons.includes(n)||(upgrades[n]||0)>=3)return;node.used=true;upgrades[n]=(upgrades[n]||0)+1;forge++;logRun(n+'を工房で強化');persist();dungeonForge()}
function items(){show('<h2>所持品</h2>'+HB('道具','回復・状態解除・探索用品','itemCategory',['道具'])+HB('武具','装備候補・お気に入り','itemCategory',['装備'])+HB('素材','地域素材・古器・結晶','itemCategory',['素材'])+HB('重要な記録','物語の手掛かり','itemCategory',['記録'])+(!activeRun()?HB('保管庫','','storageMenu'):'')+back())}
function itemCategory(t){if(t==='道具')show('<h2>道具</h2>'+Object.entries(hc().tools).filter(([n])=>inventory.tools[n]>0).map(([n,d])=>HB(n+' ×'+inventory.tools[n],d.desc,'useTool',[n])).join('')+ha(HB('戻る','','items')));else if(t==='素材')show('<h2>素材</h2>'+Object.entries(loot).filter(([,q])=>q>0).map(([n,q])=>HT((hc().labels[n]||n)+' ×'+q,n==='古器'?'ギルドで査定':Object.values(hc().regions).find(r=>r.material===n)?.title||'加工用素材')).join('')+back());else if(t==='記録')show('<h2>重要な記録</h2>'+(Object.keys(H.clues).map(n=>HT(n,'取得済み')).join('')||HT('まだ記録がありません'))+back());else show('<h2>武具</h2>'+inventory.weapons.slice().sort((a,b)=>Number(H.favorites.includes(b))-Number(H.favorites.includes(a))).map(n=>HB((H.favorites.includes(n)?'★ ':'')+n,'+'+(upgrades[n]||0)+' / '+(traits[n]||'特性なし'),'gearDetail',[n])).join('')+back())}
function useTool(n,i){const d=hc().tools[n];if(!d||!(inventory.tools[n]>0))return note('道具がありません');if(H.run?.battle)return pendingBattleMenu();if(d.field==='region'){if(!H.run)return note('この道具は探索中に使用します');if(region().item!==n)return note('この地域では仕掛けやイベントで使用する道具です');if(['浄化香','清水'].includes(n)){if(!H.run.hazard&&!(n==='浄化香'&&vitals.some(v=>v.status.poison>0)))return note('今は使用する必要がありません');inventory.tools[n]--;H.run.hazard=0;if(n==='浄化香')vitals.forEach(v=>{v.status.poison=0;v.statusPower.poison=0});logRun(n+'を使用');persist();drawDungeon();itemCategory('道具')}else mechanismMenu();return}if(!d.field)return note('この道具は戦闘の携行具として使用します');const needs=j=>{const v=vitals[j],m=rules().derived(stats[j]);return v.hp>0&&(d.field==='hp'?v.hp<m.hp:d.field==='poison'?(v.status.poison||0)>0:v.hp<m.hp||v.sp<m.sp)};if(i==null){const ids=[0,1,2,3,4,5].filter(needs);if(!ids.length)return note('使用が必要な仲間はいません');show('<h2>'+hesc(n)+' / 対象</h2>'+ids.map(j=>HB(names[j],'HP '+vitals[j].hp+'/'+rules().derived(stats[j]).hp,'useTool',[n,j])).join('')+back());return}if(!Number.isInteger(i)||i<0||i>=6||!needs(i))return;const v=vitals[i],m=rules().derived(stats[i]);if(d.field==='hp')v.hp=Math.min(m.hp,v.hp+Math.ceil(m.hp*.35));else if(d.field==='poison'){v.status.poison=0;v.statusPower.poison=0}else{v.hp=Math.min(m.hp,v.hp+15);v.sp=Math.min(m.sp,v.sp+10)}inventory.tools[n]--;logRun(names[i]+'に'+n+'を使用');persist();itemCategory('道具')}
function records(){show('<h2>記録</h2>'+HB('探索履歴',H.history.length+'件 / 最大40件','historyMenu')+HB('地域の踏査記録','イベント・隠し地点・救助','regionRecords')+HB('敵図鑑',journal.enemies.length+'種','enemyBook')+HB('人物・会話記録','','peopleBook')+HB('遺物の記録',journal.relics.length+'件','recordList',['遺物',journal.relics])+HB('噂',journal.rumors.length+'件','recordList',['噂',journal.rumors])+back())}
function historyMenu(){show('<h2>探索履歴</h2>'+(H.history.map(h=>HB(h.dungeon+' / '+h.result,'第'+h.floor+'層 / '+new Date(h.ended).toLocaleDateString('ja-JP'),'historyDetail',[h.id])).join('')||HT('探索から帰還すると記録されます'))+back())}
function historyDetail(id){const h=H.history.find(h=>h.id===id)||(lastExpedition.id===id?lastExpedition:null);if(!h)return;show('<h2>'+hesc(h.dungeon+' / '+h.result)+'</h2>'+HT('収支',(h.loot||[]).join(' / '))+(h.events||[]).map(x=>HT(x)).join('')+back())}
function regionRecords(){show('<h2>踏査記録</h2>'+Object.keys(hc().regions).filter(id=>unlocked.includes(id)).map(id=>HB(id,'イベント '+H.discoveries[id].events.length+'/6 / 隠し地点 '+H.discoveries[id].secrets.length+'/1','regionRecord',[id])).join('')+back())}
function regionRecord(id){const d=H.discoveries[id];if(!d)return;show('<h2>'+hesc(id)+'</h2>'+hc().events.filter(e=>e.region===id).map(e=>HT(d.events.includes(e.id)?e.name:'未発見の出来事',d.events.includes(e.id)?e.result:'')).join('')+hc().secrets.filter(s=>s.region===id).map(s=>HT(d.secrets.includes(s.id)?s.name:'未発見の隠し地点')).join('')+back())}
function enemyBook(){const list=[...new Set(journal.enemies)];show('<h2>敵図鑑</h2>'+(list.map(n=>{const d=journal.enemyData[n]||{};return HB(n,'遭遇 '+(d.seen||1),'enemyRecord',[n])}).join('')||HT('敵と遭遇すると記録されます'))+back())}
function enemyRecord(n){const d=journal.enemyData[n]||{};show('<h2>'+hesc(n)+'</h2>'+HT('属性相性',Object.entries(d.attributes||{}).map(([k,v])=>k+'：'+({0:'無効',.5:'耐性',1:'標準',2:'弱点'}[v]||v)).join(' / ')||'未判明')+HT('状態異常・封じ',Object.entries(d.statuses||{}).map(([k,v])=>k+'：'+v).join(' / ')||'未判明')+HT('部位記録',(d.parts||[]).map(p=>p.name+' / '+p.effect).join('\n')||'なし')+back())}
function peopleBook(){show('<h2>人物・会話記録</h2>'+hc().companion.map((c,i)=>HB(c[0],'仲間 / 会話 '+(H.companions[i]?.length||0)+'/3','talkArchive',['companion',i])).join('')+hc().npcs.map(n=>HB(n.name,n.role,'talkArchive',['npc',n.id])).join('')+back())}
function recordList(title,list){show('<h2>'+hesc(title)+'</h2>'+((list||[]).map(x=>HT(x)).join('')||HT('まだ記録がありません'))+back())}
