let masterySelection=null;
function masteryBadges(i){const owned=Object.entries(ranksFor(i)).filter(([g,r])=>r>0&&rules().masteries[g]);return '<div class="overview-masteries" aria-label="習得マスタリー">'+(owned.length?owned.map(([g,r])=>'<span>'+hesc(g)+' <b>'+r+'</b></span>').join(''):'<span>マスタリー未習得</span>')+'</div>'}
function masteryWorkspace(i,t='習得済み',g,b){
 if(H.run?.battle)return pendingBattleMenu();if(!Number.isInteger(i)||i<0||i>=names.length)return;
 const draft=masterySession(i),v=draft.value;const defs=rules().masteries,list=Object.entries(defs).filter(([n,d])=>t==='習得済み'?(v.ranks[n]||0)>0:d.category===t);
 if(!list.some(([n])=>n===g))g=list[0]?.[0];const def=defs[g],branches=Object.keys(def?.branches||{});if(b!==undefined&&!branches.includes(b))b='';const previous=masterySelection,same=previous?.i===i&&previous?.g===g,scroll=same?(document.querySelector('.mastery-right')?.scrollTop||0):0,leftScroll=previous?.i===i&&previous?.t===t?(document.querySelector('.mastery-list')?.scrollTop||0):0;const openBranches=new Set(same&&b!==undefined?previous.openBranches||[]:[]);if(b)openBranches.add(b);masterySelection={i,t,g,b,openBranches:[...openBranches]};
 const button=(text,action,args,disabled=false,selected=false)=>'<button class="row" data-hub="'+action+'" data-args="'+hesc(JSON.stringify(args))+'"'+(disabled?' disabled':'')+(selected?' aria-pressed="true"':'')+'>'+text+'</button>';
 const rank=v.ranks[g]||0,baseRank=draft.base.ranks[g]||0,category=def?.category,limited=['源泉','術法','技能'].includes(category),limit=category==='源泉'?1:2,full=limited&&!v.owned[category].includes(g)&&v.owned[category].length>=limit;
 const navigation='<aside class="mastery-left"><div class="mastery-list">'+(list.length?list.map(([n])=>button('<b>'+hesc(n)+'</b><small>Rank '+(v.ranks[n]||0)+'/10'+((v.ranks[n]||0)!==(draft.base.ranks[n]||0)?'（仮）':'')+'</small><span class="small">'+hesc(masteryDescription(n))+'</span>','growMastery',[i,n],false,n===g)).join(''):'<p class="small">習得済みなし。上の分類から選択。</p>')+'</div>'+(def?'<div class="mastery-training">'+button('<b>＋ Rank 1</b><small>'+(full?category+'の取得上限':rank>=10?'最大Rank':'仮振り · 1 Pt')+'</small>','uiMasteryRank',[i,g,1],v.points<1||rank>=10||full)+button('<b>− Rank 1</b><small>仮振りを戻す · 1 Pt返却</small>','uiMasteryRank',[i,g,-1],rank<=baseRank)+'</div>':'')+'</aside>';

 const cards=branch=>(def?.branches[branch]||[]).map(n=>{const d=rules().meta(n),u=d.unlocks.find(x=>x.mastery===g&&x.branch===branch),owned=draft.base.learned.includes(n),pending=draft.steps.some(s=>s.type==='skill'&&s.n===n),ok=rules().canLearn(n,g,v.ranks,stats[i])&&v.points>0&&(!limited||v.owned[category].includes(g));return button('<b>'+(owned?'✓ ':'')+hesc(n)+'</b><span class="item-explain">'+hesc(skillExplanation(d))+'</span><span class="small">'+(d.mode==='Passive'?'パッシブ':'アクティブ')+' / コスト '+d.setCost+(d.costType?' / '+d.costType+' '+d.cost:'')+'<br>要求 Rank '+u.rank+' / '+u.stat+' '+u.value+'</span><strong class="learn-state">'+(owned?'習得済み':pending?'習得予定 · タップで戻す':ok?'習得予約 · 1 Pt':v.points<1?'ポイント不足':'条件未達')+'</strong>','uiMasterySkill',[i,g,branch,n],owned||(!pending&&!ok))}).join('');
 const tabs=['習得済み','武器','防具','源泉','術法','技能'].map(n=>button(hesc(n),'masteryType',[i,n],false,n===t)).join('');
 const accordion=branches.map((branch,index)=>{const open=openBranches.has(branch),id='mastery-branch-'+i+'-'+index;return '<section class="mastery-branch"><button class="row branch-toggle" data-hub="uiMasteryBranch" data-args="'+hesc(JSON.stringify([i,g,branch]))+'" aria-expanded="'+open+'" aria-controls="'+id+'"><span class="branch-label"><b>'+hesc(branch)+'</b><small>'+hesc(rules().branchDescription(g,branch))+'</small></span><span aria-hidden="true">'+(open?'−':'＋')+'</span></button><div id="'+id+'" class="mastery-branch-skills"'+(!open?' hidden':'')+'>'+(open?cards(branch):'')+'</div></section>'}).join('');
 show('<h2>'+hesc(names[i])+' / 修練</h2><div class="section-meta mastery-points"><div><b>マスタリーポイント 残り '+v.points+' Pt</b><small>使用予定 '+draft.steps.length+' Pt / 所持 '+draft.base.points+' Pt</small></div>'+button('<b>修練を確定</b>','uiMasteryApply',[i],!draft.steps.length)+'<small class="mastery-point-help">左：ランク＋1に1 Pt ／ 右：スキル習得に1 Pt<br>仮振りは戻せます。確定後、スキル画面でセット。</small></div><div class="ui-tabs mastery-categories">'+tabs+'</div><div class="mastery-workspace">'+navigation+'<section class="mastery-right" aria-label="系統と習得スキル">'+(def?'<div class="mastery-skill-heading"><b>'+hesc(g)+'の系統</b></div>'+accordion:'<p class="small">マスタリーを選択してください。</p>')+'</section></div>');
 const right=document.querySelector('.mastery-right'),left=document.querySelector('.mastery-list');if(left)left.scrollTop=leftScroll;if(right){right.scrollTop=scroll;const opened=[...right.querySelectorAll('[aria-expanded="true"]')].find(e=>JSON.parse(e.dataset.args)[2]===b);if(opened){const a=opened.getBoundingClientRect(),r=right.getBoundingClientRect();if(a.top<r.top||a.bottom>r.bottom)right.scrollTop+=a.top-r.top;}}
}

let masteryDraft=null;
function masteryDraftBase(i){return {ranks:cp(ranksFor(i)),owned:cp(masteryOwned[i]),learned:learned[i].slice(),tree:learnedTree[i].slice(),points:masteryPt[i],stats:stats[i].slice()}}
function masteryDiscard(){masteryDraft=null}
function masterySession(i){const base=masteryDraftBase(i);if(!masteryDraft||masteryDraft.i!==i||JSON.stringify(base)!==JSON.stringify(masteryDraft.base))masteryDraft={i,base,steps:[],value:cp(base)};return masteryDraft}
function masteryRebuild(d){
 const v=cp(d.base),kept=[];
 for(const step of d.steps){if(v.points<1)continue;const def=rules().masteries[step.g];if(!def)continue;const c=def.category,limited=['源泉','術法','技能'].includes(c);
 if(step.type==='rank'){const r=v.ranks[step.g]||0;if(r>=10)continue;if(limited&&!v.owned[c].includes(step.g)){if(v.owned[c].length>=(c==='源泉'?1:2))continue;v.owned[c].push(step.g)}v.ranks[step.g]=Math.min(10,r+1)}
 else{if(v.learned.includes(step.n)||!def.branches[step.b]?.includes(step.n)||!rules().canLearn(step.n,step.g,v.ranks,v.stats)||(limited&&!v.owned[c].includes(step.g)))continue;v.learned.push(step.n);v.tree.push(step.n)}
 v.points--;kept.push(step);
 }d.value=v;d.steps=kept;
}
function masteryDraftRender(i){const s=masterySelection;return s?.i===i&&s.g?window.masterySkills(i,s.g,s.b):window.mastery(i)}
function masteryRankAdjust(i,g,delta){if(H.run?.battle)return;const d=masterySession(i);if(delta===1)d.steps.push({type:'rank',g});else{const idx=d.steps.findLastIndex(s=>s.type==='rank'&&s.g===g);if(idx>=0)d.steps.splice(idx,1)}masteryRebuild(d);masteryDraftRender(i)}
function masterySkillToggle(i,g,b,n){if(H.run?.battle)return;const d=masterySession(i),idx=d.steps.findIndex(s=>s.type==='skill'&&s.n===n);if(idx>=0)d.steps.splice(idx,1);else d.steps.push({type:'skill',g,b,n});masteryRebuild(d);masteryDraftRender(i)}
function masteryApply(i){if(H.run?.battle||masteryDraft?.i!==i)return;const d=masteryDraft;if(JSON.stringify(masteryDraftBase(i))!==JSON.stringify(d.base)){masteryDiscard();return masteryDraftRender(i)}masteryRebuild(d);if(!d.steps.length)return;window.masteryRanks[i]=cp(d.value.ranks);masteryOwned[i]=cp(d.value.owned);learned[i]=d.value.learned.slice();learnedTree[i]=d.value.tree.slice();masteryPt[i]=d.value.points;masteryDiscard();persist();masteryDraftRender(i)}
