let masterySelection=null;
function masteryBadges(i){const owned=Object.entries(ranksFor(i)).filter(([g,r])=>r>0&&rules().masteries[g]);return '<div class="overview-masteries" aria-label="習得マスタリー">'+(owned.length?owned.map(([g,r])=>'<span>'+hesc(g)+' <b>'+r+'</b></span>').join(''):'<span>マスタリー未習得</span>')+'</div>'}
function masteryWorkspace(i,t='習得済み',g,b){
 if(H.run?.battle)return pendingBattleMenu();if(!Number.isInteger(i)||i<0||i>=names.length)return;
 const defs=rules().masteries,list=Object.entries(defs).filter(([n,d])=>t==='習得済み'?(ranksFor(i)[n]||0)>0:d.category===t);
 if(!list.some(([n])=>n===g))g=list[0]?.[0];const def=defs[g],branches=Object.keys(def?.branches||{});if(!branches.includes(b))b=branches[0];masterySelection={i,t,g,b};
 const button=(text,action,args,disabled=false,selected=false)=>'<button class="row" data-hub="'+action+'" data-args="'+hesc(JSON.stringify(args))+'"'+(disabled?' disabled':'')+(selected?' aria-pressed="true"':'')+'>'+text+'</button>';
 const rank=ranksFor(i)[g]||0,category=def?.category,limited=['源泉','術法','技能'].includes(category),limit=category==='源泉'?1:2,full=limited&&!masteryOwned[i][category].includes(g)&&masteryOwned[i][category].length>=limit;
 const navigation='<aside class="mastery-left"><div class="mastery-list">'+(list.length?list.map(([n])=>button('<b>'+hesc(n)+'</b><small>Rank '+(ranksFor(i)[n]||0)+'/50</small><span class="small">'+hesc(masteryDescription(n))+'</span>','growMastery',[i,n],false,n===g)).join(''):'<p class="small">習得済みなし。上の分類から選択。</p>')+'</div>'+(def?'<div class="mastery-branches"><b>'+hesc(g)+'の4系統</b><div>'+branches.map(n=>button('<b>'+hesc(n)+'</b>','masterySkills',[i,g,n],false,n===b)).join('')+'</div>'+button('<b>Rank '+rank+' → '+Math.min(50,rank+5)+'</b><small>'+(full?category+'の取得上限':rank>=50?'最大Rank':'成長 ＋5 / 1 Pt')+'</small>','trainMastery',[i,g],mp[i]<1||rank>=50||full)+'</div>':'')+'</aside>';
 const ns=def?.branches[b]||[],cards=ns.map(n=>{const d=rules().meta(n),u=d.unlocks.find(x=>x.mastery===g&&x.branch===b),owned=learned[i].includes(n),ok=rules().canLearn(n,g,ranksFor(i),stats[i])&&mp[i]>0&&(!limited||masteryOwned[i][category].includes(g));return button('<b>'+(owned?'✓ ':'')+hesc(n)+'</b><span class="item-explain">'+hesc(skillExplanation(d))+'</span><span class="small">'+(d.mode==='Passive'?'パッシブ':'アクティブ')+' / コスト '+d.setCost+(d.costType?' / '+d.costType+' '+d.cost:'')+'<br>要求 Rank '+u.rank+' / '+u.stat+' '+u.value+'</span><strong class="learn-state">'+(owned?'習得済み':ok?'習得する · 1 Pt':mp[i]<1?'ポイント不足':'条件未達')+'</strong>','learnSkill',[i,g,b,n],owned||!ok)}).join('');
 const tabs=['習得済み','武器','防具','源泉','術法','技能'].map(n=>button(hesc(n),'masteryType',[i,n],false,n===t)).join('');
 show('<h2>'+hesc(names[i])+' / Mastery</h2><div class="section-meta"><b>Mastery '+mp[i]+' Pt</b></div><div class="ui-tabs mastery-categories">'+tabs+'</div><div class="mastery-workspace">'+navigation+'<section class="mastery-right"><div class="mastery-skill-heading"><b>'+hesc(b||'スキル')+'</b></div><div class="mastery-skill-list">'+cards+'</div></section></div>');
}
