/* Hub UI v9. Presentation only; save schema, rewards and battle engine stay unchanged. */
(()=>{
'use strict';
const U={route:null,stack:[],render:null,back:false,opener:null,filters:{},search:{},inventory:'道具',sortie:'formation',toast:null,formationSelected:null};
const old={};
const originals=['town','drawDungeon','closeM','skills','equip','character','partyMenu','settings','charAbility','charMastery','mastery','masteryType','growMastery','masterySkills','toggleLearnedSkill'];
for(const n of originals)old[n]=window[n];
const portraits=['gald','lize','ern','sena','mirea','yuna'];
const attrs=['PHY','SKL','ARC','MND'];
const statusNames={poison:'猛毒',blind:'盲目',sleep:'睡眠',agitate:'動揺',stun:'気絶',headBind:'頭封じ',armBind:'腕封じ',legBind:'脚封じ'};
const statusText=i=>Object.entries(vitals[i].status||{}).filter(([,n])=>n>0).map(([s,n])=>(statusNames[s]||s)+' '+n+'T').join(' / ');
const data=(n,a=[])=>' data-hub="'+n+'" data-args="'+hesc(JSON.stringify(a))+'"';
const pill=(text,kind='')=>'<span class="tag '+kind+'">'+hesc(text)+'</span>';
const section=(name,html)=>'<section class="ui-section"><h3>'+hesc(name)+'</h3>'+html+'</section>';
const hint=text=>'<p class="screen-hint">'+hesc(text)+'</p>';
const tabs=(items,chosen,fn,args=[])=>'<div class="ui-tabs" role="group" aria-label="表示切替">'+items.map(([v,n])=>'<button type="button"'+data(fn,[...args,v])+' aria-pressed="'+(v===chosen)+'">'+hesc(n)+'</button>').join('')+'</div>';
const resources=i=>{const v=vitals[i],m=rules().derived(stats[i]);return '<div class="resource-grid">'+['hp','sp'].map(k=>'<div><span>'+k.toUpperCase()+'</span><b>'+v[k]+'<small> / '+m[k]+'</small></b><i class="resource-track '+k+'"><i style="width:'+(m[k]?Math.max(0,v[k]/m[k]*100):0)+'%"></i></i></div>').join('')+'</div>'};
const actorTabs=(i,active)=>'<div class="actor-tabs">'+tabs([['overview','概要'],['attributes','能力値'],['equip','装備'],['skills','スキル'],['growth','育成']],active,'uiActor',[i])+'</div>';
const actorBasics=i=>'<section class="status-basics">'+resources(i)+'<div class="basic-abilities">'+attrs.map((n,j)=>'<span><small>'+n+' · '+['肉体','技能','異能','精神'][j]+'</small><b>'+stats[i][j]+'</b></span>').join('')+'</div></section>';
const statusPortrait=i=>'<section class="actor-hero status-cover"><div class="status-caption"><b>'+hesc(names[i])+'</b><span>'+hesc(battleStyle(i))+' · '+rows[i]+'</span></div></section>';

const actorKey=new Set(['character','charOverview','actorAttributes','charAbility','equip','skills','mastery','charMastery','equipChoice']);
const key=r=>r?(['equip','equipChoice'].includes(r.name)?'fitting:'+r.args[0]:actorKey.has(r.name)?'actor:'+r.args[0]:r.name==='equipChoice'?'equipChoice:'+r.args[0]+':'+r.args[1]:['questMenu','toolShop','itemCategory','items'].includes(r.name)?r.name:JSON.stringify(r)):'none';
const recordRoute=(r,scroll)=>({route:r?{name:r.name,args:r.args.slice()}:null,scroll});
const isOpen=()=>document.getElementById('modal').classList.contains('on');
const focusables=()=>[...document.querySelectorAll('#panel button:not(:disabled),#panel input,#panel summary,#panel a[href],#panel [tabindex="0"]')].filter(e=>!e.closest('[hidden]')&&e.getClientRects().length);
const badgeCounts=()=>({reports:hc().quests.filter(q=>qstate(q).state===2).length,chapters:H.story.pending.filter(r=>!H.story.completed.includes(r)).length,appraisal:loot.古器+rareGear.length});
const activeQuest=()=>{const q=findQuest(H.tracked);return q&&[1,2].includes(qstate(q).state)?q:null};
const objective=()=>{const q=activeQuest();if(q){const s=qstate(q);return HB(q.n,s.state===2?'達成・ギルドへ報告':q.d+' · '+s.progress+'/'+q.target,'questSelect',[q.id])}return ''};
const warnings=()=>{const a=[];for(let i=0;i<6;i++){const w=weightInfo(i),carry=eq[i][9].split('：')[1];if(vitals[i].hp<=0)a.push({i,text:'戦闘不能',action:'character'});if(statusText(i))a.push({i,text:statusText(i),action:'character'});if(!rules().fits(stats[i],skillSet[i]))a.push({i,text:'セットCost超過',action:'skills'});else if(!skillSet[i].length)a.push({i,text:'スキル未設定',action:'skills'});if(w.level)a.push({i,text:'重量 '+w.weight+'/'+w.limit,action:'equip'});if(carry!=='なし'&&!(inventory.tools[carry]>0))a.push({i,text:carry+' 残り0',action:'equip'})}return a};
const noticeList=()=>warnings().map(w=>HB(names[w.i]+' · '+w.text,'',''+w.action,[w.i])).join('');
const npcPortraits={受付:'../images/npc_eda_stand.svg',鍛冶師:'../images/npc_balun_stand.svg',学者:'../images/npc_iris_stand.svg',宿主:'../images/npc_marta_stand.svg',伝令:'../images/npc_noa_stand.svg',守人:'../images/npc_sahir_stand.svg'};
const personCard=(img,name,meta,action,args=[])=>'<button class="person-select-card"'+data(action,args)+'><img src="'+img+'" alt=""><span><b>'+hesc(name)+'</b><small>'+hesc(meta)+'</small></span><span class="member-arrow">›</span></button>';
const peopleGrid=items=>'<div class="people-select-grid">'+items.join('')+'</div>';
const memberGrid=()=>peopleGrid(names.map((n,i)=>personCard('../images/'+portraits[i]+'.svg',n,rows[i]+' · '+battleStyle(i),'character',[i])));
const routeGroup=n=>/guild|guildDesk|quest|reportChapter|appraise|storage|deposit|withdraw|infoMenu|dungeonIntel|regionRecord|enemyBook/.test(n)?'guild':/market|gearShopMenu|toolShop|toolQuantity|weaponShop|armorShop|gearDetail|craft|recipe|upgrade|trait|sell|materialTrade|materialQuantity/.test(n)?'market':/inn|roomMenu|innRest|items|itemCategory|records|history|peopleBook|personRecord|talkArchive|conversation|memberTalk|npcMenu|npcTalk|pairMenu|readPair|partyMenu|readiness|preset|character|char|mastery|equip|skills|dungeon|deployment/.test(n)?'inn':'';
const navState=n=>{const group=routeGroup(n);document.querySelectorAll('#app nav button').forEach(b=>{const on=!!group&&b.dataset.hub===group;b.classList.toggle('current',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})};
const showUI=html=>{
 const priorFocus=document.activeElement,focusAction=priorFocus?.dataset?.hub,focusArgs=priorFocus?.dataset?.args;const panel=document.getElementById('panel'),open=isOpen(),scroll=panel.querySelector('.panel-body')?.scrollTop||0,r=U.render||{name:'note',args:['メニューを閉じて操作を続けてください。']};
 if(!['equip','equipChoice'].includes(r.name))fittingDiscard();
 if(r.name!=='actorAttributes')attributeDiscard();
 const same=key(U.route)===key(r);if(!open){U.stack=[];U.opener=U.launcher||document.activeElement;U.launcher=null}else if(U.route&&!same&&!U.back)U.stack.push(recordRoute(U.route,scroll));if(U.stack.length>24)U.stack.shift();U.route={name:r.name,args:r.args.slice()};
 const temp=document.createElement('div');temp.innerHTML=html;const title=temp.querySelector('h2'),heading=title?.textContent||'メニュー';if(title)title.remove();
 // Navigation remains at the bottom; commit actions belong to the content they change.
 const confirmation=[...temp.querySelectorAll('.actions')].find(a=>[...a.querySelectorAll('button')].some(b=>/^(やめる|取り消す|取消|キャンセル)$/.test(b.textContent.trim())));
 let cancelRoute=null;
 if(confirmation){for(const b of confirmation.querySelectorAll('button'))if(b.dataset.hub==='closeM'){b.dataset.hub='uiBack';b.textContent='取り消す'}for(const b of [...confirmation.querySelectorAll('button')])if(/^(やめる|取り消す|取消|キャンセル)$/.test(b.textContent.trim())){if(b.dataset.hub&&b.dataset.hub!=='uiBack')cancelRoute={action:b.dataset.hub,args:b.dataset.args||'[]'};b.remove()}confirmation.className='inline-confirm';}
 temp.querySelectorAll('button').forEach(b=>{if(b.dataset.hub==='closeM'||/^(戻る|一覧へ|一覧|ギルドへ|市場へ|編成へ|宿・酒場へ|加工へ|キャラクターへ)$/.test(b.textContent.trim()))b.remove()});
 temp.querySelectorAll('.actions').forEach(a=>{if(!a.children.length)a.remove()});
 const controls=temp.querySelector('.fitting-controls'),controlsMarkup=controls?.outerHTML||'';controls?.remove();
 const actorRoute=/^(character|charOverview|actorAttributes|charAbility|charMastery|equip|equipChoice|skills|mastery|masteryType|growMastery|masterySkills|resistView)$/.test(r.name),actorId=Number(r.args[0]),overview=['character','charOverview'].includes(r.name);
 const tabBlock=temp.querySelector('.actor-tabs'),tabMarkup=tabBlock?.outerHTML||(actorRoute?actorTabs(actorId,/equip/i.test(r.name)?'equip':r.name==='skills'?'skills':r.name==='actorAttributes'?'attributes':overview?'overview':'growth'):'');tabBlock?.remove();
 const basics=temp.querySelector('.status-basics'),basicsMarkup=basics?.outerHTML||'';basics?.remove();
 if(actorRoute&&!overview)temp.querySelector('.actor-hero')?.remove();
 panel.classList.toggle('status-overview',overview);panel.classList.toggle('status-growth',r.name==='charAbility');panel.classList.toggle('actor-workspace',actorRoute);
 const hero=temp.querySelector('.actor-hero,.fitting-summary');const heroMarkup=hero?.outerHTML||'';hero?.remove();
 panel.classList.toggle('actor-panel',!!heroMarkup);
 const fixed=document.createElement('div');fixed.className='actor-fixed';
 if(actorRoute&&!overview)for(const child of [...temp.children])if(child.matches('.screen-hint,p.small,.section-meta,.cost-meter,.ui-tabs,.search-input,.ui-help,.attribute-heading,.allocation-bar,.allocation-grid')||r.name==='growMastery'&&child.matches('button')&&child.textContent.includes('成長 +5')){fixed.append(child)}
 panel.classList.toggle('status-attributes',r.name==='actorAttributes');
 const fixedMarkup=fixed.children.length?fixed.outerHTML:'';
 const backdrop=actorRoute?'<div class="actor-backdrop" aria-hidden="true"><img src="../images/'+portraits[actorId]+'.svg" alt=""></div>':'';

 const trade=/guildSell|guildSale|market|Shop|Quantity|gearDetail|recipe|Recipe|craft|upgrade|trait|sell|storage|deposit|appraise|Appraise|merchant/.test(r.name);
 panel.innerHTML=backdrop+'<div class="panel-head"><h2 id="panelTitle" tabindex="-1">'+hesc(heading)+'</h2>'+(actorRoute?'<div class="actor-header-switch"><button class="icon-button"'+data('uiActor',[(actorId+5)%6,/equip/i.test(r.name)?'equip':r.name==='skills'?'skills':r.name==='actorAttributes'?'attributes':overview?'overview':'growth'])+' aria-label="前の仲間">‹</button><button class="icon-button"'+data('uiActor',[(actorId+1)%6,/equip/i.test(r.name)?'equip':r.name==='skills'?'skills':r.name==='actorAttributes'?'attributes':overview?'overview':'growth'])+' aria-label="次の仲間">›</button></div>':'')+(trade?'<span class="panel-money">'+moneyText(gold)+'</span>':'')+'</div>'+heroMarkup+basicsMarkup+controlsMarkup+fixedMarkup+'<div class="panel-body">'+temp.innerHTML+'</div><footer class="panel-footer" aria-label="画面の操作">'+tabMarkup+'<div class="panel-navigation"><button class="panel-back" data-hub="uiBack" aria-label="前の画面へ"'+(!U.stack.length?' hidden':'')+'>‹ 戻る</button><button class="modal-x" data-hub="closeM" aria-label="閉じる">閉じる</button></div></footer>';

 if(cancelRoute){const back=panel.querySelector('.panel-back');back.hidden=false;back.dataset.hub=cancelRoute.action;back.dataset.args=cancelRoute.args}
 panel.setAttribute('aria-labelledby','panelTitle');document.getElementById('modal').classList.add('on');document.getElementById('app').inert=true;panel.scrollTop=0;const body=panel.querySelector('.panel-body');if(same)body.scrollTop=scroll;navState(r.name);const nextFocus=same&&focusAction?[...panel.querySelectorAll('[data-hub]')].find(e=>e.dataset.hub===focusAction&&e.dataset.args===focusArgs&&!e.disabled):null;(nextFocus||panel.querySelector('#panelTitle')).focus({preventScroll:true});
};
const closeUI=()=>{fittingDiscard();attributeDiscard();document.getElementById('modal').classList.remove('on');document.getElementById('app').inert=false;U.route=null;U.stack=[];U.formationSelected=null;if(hubBooted){renderRoster();if(!activeRun())window.town();else navState('town')}const target=U.opener;U.opener=null;const fallback=target?.dataset?.hub?[...document.querySelectorAll('#app [data-hub]')].find(e=>e.dataset.hub===target.dataset.hub&&e.dataset.args===target.dataset.args):null;(target?.isConnected?target:fallback||document.querySelector('#app nav .current'))?.focus({preventScroll:true})};
const toast=text=>{const e=document.getElementById('uiToast');if(!e)return;e.textContent=text;e.hidden=false;clearTimeout(U.toast);U.toast=setTimeout(()=>e.hidden=true,2400)};
const uiActions={
 uiBack(){const frame=U.stack.pop();if(!frame)return closeUI();U.back=true;try{const fn=window[frame.route.name];if(typeof fn==='function')fn(...frame.route.args);else closeUI();const b=document.querySelector('#panel .panel-body');if(b)b.scrollTop=frame.scroll}finally{U.back=false}},
 uiActor(i,tab='overview'){if(!Number.isInteger(i)||i<0||i>=6)return;({overview:character,attributes:actorAttributes,equip,skills,growth:charAbility}[tab]||character)(i)},
 uiFormationCell(pos){if(H.run?.battle)return pendingBattleMenu();if(!Number.isInteger(pos)||pos<0||pos>8)return;ensureFormation();const selected=U.formationSelected;if(selected==null){if(H.formation[pos]==null)return;U.formationSelected=pos;return partyMenu()}if(selected===pos){U.formationSelected=null;return partyMenu()}const value=H.formation[selected];H.formation[selected]=H.formation[pos];H.formation[pos]=value;U.formationSelected=null;syncFormationRows();persist();partyMenu()},
 uiClearTrack(){H.tracked=null;persist();questMenu('active')},
 uiDismissStatus(){closeM();settings()},
 uiCarryUsers(n){if(H.run?.battle)return pendingBattleMenu();if(!hc().tools[n]?.battle)return;show('<h2>'+hesc(n)+'を携行</h2>'+names.map((name,i)=>HB(name,eq[i][9],'setEquip',[i,9,n])).join(''))},
 uiMapLegend(){show('<h2>地図の見方</h2><div class="legend-grid">'+[['battle','戦闘'],['explore','調査'],['event','出来事'],['camp','野営'],['elite','強敵'],['merchant','旅商人'],['forge','工房'],['stairs','次の層']].map(([type,t])=>HT(nodeIcon({type})+' '+t)).join('')+'</div><p class="small">明るい地点を選択。進んだ後は、前の分岐へ戻れません。</p>')},
 uiSupply(){if(!requireTown())return;toolShop('field')},
 uiQuestList(){questMenu('active')},
 uiInventory(t){U.inventory=t;itemCategory(t)},
 uiSearchSkills(value){if(U.route?.name==='skills')U.search[U.route.args[0]]=value;filterSkillRows(value)},
 uiEquipPreview(i,k,n){if(!Number.isInteger(i)||!Number.isInteger(k))return;window.equipChoice(i,k,n)},
 uiNotify(text){toast(String(text))}
};
Object.assign(window,uiActions);
const views={
 back(){return ''},show:showUI,closeM:closeUI,
 town(){if(activeRun()){closeM();return drawDungeon()}document.getElementById('modal').classList.remove('on');document.getElementById('app').inert=false;U.route=null;U.stack=[];document.querySelector('h1').textContent='王都レクシア';document.querySelector('header .small').textContent=H.story.ending?'調査のつづき':'冒険者区';
 const b=badgeCounts(),reg=unlocked.includes(H.selected)?H.selected:unlocked[unlocked.length-1];
 const notices=(b.chapters?HB('探索結果を報告',b.chapters+'件','guild'):'')+(b.reports?HB('依頼を報告',b.reports+'件','questMenu',['ready']):'')+(b.appraisal?HB('遺物の査定',b.appraisal+'点','appraiseMenu'):'');
 document.getElementById('screen').innerHTML='<section class="town-scene town-home"><div class="home-objective"><span class="chapter-kicker">次にやること</span>'+HB(H.story.intro?storyObjective():'地下から響く鐘','','storyMenu')+'</div>'+(objective()?'<div class="tracked-objective">'+objective()+'</div>':'')+(notices?'<div class="attention-strip">'+notices+'</div>':'')+'<button class="town-dungeon-strip"'+data('partyMenu',['destination'])+'><span><small>次の出撃先</small><b>'+hesc(reg)+'</b></span><span class="town-dungeon-strip-action">行き先 ›</span></button><div class="town-command-grid">'+place('♨','宿屋','休息・会話','inn')+place('⚜','ギルド','依頼・資料','guild')+place('⚒','市場','購入・加工','market')+'</div><div class="town-location-meta"><span class="chapter-kicker">LEXIA</span><small>冒険者区</small></div></section>';document.getElementById('money').textContent=moneyText(gold);renderRoster();renderSaveStatus();navState('')},
 renderRoster(){if(!stats||!vitals)return;document.querySelectorAll('#party .m').forEach((b,i)=>{const m=rules().derived(stats[i]),v=vitals[i],state=statusText(i);b.classList.toggle('down',v.hp<=0);b.title=names[i]+' / '+rows[i]+' / HP '+v.hp+'/'+m.hp+' / SP '+v.sp+'/'+m.sp+(state?' / '+state:'');b.setAttribute('aria-label',b.title);b.innerHTML='<img src="../images/'+portraits[i]+'.svg" alt=""><b>'+names[i]+'</b><span class="roster-meta">'+(rows[i]==='前列'?'前':'後')+' · '+v.hp+'/'+m.hp+'</span><span class="roster-bars">'+['hp','sp'].map(k=>'<span class="roster-line"><em>'+k.charAt(0).toUpperCase()+'</em><i class="resource-track '+k+'"><i style="width:'+(m[k]?v[k]/m[k]*100:0)+'%"></i></i></span>').join('')+'</span>'+(state?'<span class="roster-alert" aria-label="状態異常あり">!</span>':'')});},
 partyMenu(tab='formation'){if(H.run?.battle)return pendingBattleMenu();if(!['formation','members','destination'].includes(tab))tab='formation';U.sortie=tab;ensureFormation();const ws=warnings(),labels=['前','中','後'],selected=U.formationSelected,cell=(pos)=>{const i=H.formation[pos],sel=selected===pos;if(i==null)return '<button class="formation-empty '+(sel?'selected':'')+'"'+data('uiFormationCell',[pos])+' aria-label="'+labels[Math.floor(pos/3)]+'列 空き">＋</button>';const issue=ws.some(w=>w.i===i);return '<div class="formation-member '+(sel?'selected ':'')+(issue?'has-issue':'')+'"><button class="formation-pick"'+data('uiFormationCell',[pos])+' aria-pressed="'+sel+'"><img src="../images/'+portraits[i]+'.svg" alt=""><b>'+hesc(names[i])+'</b>'+(issue?'<span class="formation-issue" aria-label="要確認">!</span>':'')+'</button><button class="formation-config"'+data('character',[i])+' aria-label="'+hesc(names[i])+'の設定">設定</button></div>'};const row=r=>'<div class="formation-row"><span class="formation-row-label">'+labels[r]+'</span><div class="formation-slots">'+[0,1,2].map(col=>cell(r*3+col)).join('')+'</div></div>';let body='';if(tab==='formation')body='<div class="formation-board sortie-formation">'+[0,1,2].map(row).join('')+'</div>';else if(tab==='members')body=memberGrid();else{const id=unlocked.includes(H.selected)?H.selected:unlocked[unlocked.length-1],r=hc().regions[id];body='<div class="destination-brief"><b>'+hesc(id)+'</b><small>'+hesc(r.mechanism)+'\n全3層</small></div>'+HB('行き先を変更','','dungeon')+HB('準備確認',ws.length?ws.length+'件の要確認':'問題なし','readiness')+'<div class="sticky-action sortie-start"><button class="primary-action" data-hub="startDungeon">出撃 →</button></div>'}show('<h2>出撃準備</h2>'+tabs([['formation','陣形'],['members','仲間'],['destination','行き先']],tab,'partyMenu')+hint(tab==='formation'?'9マスに配置。通常攻撃は正面列の最前の敵を狙います。':tab==='members'?'仲間ごとに装備・スキル・育成を確認します。':'行き先を選び、準備確認後に出撃します。')+body)},
 character(i){if(H.run?.battle)return pendingBattleMenu();if(!Number.isInteger(i)||i<0||i>=6)return;show('<h2>'+hesc(names[i])+'</h2>'+statusPortrait(i)+actorBasics(i)+actorTabs(i,'overview')+(statusText(i)?'<p class="status-warning">'+hesc(statusText(i))+'</p>':''))},
 charOverview(i){return character(i)},
 charAbility(i){return mastery(i)},
 resistView(i){const r=calcResist(i);show('<h2>'+names[i]+' / 耐性</h2>'+actorHero(i)+section('属性','<div class="resist-grid">'+['斬','突','壊','火','水','風','土','光','闇'].map(k=>'<span>'+k+' <b>'+(r[k]?r[k]+'%':'—')+'</b></span>').join('')+'</div>')+section('状態異常・封じ','<div class="resist-grid">'+Object.keys(r).filter(k=>!['斬','突','壊','火','水','風','土','光','闇'].includes(k)).map(k=>'<span>'+k+' <b>'+(r[k]?r[k]+'%':'—')+'</b></span>').join('')+'</div>')+'<p class="small">— は追加耐性なし。</p>')},
 equip(i){return fittingScreen(i)},
 equipChoice(i,k,preview){return fittingScreen(i,k,preview)},
 skills(i,filter){if(H.run?.battle)return pendingBattleMenu();if(filter!==undefined)U.filters[i]=filter;filter=U.filters[i]||'All';const query=U.search[i]||'',chosen=skillSet[i],ns=learned[i].filter(n=>rules().meta(n)&&(filter==='All'||filter==='set'?filter!=='set'||chosen.includes(n):rules().meta(n).mode===filter)).sort((a,b)=>Number(chosen.includes(b))-Number(chosen.includes(a)));show('<h2>'+names[i]+'</h2>'+actorTabs(i,'skills')+actorHero(i)+hint('タップでセット／解除。Costはセット容量、SPは技・術の消費気力。パッシブはセット中に発動。')+'<details class="ui-help"><summary>攻撃範囲の読み方</summary><p class="small">正面＝自分と同じ縦列。スルー＝最前の敵を1体飛ばす。横指定＝攻撃する列を選ぶ。範囲と射程は各スキルの説明で確認できます。</p></details>'+'<div class="cost-meter"><b>Cost '+skillCost(i)+' / '+skillCap(i)+'</b><i><i style="width:'+Math.min(100,skillCost(i)/skillCap(i)*100)+'%"></i></i></div>'+tabs([['All','すべて'],['set','セット中'],['Active','技・術'],['Passive','パッシブ']],filter,'skills',[i])+'<input id="skillSearch" class="search-input" type="search" placeholder="スキルを検索" value="'+hesc(query)+'" aria-label="スキル検索" oninput="uiSearchSkills(this.value)">'+(ns.length?ns.map(n=>{const d=rules().meta(n),on=chosen.includes(n),usable=skillUsable(i,n),next=on?chosen.filter(x=>x!==n):chosen.concat(n),fits=rules().fits(stats[i],next);return '<div data-skill-name="'+hesc(n)+'"><button class="row skill-toggle '+(on?'selected':'')+'"'+data('toggleLearnedSkill',[i,n])+' aria-pressed="'+on+'"'+(!fits?' disabled':'')+'><b>'+hesc(n)+'<span class="cost-label">'+effectiveCost(i,n)+'</span></b><span class="item-explain">'+hesc(skillExplanation(d))+'</span><span class="small">'+hesc(skillDescription(d)+(d.costType?' · '+d.costType+' '+d.cost:''))+'</span>'+(!fits?'<span class="inline-warning">変更後のCost上限を超えます</span>':!usable?'<span class="small equipment-needed">現在の装備では使用不可</span>':'')+'</button></div>'}).join(''):HT('該当するスキルはありません'))+'<p id="skillEmpty" class="empty-message" hidden>一致するスキルはありません。</p>');filterSkillRows(query)},
 filterSkillRows(text){let count=0;document.querySelectorAll('[data-skill-name]').forEach(e=>{e.hidden=!e.dataset.skillName.toLowerCase().includes(text.toLowerCase());if(!e.hidden)count++});const m=document.getElementById('skillEmpty');if(m)m.hidden=count>0},
 mastery(i){return masteryType(i,'習得済み')},
 masteryType(i,t='習得済み'){if(H.run?.battle)return pendingBattleMenu();const list=Object.entries(rules().masteries).filter(([g,d])=>t==='習得済み'?(ranksFor(i)[g]||0)>0:d.category===t);show('<h2>'+hesc(names[i])+' / Mastery</h2>'+actorTabs(i,'growth')+hint('育てる系統を選択。1 PtでRank＋5、スキル習得は別途1 Pt。')+'<div class="section-meta"><b>Mastery</b><span>'+mp[i]+' Pt</span></div>'+tabs(['習得済み','武器','防具','源泉','術法','技能'].map(x=>[x,x]),t,'masteryType',[i])+(t==='源泉'||t==='術法'||t==='技能'?hint(t+'は'+(t==='源泉'?'1':'2')+'系統まで取得できます。'):'')+(list.length?list.map(([g,d])=>HB(g+'　Rank '+(ranksFor(i)[g]||0)+'/50',masteryDescription(g),'growMastery',[i,g])).join(''):HT('まだ取得していません','上の系統を選んで育成できます。')))},
 charMastery(i){return mastery(i)},
 readiness(){if(H.run?.battle)return pendingBattleMenu();const ws=warnings();show('<h2>準備確認</h2>'+hint('装備・スキル・重量・状態をまとめて確認してから出撃します。')+(ws.length?noticeList():HT('準備完了','前列3人・後列3人'))+HB('編成へ','','partyMenu')+(activeRun()?HB('探索へ戻る','','resumeExpedition'):HB('出撃確認へ',H.selected||dungeonId,'deployment',[H.selected||dungeonId])))},
 items(){return itemCategory(U.inventory)},
 itemCategory(t='道具'){U.inventory=t;let body='';if(t==='道具')body=Object.entries(hc().tools).filter(([n])=>inventory.tools[n]>0).map(([n,d])=>HB(n+' ×'+inventory.tools[n],toolDescription(n),d.field?'useTool':'uiCarryUsers',[n])).join('');else if(t==='素材')body=Object.entries(loot).filter(([,q])=>q>0).map(([n,q])=>HT((hc().labels[n]||n)+' ×'+q,n==='古器'?'ギルドで査定':'')).join('');else if(t==='記録')body=Object.keys(H.clues).map(n=>HB(n,'詳細を読む','clueRecord',[n])).join('');else body=inventory.weapons.slice().sort((a,b)=>Number(H.favorites.includes(b))-Number(H.favorites.includes(a))).map(n=>HB((H.favorites.includes(n)?'★ ':'')+n,weaponDescription(n)+' / +'+(upgrades[n]||0)+' / '+(traits[n]||'特性なし'),'gearDetail',[n])).join('');show('<h2>所持品</h2>'+tabs([['道具','道具'],['装備','武具'],['素材','素材'],['記録','重要品']],t,'uiInventory')+(body||HT('まだ所持していません')))},
 roomMenu(){if(!requireTown())return;const p=H.pendingGrowth||{stat:0,mastery:0},pending=(p.stat||p.mastery)?('未精算 Stat '+(p.stat||0)+' / Mastery '+(p.mastery||0)):'全回復';show('<h2>部屋で休む</h2>'+HB('休息する',pending,'innRest')+HB('所持品','','items')+HB('記録','','records'))},
 inn(){if(!requireTown())return;const n=typeof conversationCounts==='function'?conversationCounts():{companion:0,npc:0,pairs:0};show('<h2>宿屋</h2>'+HB('部屋で休む','休息・所持品・記録','roomMenu')+HB('仲間と会話',(n.companion+n.pairs)?'新着 '+(n.companion+n.pairs)+'件':'','conversation')+HB('客と会話',n.npc?'新着 '+n.npc+'件':'','npcMenu')+HB('出撃準備','陣形・仲間・行き先','partyMenu'))},
 conversation(){if(!requireTown())return;const cards=hc().companion.map((x,i)=>personCard('../images/'+portraits[i]+'.svg',x[0],x[1]+' · '+(H.companions[i]?.length||0)+'/3','memberTalk',[i]));show('<h2>仲間と会話</h2>'+peopleGrid(cards)+HB('仲間同士の会話','','pairMenu'))},
 npcMenu(){if(!requireTown())return;const cards=hc().npcs.map(n=>personCard(npcPortraits[n.id]||'../images/npc_marta.svg',n.name,n.role+' · '+(H.talks[n.id]?.length||0)+'/3','npcTalk',[n.id]));show('<h2>客と会話</h2>'+peopleGrid(cards))},
 questMenu(filter='active'){const counts={open:hc().quests.filter(q=>qstate(q).state===0&&syncQuestAvailability().some(a=>a.id===q.id)).length,active:hc().quests.filter(q=>[1,2].includes(qstate(q).state)).length,ready:hc().quests.filter(q=>qstate(q).state===2).length,done:hc().quests.filter(q=>qstate(q).state===3).length};const list=hc().quests.filter(q=>filter==='all'||(filter==='active'?[1,2].includes(qstate(q).state):qstate(q).state===({open:0,ready:2,done:3}[filter]??1)));show('<h2>依頼掲示板</h2>'+tabs([['open','未受注'],['active','進行中 '+counts.active],['ready','報告 '+counts.ready],['done','完了']],filter,'questMenu')+(activeRun()?'<p class="small">探索中は進捗のみ確認できます。</p>':'')+(list.length?list.map(q=>{const st=qstate(q),available=syncQuestAvailability().some(a=>a.id===q.id);return HB((H.tracked===q.id?'★ ':'')+q.n,q.d+' · '+(st.state===0?available?'受注可能':'未開放':st.state===2?'報告待ち':st.state===3?'報告済み':st.progress+'/'+q.target),'questSelect',[q.id])}).join(''):HT('該当する依頼はありません'))+(!activeRun()&&counts.ready?HB('達成分を一括報告',counts.ready+'件','reportAll'):'')+(H.tracked?HB('追跡を解除','','uiClearTrack'):'')+HB('全件を見る','','questMenu',['all']))},
 questSelect(id){const q=findQuest(id);if(!q)return;const st=qstate(q),available=syncQuestAvailability().some(a=>a.id===q.id),prereq=q.prereq?findQuest(q.prereq):null;show('<h2>'+hesc(q.n)+'</h2>'+pill(q.d)+'<p class="message">'+hesc(q.description)+'</p>'+HT('進捗 '+st.progress+'/'+q.target,'報酬 '+moneyText(q.reward)+' · Stat '+q.stat+' / Mastery '+q.mastery+' Pt')+(activeRun()?(st.state===1?HB(H.tracked===q.id?'追跡中':'追跡する','','trackQuest',[q.id],H.tracked===q.id):''):st.state===0?HB('受注する',available?'':!unlocked.includes(q.d)?'地域未開放':prereq?'前提：'+prereq.n+'を報告':'前提条件未達成','acceptQuest',[q.id],!available):st.state===2?HB('達成報告','','claimQuest',[q.id]):st.state===3?HT('報告済み'):HB('この地域の出撃準備','','deployment',[q.d]))+(st.state===1&&!activeRun()?HB(H.tracked===q.id?'追跡中':'追跡する','','trackQuest',[q.id],H.tracked===q.id)+'<details class="ui-help"><summary>依頼の管理</summary>'+HB('取り下げる','進捗はリセットされます','askAbandonQuest',[q.id])+'</details>':''))},
 deployment(id){if(activeRun())return expeditionMenu();if(!hc().regions[id]||!unlocked.includes(id))return note('この地域は未開放です');dungeonId=id;H.selected=id;persist();partyMenu('destination')},
 settings(){show('<h2>設定</h2>'+section('表示・操作',HB('文字サイズ',H.settings.text,'cycleText')+HB('表示密度',H.settings.density||'標準','toggleCompact')+HB('重要操作の確認',H.settings.confirm?'ON':'OFF','toggleConfirm'))+section('セーブ',HT(hubSaveError?'保存に失敗しています':'自動保存',hubSaveError||'操作ごとに保存')+HB('今すぐ保存','','manualSave')+HB('書き出す','JSONファイル','exportSave')+HB('読み込む','確認後に置き換え','chooseImport'))+'<details class="ui-help danger-zone"><summary>データ管理</summary>'+HB('バックアップ復元','','askRestore',[],!RPG_STORE.getItem(HUB_BACKUP))+HB('最初から始める','進行を初期化','resetSave')+'</details>')},
 manualSave(){toast(saveGame()?'保存しました':'保存できません。書き出しを利用してください。');renderSaveStatus()},
 drawDungeon(){old.drawDungeon();navState('town');const root=document.querySelector('.expedition');if(!root)return;const q=activeQuest();if(q){const e=document.createElement('button');e.className='field-quest';e.setAttribute('data-hub','questSelect');e.dataset.args=JSON.stringify([q.id]);e.textContent='★ '+q.n+' '+qstate(q).progress+'/'+q.target;root.querySelector('.field-head').after(e)}const head=root.querySelector('.field-head');if(head){const help=document.createElement('button');help.className='icon-button';help.setAttribute('data-hub','uiMapLegend');help.setAttribute('aria-label','地図の見方');help.textContent='?';head.append(help)}const generic=root.querySelector('.field-actions .row.static .small');if(generic)generic.remove()}
};
Object.assign(window,views);
window.HUB_UI_ACTIONS=Object.keys(uiActions);
// Safe render-only history. Returning re-renders from current state, never replays purchases or rewards.
const routes=['actorAttributes','guildMembers','guildSellMenu','guildSaleQuantity','guildSaleConfirm','storyMenu','readStory','reportChapter','epilogue','guild','guildDesk','questMenu','questSelect','inn','roomMenu','innRest','returnTalk','conversation','memberTalk','npcMenu','npcTalk','pairMenu','readPair','talkArchive','rumors','rumorDetail','infoMenu','dungeonIntel','market','gearShopMenu','toolShop','toolQuantity','weaponShop','gearDetail','armorShop','armorDetail','armorEquipMenu','craftMenu','recipeMenu','recipeDetail','upgradeMenu','traitMenu','traitChoice','appraiseMenu','rareAppraise','sellMenu','materialTrade','materialQuantity','storageMenu','depositMenu','merchantNode','dungeonForge','items','itemCategory','records','explorationStats','historyMenu','historyDetail','regionRecords','regionRecord','enemyBook','enemyRecord','peopleBook','personRecord','clueRecord','recordList','partyMenu','readiness','equip','equipChoice','skills','presetMenu','askSavePreset','settings','character','charOverview','charAbility','resistView','charMastery','mastery','masteryType','growMastery','masterySkills','squadMenu','rowSwapMenu','dungeon','deployment','camp','moraleMenu','expeditionMenu','runJournal','battlePrep','mechanismMenu','eventChoice','explorationNode','stairsMenu','secretNode','pendingBattleMenu','note','checkpointResult','uiCarryUsers','uiMapLegend'];
for(const name of routes){const render=window[name];if(typeof render!=='function')continue;window[name]=(...args)=>{const previous=U.render;U.render={name,args};try{return render(...args)}finally{U.render=previous}}}
// Modal focus, keyboard escape and touch navigation work independently of game state.
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!isOpen())return;const list=focusables(),first=list[0],last=list[list.length-1];if(!first)return;e.stopPropagation();if(e.shiftKey&&(document.activeElement===first||!list.includes(document.activeElement))){last.focus();e.preventDefault()}else if(!e.shiftKey&&(document.activeElement===last||!list.includes(document.activeElement))){first.focus();e.preventDefault()}});
document.addEventListener('click',e=>{if(e.target.closest('#app nav')){U.stack=[];U.route=null}const el=e.target.closest('[data-hub],button[onclick]');if(!el)return;if(el.closest('#app'))U.launcher=el;if(el.closest('#panel')&&!el.disabled){U.opener=U.opener?.isConnected?U.opener:document.querySelector('#app nav .current')}},true);
window.HUB_UI={version:21,state:U,warnings,resources};
})();
