/* Hub UI v8. Presentation only; save schema, rewards and battle engine stay unchanged. */
(()=>{
'use strict';
const U={route:null,stack:[],render:null,back:false,opener:null,filters:{},search:{},inventory:'道具',toast:null};
const old={};
const originals=['town','drawDungeon','closeM','skills','equip','character','partyMenu','settings','charAbility','charMastery','mastery','masteryType','growMastery','masterySkills','toggleLearnedSkill'];
for(const n of originals)old[n]=window[n];
const portraits=['gald','lize','ern','sena','mirea','yuna'];
const attrs=['PHY','SKL','ARC','MND'];
const statusNames={poison:'猛毒',blind:'盲目',sleep:'睡眠',agitate:'動揺',stun:'気絶',headBind:'頭封じ',armBind:'腕封じ',legBind:'脚封じ'};
const statusText=i=>Object.entries(vitals[i].status||{}).filter(([,n])=>n>0).map(([s,n])=>(statusNames[s]||s)+' '+n+'T').join(' / ');
const data=(n,a=[])=>' data-hub="'+n+'" data-args="'+hesc(JSON.stringify(a))+'"';
const pill=(text,kind='')=>'<span class="tag '+kind+'">'+hesc(text)+'</span>';
const section=(name,html)=>'<section class="ui-section"><h3>'+hesc(name)+'</h3>'+html+'</section>';
const tabs=(items,chosen,fn,args=[])=>'<div class="ui-tabs" role="group" aria-label="表示切替">'+items.map(([v,n])=>'<button type="button"'+data(fn,[...args,v])+' aria-pressed="'+(v===chosen)+'">'+hesc(n)+'</button>').join('')+'</div>';
const resources=i=>{const v=vitals[i],m=rules().derived(stats[i]);return '<div class="resource-grid">'+['hp','sp','mp'].map(k=>'<div><span>'+k.toUpperCase()+'</span><b>'+v[k]+'<small> / '+m[k]+'</small></b><i class="resource-track '+k+'"><i style="width:'+(m[k]?Math.max(0,v[k]/m[k]*100):0)+'%"></i></i></div>').join('')+'</div>'};
const actorTabs=(i,active)=>'<div class="actor-switch"><button class="icon-button"'+data('uiActor',[(i+5)%6,active])+' aria-label="前の仲間">‹</button><span>'+hesc(battleStyle(i))+' · '+rows[i]+'</span><button class="icon-button"'+data('uiActor',[(i+1)%6,active])+' aria-label="次の仲間">›</button></div>'+tabs([['overview','概要'],['ability','能力'],['equip','装備'],['skills','スキル'],['mastery','育成']],active,'uiActor',[i]);
const actorKey=new Set(['character','charOverview','charAbility','equip','skills','mastery','charMastery']);
const key=r=>r?(actorKey.has(r.name)?'actor:'+r.args[0]:['questMenu','toolShop','itemCategory','items'].includes(r.name)?r.name:JSON.stringify(r)):'none';
const recordRoute=(r,scroll)=>({route:r?{name:r.name,args:r.args.slice()}:null,scroll});
const isOpen=()=>document.getElementById('modal').classList.contains('on');
const focusables=()=>[...document.querySelectorAll('#panel button:not(:disabled),#panel input,#panel summary,#panel a[href],#panel [tabindex="0"]')].filter(e=>!e.closest('[hidden]')&&e.getClientRects().length);
const badgeCounts=()=>({reports:hc().quests.filter(q=>qstate(q).state===2).length,chapters:H.story.pending.filter(r=>!H.story.completed.includes(r)).length,appraisal:loot.古器+rareGear.length});
const activeQuest=()=>{const q=findQuest(H.tracked);return q&&[1,2].includes(qstate(q).state)?q:null};
const objective=()=>{const q=activeQuest();if(q){const s=qstate(q);return HB(q.n,s.state===2?'達成・ギルドへ報告':q.d+' · '+s.progress+'/'+q.target,'questSelect',[q.id])}return ''};
const warnings=()=>{const a=[];for(let i=0;i<6;i++){const w=weightInfo(i),carry=eq[i][9].split('：')[1];if(vitals[i].hp<=0)a.push({i,text:'戦闘不能',action:'character'});if(statusText(i))a.push({i,text:statusText(i),action:'character'});if(!rules().fits(stats[i],skillSet[i]))a.push({i,text:'セットCost超過',action:'skills'});else if(!skillSet[i].length)a.push({i,text:'スキル未設定',action:'skills'});if(w.level)a.push({i,text:'重量 '+w.weight+'/'+w.limit,action:'equip'});if(carry!=='なし'&&!(inventory.tools[carry]>0))a.push({i,text:carry+' 残り0',action:'equip'})}return a};
const noticeList=()=>warnings().map(w=>HB(names[w.i]+' · '+w.text,'',''+w.action,[w.i])).join('');
const routeGroup=n=>/settings|Save|Import|Restore|reset|cycleText|toggleConfirm/.test(n)?'settings':/party|character|char|mastery|Mastery|equip|Equip|skills|Skill|Formation|squad|readiness|preset|Preset/.test(n)?'partyMenu':/items|itemCategory|storage|deposit|withdraw|Tool|Carry/.test(n)?'items':/records|Record|history|History|Book|Archive/.test(n)?'records':'town';
const navState=n=>{document.querySelectorAll('#app nav button').forEach(b=>{const on=b.dataset.hub===routeGroup(n);b.classList.toggle('current',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});const b=document.querySelector('#app nav [data-hub="town"]');if(b){b.innerHTML='<span class="ico">'+(activeRun()?'◇':'⌂')+'</span>'+(activeRun()?'探索':'拠点');b.setAttribute('aria-label',activeRun()?'探索地図':'拠点')}};
const showUI=html=>{
 const priorFocus=document.activeElement,focusAction=priorFocus?.dataset?.hub,focusArgs=priorFocus?.dataset?.args;const panel=document.getElementById('panel'),open=isOpen(),scroll=panel.querySelector('.panel-body')?.scrollTop||0,r=U.render||{name:'note',args:['メニューを閉じて操作を続けてください。']};
 const same=key(U.route)===key(r);if(!open){U.stack=[];U.opener=U.launcher||document.activeElement;U.launcher=null}else if(U.route&&!same&&!U.back)U.stack.push(recordRoute(U.route,scroll));if(U.stack.length>24)U.stack.shift();U.route={name:r.name,args:r.args.slice()};
 const temp=document.createElement('div');temp.innerHTML=html;const title=temp.querySelector('h2'),heading=title?.textContent||'メニュー';if(title)title.remove();
 // Close belongs to the fixed header, not a second card at the foot of every list.
 temp.querySelectorAll('.actions').forEach(a=>{const bs=[...a.querySelectorAll('button')];if(bs.length&&bs.every(b=>b.dataset.hub==='closeM'||['閉じる','戻る','一覧へ','一覧','ギルドへ','市場へ','編成へ','宿・酒場へ','加工へ'].includes(b.textContent.trim()))&&U.stack.length)a.remove()});
 const trade=/market|Shop|Quantity|gearDetail|recipe|Recipe|craft|upgrade|trait|sell|storage|deposit|appraise|Appraise|merchant/.test(r.name);
 panel.innerHTML='<div class="panel-head"><button class="icon-button panel-back" data-hub="uiBack" aria-label="前の画面へ"'+(!U.stack.length?' hidden':'')+'>‹</button><h2 id="panelTitle" tabindex="-1">'+hesc(heading)+'</h2>'+(trade?'<span class="panel-money">'+moneyText(gold)+'</span>':'')+'<button class="modal-x" data-hub="closeM" aria-label="閉じる">×</button></div><div class="panel-body">'+temp.innerHTML+'</div>';
 panel.setAttribute('aria-labelledby','panelTitle');document.getElementById('modal').classList.add('on');document.getElementById('app').inert=true;panel.scrollTop=0;const body=panel.querySelector('.panel-body');if(same)body.scrollTop=scroll;navState(r.name);const nextFocus=same&&focusAction?[...panel.querySelectorAll('[data-hub]')].find(e=>e.dataset.hub===focusAction&&e.dataset.args===focusArgs&&!e.disabled):null;(nextFocus||panel.querySelector('#panelTitle')).focus({preventScroll:true});
};
const closeUI=()=>{document.getElementById('modal').classList.remove('on');document.getElementById('app').inert=false;U.route=null;U.stack=[];if(hubBooted){renderRoster();if(!activeRun())window.town();else navState('town')}const target=U.opener;U.opener=null;const fallback=target?.dataset?.hub?[...document.querySelectorAll('#app [data-hub]')].find(e=>e.dataset.hub===target.dataset.hub&&e.dataset.args===target.dataset.args):null;(target?.isConnected?target:fallback||document.querySelector('#app nav .current'))?.focus({preventScroll:true})};
const toast=text=>{const e=document.getElementById('uiToast');if(!e)return;e.textContent=text;e.hidden=false;clearTimeout(U.toast);U.toast=setTimeout(()=>e.hidden=true,2400)};
const uiActions={
 uiBack(){const frame=U.stack.pop();if(!frame)return closeUI();U.back=true;try{const fn=window[frame.route.name];if(typeof fn==='function')fn(...frame.route.args);else closeUI();const b=document.querySelector('#panel .panel-body');if(b)b.scrollTop=frame.scroll}finally{U.back=false}},
 uiActor(i,tab='overview'){if(!Number.isInteger(i)||i<0||i>=6)return;({overview:character,ability:charAbility,equip,skills,mastery}[tab]||character)(i)},
 uiClearTrack(){H.tracked=null;persist();questMenu('active')},
 uiDismissStatus(){closeM();settings()},
 uiCarryUsers(n){if(H.run?.battle)return pendingBattleMenu();if(!hc().tools[n]?.battle)return;show('<h2>'+hesc(n)+'を携行</h2>'+names.map((name,i)=>HB(name,eq[i][9],'setEquip',[i,9,n])).join(''))},
 uiMapLegend(){show('<h2>地図の見方</h2><div class="legend-grid">'+[['battle','戦闘'],['explore','調査'],['event','出来事'],['camp','野営'],['elite','強敵'],['merchant','旅商人'],['forge','工房'],['stairs','次の層']].map(([type,t])=>HT(nodeIcon({type})+' '+t)).join('')+'</div><p class="small">明るい地点を選択。進んだ後は、前の分岐へ戻れません。</p>')},
 uiSupply(){if(!requireTown())return;toolShop('field')},
 uiQuestList(){questMenu('active')},
 uiInventory(t){U.inventory=t;itemCategory(t)},
 uiSearchSkills(value){if(U.route?.name==='skills')U.search[U.route.args[0]]=value;filterSkillRows(value)},
 uiNotify(text){toast(String(text))}
};
Object.assign(window,uiActions);
const views={
 back(){return ''},show:showUI,closeM:closeUI,
 town(){if(activeRun()){closeM();return drawDungeon()}document.getElementById('modal').classList.remove('on');document.getElementById('app').inert=false;U.route=null;U.stack=[];document.querySelector('h1').textContent='王都レクシア';document.querySelector('header .small').textContent=H.story.ending?'調査のつづき':'冒険者区';
 const b=badgeCounts(),reg=unlocked.includes(H.selected)?H.selected:unlocked[unlocked.length-1],chapter=Math.min(4,H.story.completed.length+1);
 const notices=(b.chapters?HB('探索結果を報告',b.chapters+'件','guild'):'')+(b.reports?HB('依頼を報告',b.reports+'件','questMenu',['ready']):'')+(b.appraisal?HB('遺物の査定',b.appraisal+'点','appraiseMenu'):'');
 document.getElementById('screen').innerHTML='<section class="town-scene"><div class="home-objective"><span class="chapter-kicker">'+(H.story.ending?'EPILOGUE':'CHAPTER 0'+chapter)+'</span>'+HB(H.story.intro?storyObjective():'地下から響く鐘','','storyMenu')+'</div>'+(objective()?'<div class="tracked-objective">'+objective()+'</div>':'')+(notices?'<div class="attention-strip">'+notices+'</div>':'')+'<div class="town-spacer" aria-hidden="true"></div><div class="places">'+place('♨','宿・酒場','会話・噂','inn')+place('⚜','ギルド','依頼・査定','guild')+place('⚒','市場','購入・加工','market')+'</div><div class="departure-card"><button class="region-select" data-hub="dungeon"><span class="chapter-kicker">EXPEDITION</span><b>'+hesc(reg)+'</b><small>行き先を変更 ›</small></button><div class="departure-bottom"><span class="small">全3層 · '+hesc(hc().regions[reg].mechanism)+'</span><button class="primary-action"'+data('deployment',[reg])+'>出撃準備 <span>→</span></button></div></div></section>';document.getElementById('money').textContent=moneyText(gold);renderRoster();renderSaveStatus();navState('town')},
 renderRoster(){if(!stats||!vitals)return;document.querySelectorAll('#party .m').forEach((b,i)=>{const m=rules().derived(stats[i]),v=vitals[i],state=statusText(i);b.classList.toggle('down',v.hp<=0);b.title=names[i]+' / '+rows[i]+' / HP '+v.hp+'/'+m.hp+' / SP '+v.sp+'/'+m.sp+' / MP '+v.mp+'/'+m.mp+(state?' / '+state:'');b.setAttribute('aria-label',b.title);b.innerHTML='<img src="../images/'+portraits[i]+'.svg" alt=""><b>'+names[i]+'</b><span class="roster-meta">'+(rows[i]==='前列'?'前':'後')+' · '+v.hp+'/'+m.hp+'</span><span class="roster-bars">'+['hp','sp','mp'].map(k=>'<span class="roster-line"><em>'+k.charAt(0).toUpperCase()+'</em><i class="resource-track '+k+'"><i style="width:'+(m[k]?v[k]/m[k]*100:0)+'%"></i></i></span>').join('')+'</span>'+(state?'<span class="roster-alert" aria-label="状態異常あり">!</span>':'')});},
 partyMenu(){if(H.run?.battle)return pendingBattleMenu();show('<h2>編成</h2><div class="toolbar">'+HB('隊列','','squadMenu')+HB('プリセット','','presetMenu')+HB('準備確認',warnings().length?String(warnings().length)+'件':'','readiness')+'</div>'+['前列','後列'].map(row=>section(row+' · 3人',names.map((n,i)=>rows[i]!==row?'':('<button class="party-member"'+data('character',[i])+'><img src="../images/'+portraits[i]+'.svg" alt=""><span><b>'+n+'</b><small>'+hesc(eq[i][0].split('：')[1])+' / '+hesc(battleStyle(i))+'</small><small>Cost '+skillCost(i)+'/'+skillCap(i)+(statusText(i)?' · '+hesc(statusText(i)):'')+'</small></span><span class="member-arrow">›</span></button>')).join(''))).join(''))},
 character(i){if(H.run?.battle)return pendingBattleMenu();if(!Number.isInteger(i)||i<0||i>=6)return;show('<h2>'+hesc(names[i])+'</h2>'+actorTabs(i,'overview')+resources(i)+(statusText(i)?'<p class="inline-warning">'+hesc(statusText(i))+'</p>':'')+section('装備',HB(eq[i][0].split('：')[1]+' / '+eq[i][1].split('：')[1],'予備 '+eq[i][2].split('：')[1]+' / '+eq[i][3].split('：')[1],'equip',[i]))+section('セット中',HB(skillSet[i].join(' · ')||'スキル未設定','Cost '+skillCost(i)+' / '+skillCap(i),'skills',[i]))+section('育成',ha(HB('能力',statPt[i]+' Pt','charAbility',[i]),HB('Mastery',mp[i]+' Pt','mastery',[i])))+HB('隊列を変更',rows[i],'toggleRow',[i]))},
 charOverview(i){return character(i)},
 charAbility(i){if(H.run?.battle)return pendingBattleMenu();const a=stats[i],d=rules().derived(a),armor=ARM[eq[i][4].split('：')[1]]||[0,'',0,0];show('<h2>'+names[i]+'</h2>'+actorTabs(i,'ability')+'<div class="section-meta"><b>能力値</b><span>残り '+statPt[i]+' Pt</span></div><div class="stats-grid">'+attrs.map((k,j)=>'<div><span>'+k+'</span><b>'+a[j]+'</b><button class="stat-plus"'+data('addStat',[i,j])+(statPt[i]<=0?' disabled':'')+' aria-label="'+k+'を1上げる">＋</button></div>').join('')+'</div>'+resources(i)+'<div class="stat-summary"><span>物防 <b>'+(a[0]+armor[2])+'</b></span><span>魔防 <b>'+(a[2]+a[3]+armor[3])+'</b></span><span>重量上限 <b>'+a[0]+'</b></span></div>'+HB('属性・状態耐性','','resistView',[i])+'<p class="small">＋を押すと1 Pt消費して能力値を1上げます。</p>')},
 resistView(i){const r=calcResist(i);show('<h2>'+names[i]+' / 耐性</h2>'+section('属性','<div class="resist-grid">'+['斬','突','壊','火','水','風','土','光','闇'].map(k=>'<span>'+k+' <b>'+(r[k]?r[k]+'%':'—')+'</b></span>').join('')+'</div>')+section('状態異常・封じ','<div class="resist-grid">'+Object.keys(r).filter(k=>!['斬','突','壊','火','水','風','土','光','闇'].includes(k)).map(k=>'<span>'+k+' <b>'+(r[k]?r[k]+'%':'—')+'</b></span>').join('')+'</div>')+'<p class="small">— は追加耐性なし。</p>')},
 equip(i){if(H.run?.battle)return pendingBattleMenu();const w=weightInfo(i);const buttons=ks=>ks.map(k=>HB(({0:'主武器',1:'副手',2:'主武器',3:'副手',4:'防具一式',8:'装飾',9:'携行具'})[k],eq[i][k].split('：')[1],'equipChoice',[i,k])).join('');show('<h2>'+names[i]+'</h2>'+actorTabs(i,'equip')+'<div class="section-meta"><b>'+stanceInfo(i).name+'</b>'+pill('重量 '+w.weight+'/'+w.limit,w.level?'warning':'')+'</div>'+(w.level?'<p class="inline-warning">'+hesc(w.text)+'</p>':'')+section('現在のセット','<div class="two-columns">'+buttons([0,1])+'</div>')+section('予備セット','<div class="two-columns">'+buttons([2,3])+'</div>')+'<button class="swap-set"'+data('swapMain',[i])+'>⇄ 主副セットを換装</button>'+buttons([4,8,9]))},
 equipChoice(i,k){if(H.run?.battle)return pendingBattleMenu();const list=k<4?['なし',...inventory.weapons]:k===4?inventory.armor:k===9?['なし',...Object.keys(hc().tools).filter(n=>hc().tools[n].battle)]:['なし','護符'];const now=eq[i][k].split('：')[1],base=weightInfo(i);show('<h2>'+names[i]+' / '+({0:'主武器',1:'副手',2:'予備主武器',3:'予備副手',4:'防具一式',8:'装飾',9:'携行具'})[k]+'</h2><p class="small">現在：'+hesc(now)+'</p>'+list.map(n=>{const m=WM[n],w=candidateWeight(i,k,n),ok=canEquip(i,k,n);let reason='';if(!ok){const j={PHY:0,SKL:1,ARC:2,MND:3}[m?.[3]];reason=m&&j!=null&&stats[i][j]<m[4]?m[3]+' '+stats[i][j]+' → 必要 '+m[4]:(k===1||k===3)?isTwoHanded(n)?'両手武器は副手に装備不可':isTwoHanded(eq[i][k-1].split('：')[1])?'主武器が両手武器':'二刀流にはSKL 30が必要':'装備条件不足'}const detail=reason||((m?m[0]+' · '+m[1]+' / ':'')+(k===2||k===3?'予備重量 '+(m?.[2]||0)+'（待機中は対象外）':'重量 '+base.weight+' → '+w.weight+'/'+w.limit)+(k===9?' / 所持 '+(inventory.tools[n]||0):''));return '<div class="candidate '+(n===now?'selected':'')+'">'+HB(n+(n===now?'　装備中':''),detail,'setEquip',[i,k,n],!ok)+'</div>'}).join(''))},
 skills(i,filter){if(H.run?.battle)return pendingBattleMenu();if(filter!==undefined)U.filters[i]=filter;filter=U.filters[i]||'All';const query=U.search[i]||'',chosen=skillSet[i],ns=learned[i].filter(n=>rules().meta(n)&&(filter==='All'||filter==='set'?filter!=='set'||chosen.includes(n):rules().meta(n).mode===filter)).sort((a,b)=>Number(chosen.includes(b))-Number(chosen.includes(a)));show('<h2>'+names[i]+'</h2>'+actorTabs(i,'skills')+'<div class="cost-meter"><b>Cost '+skillCost(i)+' / '+skillCap(i)+'</b><i><i style="width:'+Math.min(100,skillCost(i)/skillCap(i)*100)+'%"></i></i></div>'+tabs([['All','すべて'],['set','セット中'],['Active','技・術'],['Passive','パッシブ']],filter,'skills',[i])+'<input id="skillSearch" class="search-input" type="search" placeholder="スキルを検索" value="'+hesc(query)+'" aria-label="スキル検索" oninput="uiSearchSkills(this.value)">'+(ns.length?ns.map(n=>{const d=rules().meta(n),on=chosen.includes(n),usable=skillUsable(i,n),next=on?chosen.filter(x=>x!==n):chosen.concat(n),fits=rules().fits(stats[i],next);return '<div data-skill-name="'+hesc(n)+'"><button class="row skill-toggle '+(on?'selected':'')+'"'+data('toggleLearnedSkill',[i,n])+' aria-pressed="'+on+'"'+(!fits?' disabled':'')+'><b>'+hesc(n)+'<span class="cost-label">'+effectiveCost(i,n)+'</span></b><span class="small">'+hesc(d.mode==='Passive'?d.description:skillDescription(d)+(d.costType?' · '+d.costType+' '+d.cost:''))+'</span>'+(!fits?'<span class="inline-warning">変更後のCost上限を超えます</span>':!usable?'<span class="small equipment-needed">現在の装備では使用不可</span>':'')+'</button></div>'}).join(''):HT('該当するスキルはありません'))+'<p id="skillEmpty" class="empty-message" hidden>一致するスキルはありません。</p>');filterSkillRows(query)},
 filterSkillRows(text){let count=0;document.querySelectorAll('[data-skill-name]').forEach(e=>{e.hidden=!e.dataset.skillName.toLowerCase().includes(text.toLowerCase());if(!e.hidden)count++});const m=document.getElementById('skillEmpty');if(m)m.hidden=count>0},
 mastery(i){if(H.run?.battle)return pendingBattleMenu();show('<h2>'+names[i]+'</h2>'+actorTabs(i,'mastery')+'<div class="section-meta"><b>Mastery</b><span>'+mp[i]+' Pt</span></div>'+Object.entries(ranksFor(i)).filter(([,v])=>v>0).map(([g,v])=>HB(g,v+'/50','growMastery',[i,g])).join('')+section('系統を探す','<div class="category-grid">'+['武器','防具','源泉','術法','技能'].map(t=>HB(t,'','masteryType',[i,t])).join('')+'</div>')+'<details class="ui-help"><summary>育成の仕組み</summary><p class="small">1 PtでRank＋5。スキル習得は別途1 Pt。源泉は1系統、術法・技能は各2系統まで。</p></details>')},
 charMastery(i){return mastery(i)},
 readiness(){if(H.run?.battle)return pendingBattleMenu();const ws=warnings();show('<h2>準備確認</h2>'+(ws.length?noticeList():HT('準備完了','前列3人・後列3人'))+HB('隊列を調整','','squadMenu')+(activeRun()?HB('探索へ戻る','','resumeExpedition'):HB('出撃確認へ',H.selected||dungeonId,'deployment',[H.selected||dungeonId])))},
 items(){return itemCategory(U.inventory)},
 itemCategory(t='道具'){U.inventory=t;let body='';if(t==='道具')body=Object.entries(hc().tools).filter(([n])=>inventory.tools[n]>0).map(([n,d])=>HB(n+' ×'+inventory.tools[n],d.desc,d.field?'useTool':'uiCarryUsers',[n])).join('');else if(t==='素材')body=Object.entries(loot).filter(([,q])=>q>0).map(([n,q])=>HT((hc().labels[n]||n)+' ×'+q,n==='古器'?'ギルドで査定':'')).join('');else if(t==='記録')body=Object.keys(H.clues).map(n=>HT(n)).join('');else body=inventory.weapons.slice().sort((a,b)=>Number(H.favorites.includes(b))-Number(H.favorites.includes(a))).map(n=>HB((H.favorites.includes(n)?'★ ':'')+n,'+'+(upgrades[n]||0)+' / '+(traits[n]||'特性なし'),'gearDetail',[n])).join('');show('<h2>所持品</h2>'+tabs([['道具','道具'],['装備','武具'],['素材','素材'],['記録','重要品']],t,'uiInventory')+(body||HT('まだ所持していません'))+(!activeRun()?section('管理',ha(HB('保管庫','','storageMenu'),HB('売却','','sellMenu'))):''))},
 inn(){if(!requireTown())return;show('<h2>宿・酒場</h2>'+(H.history.length?HB('帰還後の食卓',lastExpedition.dungeon+' / '+lastExpedition.result,'returnTalk'):'')+HB('仲間の会話','','conversation')+HB('街の人々','','npcMenu')+HB('仲間同士の会話','','pairMenu')+HB('噂と手掛かり','','rumors'))},
 questMenu(filter='active'){const counts={open:hc().quests.filter(q=>qstate(q).state===0&&syncQuestAvailability().some(a=>a.id===q.id)).length,active:hc().quests.filter(q=>[1,2].includes(qstate(q).state)).length,ready:hc().quests.filter(q=>qstate(q).state===2).length,done:hc().quests.filter(q=>qstate(q).state===3).length};const list=hc().quests.filter(q=>filter==='all'||(filter==='active'?[1,2].includes(qstate(q).state):qstate(q).state===({open:0,ready:2,done:3}[filter]??1)));show('<h2>依頼掲示板</h2>'+tabs([['open','未受注'],['active','進行中 '+counts.active],['ready','報告 '+counts.ready],['done','完了']],filter,'questMenu')+(activeRun()?'<p class="small">探索中は進捗のみ確認できます。</p>':'')+(list.length?list.map(q=>{const st=qstate(q),available=syncQuestAvailability().some(a=>a.id===q.id);return HB((H.tracked===q.id?'★ ':'')+q.n,q.d+' · '+(st.state===0?available?'受注可能':'未開放':st.state===2?'報告待ち':st.state===3?'報告済み':st.progress+'/'+q.target),'questSelect',[q.id])}).join(''):HT('該当する依頼はありません'))+(!activeRun()&&counts.ready?HB('達成分を一括報告',counts.ready+'件','reportAll'):'')+(H.tracked?HB('追跡を解除','','uiClearTrack'):'')+HB('全件を見る','','questMenu',['all']))},
 questSelect(id){const q=findQuest(id);if(!q)return;const st=qstate(q),available=syncQuestAvailability().some(a=>a.id===q.id),prereq=q.prereq?findQuest(q.prereq):null;show('<h2>'+hesc(q.n)+'</h2>'+pill(q.d)+'<p class="message">'+hesc(q.description)+'</p>'+HT('進捗 '+st.progress+'/'+q.target,'報酬 '+moneyText(q.reward)+' · Stat '+q.stat+' / Mastery '+q.mastery+' Pt')+(activeRun()?(st.state===1?HB(H.tracked===q.id?'追跡中':'追跡する','','trackQuest',[q.id],H.tracked===q.id):''):st.state===0?HB('受注する',available?'':!unlocked.includes(q.d)?'地域未開放':prereq?'前提：'+prereq.n+'を報告':'前提条件未達成','acceptQuest',[q.id],!available):st.state===2?HB('達成報告','','claimQuest',[q.id]):st.state===3?HT('報告済み'):HB('この地域の出撃準備','','deployment',[q.d]))+(st.state===1&&!activeRun()?HB(H.tracked===q.id?'追跡中':'追跡する','','trackQuest',[q.id],H.tracked===q.id)+'<details class="ui-help"><summary>依頼の管理</summary>'+HB('取り下げる','進捗はリセットされます','askAbandonQuest',[q.id])+'</details>':''))},
 deployment(id){if(activeRun())return expeditionMenu();if(!hc().regions[id]||!unlocked.includes(id))return note('この地域は未開放です');dungeonId=id;H.selected=id;const r=hc().regions[id],q=hc().quests.filter(q=>q.d===id&&[1,2].includes(qstate(q).state));show('<h2>'+id+' / 出撃準備</h2>'+pill('全3層')+' '+pill('前列3・後列3')+'<p class="small">'+hesc(r.mechanism)+' · '+hesc(r.item)+'</p>'+section('編成',names.map((n,i)=>'<div class="deploy-member"><button'+data('character',[i])+'><b>'+n+'</b><small>'+rows[i]+' · '+hesc(eq[i][0].split('：')[1])+'</small></button><span>HP '+vitals[i].hp+'/'+rules().derived(stats[i]).hp+'</span></div>').join(''))+(warnings().length?HB('準備を確認',warnings().length+'件','readiness'):'')+section('受注中',q.length?q.map(q=>HB(q.n,qstate(q).progress+'/'+q.target,'questSelect',[q.id])).join(''):HB('この地域の依頼を探す','','questMenu',['open']))+'<details class="ui-help"><summary>地域の詳細</summary><p class="message">'+hesc(r.intro)+'</p></details><div class="sticky-action"><button class="primary-action" data-hub="startDungeon">6人で出撃 →</button></div>')},
 settings(){show('<h2>設定</h2>'+section('表示・操作',HB('文字サイズ',H.settings.text,'cycleText')+HB('重要操作の確認',H.settings.confirm?'ON':'OFF','toggleConfirm'))+section('セーブ',HT(hubSaveError?'保存に失敗しています':'自動保存',hubSaveError||'操作ごとに保存')+HB('今すぐ保存','','manualSave')+HB('書き出す','JSONファイル','exportSave')+HB('読み込む','確認後に置き換え','chooseImport'))+'<details class="ui-help danger-zone"><summary>データ管理</summary>'+HB('バックアップ復元','','askRestore',[],!RPG_STORE.getItem(HUB_BACKUP))+HB('最初から始める','進行を初期化','resetSave')+'</details>')},
 manualSave(){toast(saveGame()?'保存しました':'保存できません。書き出しを利用してください。');renderSaveStatus()},
 drawDungeon(){old.drawDungeon();navState('town');const root=document.querySelector('.expedition');if(!root)return;const q=activeQuest();if(q){const e=document.createElement('button');e.className='field-quest';e.setAttribute('data-hub','questSelect');e.dataset.args=JSON.stringify([q.id]);e.textContent='★ '+q.n+' '+qstate(q).progress+'/'+q.target;root.querySelector('.field-head').after(e)}const head=root.querySelector('.field-head');if(head){const help=document.createElement('button');help.className='icon-button';help.setAttribute('data-hub','uiMapLegend');help.setAttribute('aria-label','地図の見方');help.textContent='?';head.append(help)}const generic=root.querySelector('.field-actions .row.static .small');if(generic)generic.remove()}
};
Object.assign(window,views);
window.HUB_UI_ACTIONS=Object.keys(uiActions);
// Safe render-only history. Returning re-renders from current state, never replays purchases or rewards.
const routes=['storyMenu','readStory','reportChapter','epilogue','guild','questMenu','questSelect','inn','returnTalk','conversation','memberTalk','npcMenu','npcTalk','pairMenu','readPair','talkArchive','rumors','infoMenu','dungeonIntel','market','toolShop','toolQuantity','weaponShop','gearDetail','armorShop','craftMenu','recipeMenu','recipeDetail','upgradeMenu','traitMenu','traitChoice','appraiseMenu','rareAppraise','sellMenu','materialTrade','materialQuantity','storageMenu','depositMenu','merchantNode','dungeonForge','items','itemCategory','records','historyMenu','historyDetail','regionRecords','regionRecord','enemyBook','enemyRecord','peopleBook','recordList','partyMenu','readiness','equip','equipChoice','skills','presetMenu','askSavePreset','settings','character','charOverview','charAbility','resistView','charMastery','mastery','masteryType','growMastery','masterySkills','squadMenu','rowSwapMenu','dungeon','deployment','camp','moraleMenu','expeditionMenu','runJournal','battlePrep','mechanismMenu','eventChoice','explorationNode','stairsMenu','secretNode','pendingBattleMenu','note','checkpointResult','uiCarryUsers','uiMapLegend'];
for(const name of routes){const render=window[name];if(typeof render!=='function')continue;window[name]=(...args)=>{const previous=U.render;U.render={name,args};try{return render(...args)}finally{U.render=previous}}}
// Modal focus, keyboard escape and touch navigation work independently of game state.
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!isOpen())return;const list=focusables(),first=list[0],last=list[list.length-1];if(!first)return;e.stopPropagation();if(e.shiftKey&&(document.activeElement===first||!list.includes(document.activeElement))){last.focus();e.preventDefault()}else if(!e.shiftKey&&(document.activeElement===last||!list.includes(document.activeElement))){first.focus();e.preventDefault()}});
document.addEventListener('click',e=>{if(e.target.closest('#app nav')){U.stack=[];U.route=null}const el=e.target.closest('[data-hub],button[onclick]');if(!el)return;if(el.closest('#app'))U.launcher=el;if(el.closest('#panel')&&!el.disabled){U.opener=U.opener?.isConnected?U.opener:document.querySelector('#app nav .current')}},true);
window.HUB_UI={version:8,state:U,warnings,resources};
})();
