/* Preparation and save tools live entirely on the hub side. */
var pendingHubImport=null;
function partyMenu(){if(H.run?.battle)return pendingBattleMenu();show('<h2>編成・準備</h2>'+HB('隊列・準備診断','前列3人 / 後列3人','readiness')+HB('編成プリセット','装備・スキル・隊列を3組保存','presetMenu')+names.map((n,i)=>HB(n+' / '+rows[i],battleStyle(i)+' / Cost '+skillCost(i)+'/'+skillCap(i),'character',[i])).join('')+back())}
function readiness(){const notices=[];if(rows.filter(r=>r==='前列').length!==3)notices.push('前列・後列を3人ずつにしてください');names.forEach((n,i)=>{if(vitals[i].hp<=0)notices.push(n+'：戦闘不能');if(!skillFits(i))notices.push(n+'：Cost超過');if(weightInfo(i).level>0)notices.push(n+'：重量超過（装備は可能）');if(!skillSet[i].length)notices.push(n+'：セットスキルなし');const carry=eq[i][9].split('：')[1];if(carry!=='なし'&&!(inventory.tools[carry]>0))notices.push(n+'：携行具の残数なし')});show('<h2>準備診断</h2>'+HT(notices.length?'確認 '+notices.length+'件':'準備完了',notices.join('\n')||'6人の装備・スキル・隊列を確認しました。')+HB('隊列編成','','squadMenu')+names.map((n,i)=>HB(n,eq[i][0]+' / '+eq[i][2],'character',[i])).join('')+ha(HB('探索中の地点へ','','resumeExpedition',[],!activeRun()),HB('編成へ','','partyMenu')))}
function stanceInfo(i){const m=eq[i][0].split('：')[1],o=eq[i][1].split('：')[1],name=m==='なし'&&o==='なし'?'無手':isTwoHanded(m)?'両手武器':o==='なし'?'片手武器・副手なし':o.includes('盾')?'武器＋盾':'二刀流';return {name,effect:name==='二刀流'?'セットCost 4を使用。副武器の攻撃力を加算。':name==='片手武器・副手なし'?'両手持ち：重量軽減・威力と命中上昇。通常攻撃で物理防御を崩す。':'主副セットを手動で換装。予備武器も装備重量に含まれます。'}}
function equip(i){const w=weightInfo(i);show('<h2>'+hesc(names[i])+' / 装備</h2>'+HT(stanceInfo(i).name,'重量 '+w.weight+'/'+w.limit+' / '+w.text)+[0,1,2,3,4,8,9].map(k=>HB(k===4?'防具一式：'+eq[i][4].split('：')[1]:eq[i][k],'候補を比較','equipChoice',[i,k])).join('')+HB('主副セット ⇄ 予備セット','主武器と副手を同時に交換','swapMain',[i])+ha(HB('キャラクターへ','','character',[i])))}
function weaponMasteryFor(n){return n==='呪符'?'符術':weaponKind(n)}
function weaponMasteryReady(i,n){return n==='なし'||(ranksFor(i)[weaponMasteryFor(n)]||0)>0}
function canEquip(i,k,n){if(!Number.isInteger(i)||i<0||i>=6||![0,1,2,3,4,8,9].includes(k))return false;if(k<4){if(n==='なし')return true;if(!inventory.weapons.includes(n)||!WM[n]||!weaponMasteryReady(i,n))return false;const m=WM[n],j={PHY:0,SKL:1,ARC:2,MND:3}[m[3]];if(m[3]!=='―'&&stats[i][j]<m[4])return false;if((k===1||k===3)&&(isTwoHanded(n)||isTwoHanded(eq[i][k-1].split('：')[1])||(!n.includes('盾')&&stats[i][1]<30)))return false;return true}if(k===4)return n==='なし'||inventory.armor.includes(n)&&!!ARM[n]&&(ranksFor(i)[armorFamily(n)]||0)>0;if(k===8)return ['なし','護符'].includes(n);return n==='なし'||!!hc().tools[n]?.battle}
function candidateWeight(i,k,n){const old=eq[i].slice();const label=old[k].split('：')[0];eq[i][k]=label+'：'+n;if(k===4)for(let z=5;z<=7;z++)eq[i][z]=old[z].split('：')[0]+'：'+n;if((k===0||k===2)&&isTwoHanded(n))eq[i][k+1]=old[k+1].split('：')[0]+'：なし';const w=weightInfo(i);eq[i]=old;return w}
function equipmentSnapshot(i){
 const a=stats[i],d=rules().derived(a),armor=ARM[eq[i][4].split('：')[1]]||[0,'',0,0],w=weightInfo(i),main=eq[i][0].split('：')[1],weapon=WM[main],set=skillSet[i].filter(n=>rules().meta(n)?.mode==='Active'),usable=set.filter(n=>skillUsable(i,n)).length;
 return {hp:d.hp,sp:d.sp,pdef:a[0]+(armor[2]||0),mdef:a[2]+a[3]+(armor[3]||0),weight:w.weight,limit:w.limit,weightLevel:w.level,weightText:w.text,attack:weapon?weapon[0]+'・'+weapon[1]:'壊・近',usable,setCount:set.length,stance:stanceInfo(i).name};
}
function candidateEquipmentSnapshot(i,k,n){
 const old=eq[i].slice(),label=old[k].split('：')[0];
 eq[i][k]=label+'：'+n;
 if(k===4)for(let z=5;z<=7;z++)eq[i][z]=old[z].split('：')[0]+'：'+n;
 if((k===0||k===2)&&isTwoHanded(n))eq[i][k+1]=old[k+1].split('：')[0]+'：なし';
 const out=equipmentSnapshot(i);eq[i]=old;return out;
}
function equipmentCompareText(i,k,n){
 const a=equipmentSnapshot(i),b=candidateEquipmentSnapshot(i,k,n),parts=[];
 if(a.pdef!==b.pdef)parts.push('物防 '+a.pdef+'→'+b.pdef);
 if(a.mdef!==b.mdef)parts.push('魔防 '+a.mdef+'→'+b.mdef);
 if(a.weight!==b.weight)parts.push('重量 '+a.weight+'→'+b.weight);
 if(a.attack!==b.attack)parts.push('攻撃 '+a.attack+'→'+b.attack);
 if(a.stance!==b.stance)parts.push('構え '+a.stance+'→'+b.stance);
 if(a.usable!==b.usable)parts.push('使用可能技 '+a.usable+'/'+a.setCount+'→'+b.usable+'/'+b.setCount);
 return parts.join(' / ')||'主要戦闘値は変わりません';
}
function equipmentComparePanel(i,k,n){
 const a=equipmentSnapshot(i),b=candidateEquipmentSnapshot(i,k,n),now=eq[i][k].split('：')[1],slots={0:'主武器',1:'副手',2:'予備主武器',3:'予備副手',4:'防具一式',8:'装飾',9:'携行具'};
 const metric=(label,x,y,dir=1,sx=x,sy=y)=>{const cls=sx===sy?'same':((sy-sx)*dir>0?'up':'down');return '<span class="'+cls+'"><small>'+label+'</small><b>'+x+'</b><i>›</i><b>'+y+'</b></span>'};
 const profile=k<4?'<div class="equip-profile"><small>属性・射程</small><b>'+hesc(WM[now]?.[0]||'—')+'・'+hesc(WM[now]?.[1]||'—')+'</b><i>›</i><b>'+hesc(WM[n]?.[0]||'—')+'・'+hesc(WM[n]?.[1]||'—')+'</b></div>':'';
 const stance=a.stance!==b.stance?'<div class="equip-profile"><small>構え</small><b>'+hesc(a.stance)+'</b><i>›</i><b>'+hesc(b.stance)+'</b></div>':'';
 const unchanged=a.pdef===b.pdef&&a.mdef===b.mdef&&a.weight===b.weight&&a.attack===b.attack&&a.usable===b.usable&&a.stance===b.stance;
 const note=unchanged?'<p class="equip-nochange">'+(k===2||k===3?'予備装備のため、換装するまでは現在の戦闘値に反映されません。':'主要戦闘値の変化はありません。')+'</p>':'';
 return '<section class="equip-compare" aria-live="polite"><div class="equip-compare-head"><div><small>選択中 · '+hesc(slots[k]||'装備')+'</small><b>'+hesc(n)+'</b></div><span>現在 → 装備後</span></div><div class="equip-change-items"><b>'+hesc(now)+'</b><i>→</i><b>'+hesc(n)+'</b></div><div class="equip-compare-grid">'+metric('物防',a.pdef,b.pdef)+metric('魔防',a.mdef,b.mdef)+metric('重量',a.weight,b.weight,-1)+metric('使用可能技',a.usable+'/'+a.setCount,b.usable+'/'+b.setCount,1,a.usable,b.usable)+'</div>'+profile+stance+note+(b.weightLevel?'<p class="inline-warning">'+hesc(b.weightText)+'</p>':a.weightLevel&&!b.weightLevel?'<p class="equip-improved">重量超過が解消されます。</p>':'')+'</section>';
}
function equipChoice(i,k){if(H.run?.battle)return pendingBattleMenu();const list=k<4?['なし',...inventory.weapons]:k===4?inventory.armor:k===9?['なし',...Object.keys(hc().tools).filter(n=>hc().tools[n].battle)]:['なし','護符'];const current=eq[i][k].split('：')[1];show('<h2>'+hesc(names[i])+' / 装備候補</h2>'+HT('現在：'+current,'装備後の重量を表示。要求不足のものは選べません。')+list.map(n=>{const m=WM[n],w=candidateWeight(i,k,n);return HB((n===current?'✓ ':'')+n,(m?m[0]+' / '+m[1]+' / '+m[3]+' '+m[4]+' / ':'')+'装備後 '+w.weight+'/'+w.limit+(k===9?' / 所持 '+(inventory.tools[n]||0):''),'setEquip',[i,k,n],!canEquip(i,k,n))}).join('')+ha(HB('戻る','','equip',[i])))}
function setEquip(i,k,n){if(H.run?.battle||!canEquip(i,k,n))return;const label=eq[i][k].split('：')[0];eq[i][k]=label+'：'+n;if(k===4)for(let z=5;z<=7;z++)eq[i][z]=eq[i][z].split('：')[0]+'：'+n;if((k===0||k===2)&&isTwoHanded(n))eq[i][k+1]=eq[i][k+1].split('：')[0]+'：なし';persist();equip(i)}
function swapMain(i){if(H.run?.battle)return;const labels=['主武器','副手','予備主','予備副'],v=eq[i].slice(0,4).map(x=>x.split('：')[1]);eq[i][0]=labels[0]+'：'+v[2];eq[i][1]=labels[1]+'：'+v[3];eq[i][2]=labels[2]+'：'+v[0];eq[i][3]=labels[3]+'：'+v[1];persist();equip(i)}
function skills(i,filter='All'){const ns=learned[i].filter(n=>rules().meta(n)&&(filter==='All'||rules().meta(n).mode===filter));show('<h2>'+hesc(names[i])+' / スキル</h2>'+HT('Cost '+skillCost(i)+' / '+skillCap(i),'アクティブ・パッシブ共通。セット中のみ有効。')+ha(HB('すべて','','skills',[i]),HB('技・術','','skills',[i,'Active']),HB('パッシブ','','skills',[i,'Passive']))+'<input class="search-input" type="search" placeholder="スキル名で絞り込み" aria-label="スキル検索" oninput="filterSkillRows(this.value)">'+ns.map(n=>{const d=rules().meta(n);return '<div data-skill-name="'+hesc(n)+'">'+HB((skillSet[i].includes(n)?'✓ ':'○ ')+n,'Cost '+effectiveCost(i,n)+' / '+skillDescription(d)+(d.costType?' / '+d.costType+' '+d.cost:''),'toggleLearnedSkill',[i,n])+'</div>'}).join('')+ha(HB('習得・育成','','mastery',[i]),HB('戻る','','character',[i])))}
function filterSkillRows(text){document.querySelectorAll('[data-skill-name]').forEach(e=>e.hidden=!e.dataset.skillName.includes(text))}
function presetMenu(){show('<h2>編成プリセット</h2><p class="sortie-instruction">陣形・装備・スキルを３組まで保存できます。</p><div class="sortie-presets">'+H.presets.map((p,i)=>'<section class="sortie-preset"><div><small>SET '+(i+1)+'</small><b>'+hesc(p?.name||'未登録')+'</b></div><div class="sortie-preset-actions"><button'+` data-hub="askSavePreset" data-args="[${i}]"`+'>保存</button><button'+` data-hub="applyPreset" data-args="[${i}]"`+(!p?' disabled':'')+'>呼び出す</button></div></section>').join('')+'</div>'+back())}
function askSavePreset(i){if(![0,1,2].includes(i)||H.run?.battle)return;show('<h2>セット '+(i+1)+'を保存</h2><input id="presetName" class="search-input" maxlength="30" value="'+hesc(H.presets[i]?.name||'編成 '+(i+1))+'" aria-label="プリセット名">'+HT('保存内容','3×3陣形・装備・予備セット・スキル。能力値や習得状況は変更しません。')+ha(HB('保存','','savePreset',[i]),HB('戻る','','presetMenu')))}
function savePreset(i){if(![0,1,2].includes(i)||H.run?.battle)return;ensureFormation();H.presets[i]={name:(document.getElementById('presetName')?.value||'編成 '+(i+1)).slice(0,30),eq:cp(eq),rows:cp(rows),formation:cp(H.formation),skills:cp(skillSet)};persist();presetMenu()}
function applyPreset(i){if(H.run?.battle)return;const p=H.presets[i];if(!p)return;const missing=[];p.eq.forEach((a,j)=>{if(!Array.isArray(a)||a.length!==10){missing.push(names[j]+'の装備');return}const saved=eq[j];eq[j]=a;try{for(const k of [0,1,2,3,4,8,9]){const n=a[k].split('：')[1];if(!canEquip(j,k,n))missing.push(names[j]+'：'+n)}}finally{eq[j]=saved}if(!skillFits(j,p.skills[j],a)||p.skills[j].some(n=>!learned[j].includes(n)))missing.push(names[j]+'のスキル')});if(missing.length)return note('呼び出せません：'+[...new Set(missing)].join(' / '));eq=cp(p.eq);rows=cp(p.rows);skillSet=cp(p.skills);H.formation=validFormation(p.formation)?cp(p.formation):formationFromRows();syncFormationRows();persist();partyMenu()}
function settings(){show('<h2>設定・セーブ</h2>'+HT(hubSaveError?'保存に注意が必要です':'自動保存',hubSaveError||'操作ごとに保存します。探索中の地点・報酬待ちも再開できます。')+HB('手動セーブ','','manualSave')+HB('文字サイズ',H.settings.text,'cycleText')+HB('重要操作の確認',H.settings.confirm?'ON':'OFF','toggleConfirm')+HB('セーブを書き出す','JSONファイルとして手元に保存','exportSave')+HB('セーブを読み込む','現在のデータは確認後に置き換え','chooseImport')+HB('前のバックアップを復元','読込前のデータを保持しています','askRestore',[],!RPG_STORE.getItem(HUB_BACKUP))+HB('最初から始める','現在の進行を初期化','resetSave')+back())}
function manualSave(){note(saveGame()?'セーブしました。':'保存できません。書き出しを利用してください。')}
function cycleText(){const a=['標準','大','小'];H.settings.text=a[(a.indexOf(H.settings.text)+1)%3];applyHubSettings();persist();settings()}
function toggleCompact(){H.settings.density=H.settings.density==='コンパクト'?'標準':'コンパクト';applyHubSettings();persist();settings()}
function toggleConfirm(){H.settings.confirm=!H.settings.confirm;ui.confirm=H.settings.confirm;persist();settings()}
function exportSave(){const raw=JSON.stringify(collectSave(),null,2),blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rpg-save-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function chooseImport(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(file.size>2500000)return note('ファイルが大きすぎます');try{previewImport(await file.text())}catch(e){note('読み込めません：'+e.message)}};input.click()}
function previewImport(raw){try{const d=JSON.parse(raw);validateSave(d);pendingHubImport=d;show('<h2>セーブを読み込みますか？</h2>'+HT('確認',moneyText(d.gold)+' / 能力値合計 '+d.stats[0].reduce((s,v)=>s+v,0))+'<p class="message">現在のデータはバックアップしてから置き換えます。</p>'+ha(HB('やめる','','cancelImport'),HB('読み込む','','confirmImport')))}catch(e){pendingHubImport=null;note('読み込めません：'+e.message)}}
function cancelImport(){pendingHubImport=null;settings()}
function confirmImport(){if(!pendingHubImport)return;const d=pendingHubImport;pendingHubImport=null;RPG_STORE.setItem(HUB_BACKUP,JSON.stringify(collectSave()));try{for(const[k,v]of Object.entries(HUB_DEFAULTS))window[k]=cp(v);installSave(d);RPG_STORE.removeItem('rpg.exploreBattle');if(H.run?.battle){H.run.battle=null;H.run.phase='choice'}persist();closeM();activeRun()?resumeExpedition():town()}catch(e){note('読込に失敗しました。バックアップから復元してください：'+e.message)}}
function askRestore(){confirmAction('バックアップを復元','現在の進行を、前回読み込む前のセーブで置き換えます。','restoreBackup')}
function restoreBackup(){const raw=RPG_STORE.getItem(HUB_BACKUP);if(raw)previewImport(raw)}
function resetSave(){confirmAction('最初から始める','探索・所持品・育成・物語を初期化します。現在のデータはバックアップへ退避します。','resetSaveConfirmed')}
function resetSaveConfirmed(){RPG_STORE.setItem(HUB_BACKUP,JSON.stringify(collectSave()));for(const[k,v]of Object.entries(HUB_DEFAULTS))window[k]=cp(v);window.masteryRanks=null;window.legacySkills=null;RPG_STORE.removeItem('rpg.exploreBattle');installSave(null);persist();town()}
function hubBootstrap(){rebuildSkillWeaponMap();loadGame();if(RPG_STORE.isExplorationDemo&&!activeRun()){ensureFormation();H.run=makeRun('古代迷宮',['森林','洞窟','廃墟都市']);H.totalRuns++;H.story.intro=true;logRun('出撃：古代迷宮');syncRun()}hubBooted=true;const allowed=new Set(window.HUB_ACTION_NAMES||[]);document.addEventListener('click',e=>{const el=e.target.closest('[data-hub]');if(!el||el.disabled)return;const fn=el.dataset.hub;if(!allowed.has(fn)||typeof window[fn]!=='function')return;e.preventDefault();try{const args=JSON.parse(el.dataset.args||'[]');if(!Array.isArray(args)||args.length>8)return;window[fn](...args)}catch(err){console.error(err);note('操作を完了できませんでした。セーブを書き出して再読込してください。')}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeM()});document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeM()});const r=H.run;if(!resumeBattle()){if(r){drawDungeon();if(r.pending!=null)resumeNode()}else town()}persist();window.addEventListener('pagehide',()=>saveGame());document.body.dataset.hubVersion='7'}
function squadMenu(){return partyMenu()}
function weaponKind(n){if(!n||n==='なし')return 'なし';for(const[k,re]of [['格闘',/拳甲|格闘/],['槌',/槌/],['斧',/斧/],['短剣',/短剣/],['剣',/剣/],['槍',/槍/],['弓',/弓/],['杖',/杖/],['盾',/盾/],['投擲',/回刃|投/],['鞭',/鞭/],['鎌',/鎌/],['刀',/刀/],['銃',/銃/]])if(re.test(n))return k;return n}
function mainMastery(i){const highest=Object.entries(ranksFor(i)).sort((a,b)=>b[1]-a[1])[0];return highest?highest[0]+' '+highest[1]+'/50':'未取得'}
function charOverview(i){const v=vitals[i],max=rules().derived(stats[i]);show('<h2>'+hesc(names[i])+' / 概要</h2>'+HT(battleStyle(i)+' / '+rows[i],eq[i][0]+' ⇄ '+eq[i][2])+HT('資源','HP '+v.hp+'/'+max.hp+' / SP '+v.sp+'/'+max.sp)+HT('主力Mastery',mainMastery(i))+HT('セット中のスキル',skillSet[i].join(' / ')||'なし')+HT('残っている状態',Object.entries(v.status||{}).filter(([,n])=>n>0).map(([k,v])=>({poison:'猛毒',blind:'盲目',sleep:'睡眠',agitate:'動揺'}[k]||k)+' '+v+'ターン').join(' / ')||'なし')+ha(HB('戻る','','character',[i])))}
