function rulebook(){return window.RPG_RULES}
function copy(x){return JSON.parse(JSON.stringify(x))}
function passive(u,key){const defs=rulebook().skills;return (u.masteries||[]).reduce((v,n)=>{const d=defs[n];return v+(d?.mode==='Passive'&&!weaponSkillReason(u,d)?d.passive?.[key]||0:0)},0)}
function actorSide(u){return u.enemy?enemies:party}
function opponentSide(u){return u.enemy?party:enemies}
function equippedKind(u){return activeWeaponKinds(u)}
function setCommand(u,q){if(!editable()||!u?.alive||u.hp<=0)return false;if(u.casting&&q.type!=='cast')cancelCasting(u);u.queued=q;u.defending=q.type==='defend';getDraft(u).partId=q.partId||null;return true}
function activeWeaponKinds(u){return new Set([battleWeaponKind(u.weapon?.name),battleWeaponKind(u.currentOffhand)])}
function weaponSkillReason(u,a){if(u.enemy)return '';const req=a.weapons||rulebook().skills[a.name]?.weapons;if(!req?.length)return '';const kinds=activeWeaponKinds(u);if(req.includes('格闘')&&((u.weapon?.name==='無手'&&(u.currentOffhand||'なし')==='なし')||kinds.has('格闘')))return '';if(req.includes('投擲')&&throwAction(u))return '';return req.some(x=>kinds.has(x))?'':'対応装備：'+req.join(' / ')}
function weaponByName(n){const aliases={'王国剣':'sword','長槍':'spear','短杖':'staff','拳甲':'fist','古戦槌':'hammer','風裂弓':'bow','星紋杖':'staff','遺跡短剣':'dagger','呪符':'talisman'};if(!n||n==='なし')return {name:'無手',attr:'壊',range:'near',power:0,hit:0,speed:10,load:0,weight:'light'};const k=aliases[n.replace('・異品','')]||Object.keys(W).find(k=>W[k].name===n)||({'槌':'hammer','斧':'axe','短剣':'dagger','剣':'sword','槍':'spear','鞭':'whip','鎌':'scythe','刀':'katana','弓':'bow','銃':'gun','杖':'staff','盾':'shield','格闘':'fist','投擲':'chakram'}[battleWeaponKind(n)]);return k?{...W[k],name:n}:null}
function battleLoad(u){const eq=u.handSets,meta=EXPCTX?.gearMeta||{},a=ARM[u.armor]||{w:0};let armor=eq?[4,5,6,7].reduce((v,k)=>v+({魔装:2,軽装:3,重装:8}[eq[k]?.split('：')[1]]||0),0):a.w*4;const weight=n=>meta[n]?.[2]??weaponByName(n)?.load??0;const load=eq?[0,1,2,3].reduce((v,k)=>v+weight(eq[k].split('：')[1]),0):(u.weapon?.load||0);return (load+armor+(eq?.[8]?.endsWith('：なし')?0:1))*(1-Math.min(.4,passive(u,'loadReduction')))}
function updateEncumbrance(u){const weight=Math.max(0,Math.round(battleLoad(u)*100)/100),limit=Math.max(1,u.PHY),ratio=weight/limit;u.encumbrance={weight,limit,ratio,level:ratio<=1?0:ratio<=1.2?1:ratio<=1.5?2:3};return u.encumbrance}
function applyHandSet(u){if(!u.handSets)return;const main=u.handSets[u.wi?2:0].split('：')[1],off=u.handSets[u.wi?3:1].split('：')[1];u.weapon=weaponByName(main)||weaponByName('なし');u.currentOffhand=off;u.shieldGuard=/盾/.test(off)?.1:0;u.dualWield=off!=='なし'&&!/盾/.test(off);u.weaponBonus=EXPCTX?.upgrades?.[main]||0;u.weaponTrait=EXPCTX?.traits?.[main]||'';updateEncumbrance(u)}
function normal(u){return {name:'通常攻撃',kind:'attack',range:u.weapon?.range||'near',attr:u.weapon?.attr||'壊',target:'enemy',scope:'single',stat:'PHY',mult:1,body:['arms'],hit:0,speed:0}}
function throwAction(u){const tool={投げナイフ:{attr:'斬',power:12},鉄針:{attr:'突',power:9},投石:{attr:'壊',power:10}}[u.carry];return tool?{name:'投擲：'+u.carry,kind:'throw',target:'enemy',scope:'single',range:'far',stat:'SKL',mult:1,body:['arms'],speed:10,itemCost:u.carry,...tool}:null}
function actionFor(u,key=getDraft(u).key){return key==='throw'?throwAction(u)||normal(u):key==='attack'?normal(u):u.skills[Number(key)]||normal(u)}
function actionCost(u,a){return a.costType?Math.max(a.cost>0?1:0,(a.cost||0)-(a.costType==='MP'?Math.min(5,passive(u,'mpDiscount')):0)):0}
function enough(u,a){return !a.costType||u[a.costType.toLowerCase()]>=actionCost(u,a)}
function blocked(u,a){if(u.status.headBind>0&&a.body?.includes('head'))return '頭封じ';if(u.status.armBind>0&&a.body?.includes('arms'))return '腕封じ';if(u.status.legBind>0&&a.body?.includes('legs'))return '脚封じ';if(a.partKey&&u.parts?.[a.partKey]?.hp<=0)return '部位破壊';return weaponSkillReason(u,a)}
function unavailable(u,a){if(u.status.sleep>0)return '睡眠';if(u.status.stun>0)return '気絶';const r=blocked(u,a);if(r)return r;if(a.once&&u.usedSkills?.[a.name])return 'この戦闘では使用済み';if(a.itemCost&&(carryRemaining[a.itemCost]||0)<=0)return a.itemCost+'不足';if(!enough(u,a))return a.costType+'不足';if(!targets(u,a).length)return '射程内に対象なし';return ''}
function targets(u,a){const side=a.target==='ally'||a.target==='self'?actorSide(u):opponentSide(u);if(a.target==='self')return u.alive?[u]:[];if(a.revive)return side.filter(x=>!x.alive);return live(side).filter(t=>a.target==='ally'||canReach(u,t,a.range))}
function affectedTargets(u,t,a){if(a.revive||a.target==='self')return [t];const ls=live(actorSide(t)),sc=a.scope||'single';if(sc==='all')return ls;if(sc==='row')return ls.filter(x=>x.row===t.row);if(sc==='adjacent')return ls.filter(x=>x.row===t.row&&Math.abs(col(x)-col(t))<=1);if(sc==='pierce')return ls.filter(x=>col(x)===col(t));if(sc==='random'){const pool=ls.slice(),out=[];while(pool.length&&out.length<(a.randomCount||3))out.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);return out}return [t]}
function simpleCommand(type){if(!editable())return;const u=current();if(type==='swap')return openSwapSheet();if(type==='escape'&&(u.status.legBind>0||EXPCTX?.boss||EXPCTX?.noEscape))return notify('逃走できません');if(setCommand(u,{type}))advance()}
function queue(){if(!editable())return;const u=current(),a=actionFor(u),reason=unavailable(u,a);if(reason)return notify(reason);const d=getDraft(u);if(setCommand(u,{type:a.kind==='attack'?'attack':'skill',action:copy(a),targetId:d.targetId,partId:d.partId||null}))advance()}
function cancelCasting(u){if(!u?.casting)return;u.casting=null;if(u.queued?.type==='cast')u.queued=null;u.defending=false}
function freeColumn(row,side=party){const max=side===enemies?Math.max(3,...side.filter(x=>x.row===row).map(col)):3,used=new Set(live(side).filter(x=>x.row===row).flatMap(x=>Array.from({length:x.span||1},(_,i)=>col(x)+i)));for(let i=1;i<=max;i++)if(!used.has(i))return i;return null}
function rowChange(){if(!editable())return;const u=current();if(u.status.legBind>0)return notify('脚封じで移動できません');if(!freeColumn(u.row==='front'?'back':'front',party))return openSwapSheet();if(setCommand(u,{type:'row'}))advance()}
function openSwapSheet(){if(!editable())return;const u=current();if(u.status.legBind>0)return notify('脚封じで移動できません');$('sheetKicker').textContent=u.name;$('sheetTitle').textContent='交代相手';const list=$('sheetList');list.replaceChildren();for(const m of live(party).filter(x=>x.row!==u.row)){const b=document.createElement('button');b.className='member-option';b.textContent=m.name+' / 相手の行動は消費しない';b.disabled=m.status.legBind>0;b.onclick=()=>{if(setCommand(u,{type:'swap',swapId:m.id})){closeSheet();advance()}};list.append(b)}sheet.showModal()}
async function moveTo(u,row,token,allowSwap=true){if(u.row===row||u.span>1)return false;const side=actorSide(u),fc=freeColumn(row,side);if(fc){u.row=row;u.slot=fc+(row==='back'?3:0);render();return true}const other=live(side).find(x=>x.row===row&&col(x)===col(u)&&x.span<=1&&x.status.legBind<=0);if(allowSwap&&other){await animateSwap(u,other,u.name+'と'+other.name+'の位置が入れ替わった。',token);return true}return false}
function setTimed(u,key,value,turns=3,source=key){u.timed=u.timed||{};const id=key+':'+source,old=u.timed[id];u.timed[id]={key,value:old&&Math.abs(old.value)>Math.abs(value)?old.value:value,turns,appliedRound:round}}
function buff(u,key){return clamp(Object.values(u.timed||{}).filter(x=>x.key===key).reduce((v,x)=>v+x.value,0),-.4,.4)}
function tickTimed(u){for(const k of Object.keys(u.timed||{})){if(--u.timed[k].turns<=0)delete u.timed[k]}}
function terrainEvadeMod(u){return /泥濘|悪路/.test(terrain.name)?-10:/岩場|瓦礫/.test(terrain.name)?-5:0}
function hit(a,t,act){const magical=act.kind==='spell',acc=a.SKL+(magical?0:(a.weapon?.hit||0))+(act.hit||0)+terrainHitMod(a,act)+(magical||act.ignoreCover?0:terrain.wHit?.(a.weapon)||0)-(a.status.blind>0?30:0),pen=[0,5,15,30][t.encumbrance?.level||0],ev=t.status.legBind>0?0:(t.SKL+passive(t,'evade')+terrainEvadeMod(t)-pen)*(1+buff(t,'evade'));return clamp(90+(acc-ev)*.5,30,100)}
function speed(u,q){if(u.status.legBind>0)return -100000;const a=q?.action||normal(u),pen=[0,5,15,30][u.encumbrance?.level||0],p=q?.type==='carry'?10+passive(u,'itemSpeed'):a.kind==='spell'?passive(u,'castSpeed'):u.weapon?.speed||0;return u.SKL*(1+buff(u,'speed'))+p+(a.speed||0)+(u.tempSpeed||0)+terrainSpeedMod(u)+(a.kind==='spell'?0:terrain.wSpeed?.(u.weapon)||0)-pen+(round===1?passive(u,'openingSpeed'):0)}
function typeAffinity(t,a){if(!t.enemy)return 1;const s=t.style||'';if(/重装|ゴーレム|機械/.test(s))return a==='壊'?2:a==='斬'?.5:1;if(/飛行/.test(s))return a==='突'?2:a==='壊'?.5:1;if(/獣/.test(s))return a==='斬'?2:1;if(/亡者|死霊/.test(s))return a==='壊'?2:a==='突'?.5:1;return 1}
function affinity(t,attr){const attrs=Array.isArray(attr)?attr:String(attr||'無').split(/[+＋/]/),norm=x=>x===0?0:x>1?2:x<1?.5:1;return attrs.reduce((sum,x)=>sum+norm(t.weak?.[x]??t.resist?.[x]??typeAffinity(t,x)),0)/attrs.length}
function attackValue(u,a){let v;if(a.kind==='throw')v=(a.power||0)+u.SKL;else if(a.kind==='attack')v=(u.weapon?.power||0)+(u.weapon?.throwing?u.SKL:u.weapon?.skillNormal?u.PHY*.4+u.SKL*.7:u.PHY);else{const stat=a.scale?Object.entries(a.scale).reduce((v,[k,x])=>v+(u[k]||0)*x,0):u[a.stat]||u.PHY;v=(a.kind==='spell'?a.power??14:u.weapon?.power||0)+stat}if(a.kind!=='spell')v*=[1,.95,.9,.8][u.encumbrance?.level||0];return v*(1+buff(u,'attack'))*(u.status.agitate>0?.85:1)}
function repeatMult(){return 1}
function damage(u,t,a){const magic=a.kind==='spell',def=(magic?t.magDef:t.physDef)*(1+buff(t,'defense'))*(t.status.agitate>0?.85:1)*(1-(a.defPierce||0)),aff=affinity(t,a.attr),chance=clamp(5+(u.SKL-t.SKL)/4+(u.weapon?.crit||0)+(a.critBonus||0)+passive(u,'crit'),0,50),crit=Math.random()*100<chance;let mul=1;const at=Array.isArray(a.attr)?a.attr:[a.attr];if(/水辺|浅瀬/.test(terrain.name)){if(at.includes('火'))mul*=.85;if(at.includes('水'))mul*=1.15}if(terrain.arcaneAttr&&at.includes(terrain.arcaneAttr))mul*=1.18;if(a.range==='far'&&!magic&&(/開所|広場/.test(terrain.name)||terrain.name==='高台'&&u.row==='back'))mul*=1.1;if(/結界地/.test(terrain.name)&&magic)mul*=.85;if(aff>1)mul*=1+passive(u,'weakBonus')+buff(u,'weak');if(magic)mul*=1+passive(u,'spellBoost');if(a.kind==='throw'||a.weapons?.includes('投擲'))mul*=1+passive(u,'throwBoost');if(a.flyingBonus&&/飛行/.test(t.style))mul*=1+a.flyingBonus;if(t.enemy&&/重装|機械|ゴーレム/.test(t.style))mul*=1+passive(u,'armoredBonus');if(t.hp/t.maxHp<=.3)mul*=1+(a.executeBonus||0)+passive(u,'executeBonus');if(round===1)mul*=1+passive(u,'openingBonus');if(u.weaponBonus&&a.kind!=='spell')mul*=1+u.weaponBonus*.04;if(t.status.sleep>0)mul*=1.5;mul*=1-Math.min(.4,passive(t,'reduction'));mul*=1-Math.max(0,buff(t,'guard'));if(t.defending)mul*=Math.max(.3,.5-(t.shieldGuard||0)-passive(t,'guard'));const rguard=live(actorSide(t)).reduce((v,g)=>g.row===t.row?Math.max(v,passive(g,'rowGuard')):v,0);mul*=1-Math.min(.3,rguard);if(t.exploreResist)mul*=1-Math.min(.4,at.reduce((v,k)=>v+(t.exploreResist[k]||0),0)/at.length/100);const value=Math.floor(attackValue(u,a)*(a.mult??1)*100/(100+Math.max(0,def))*aff*(crit?1.5:1)*mul*(.95+Math.random()*.1));return {value:aff===0?0:Math.max(1,value),crit,weak:aff>1,aff}}
function statusStat(a,act,k){return a[act.statusStat||((act.kind==='spell')?act.stat:k==='stun'?'PHY':'SKL')]||a.SKL}
function statusResist(t,k){const fixed=t.statusResist?.[k];if(fixed==='immune')return Infinity;return (fixed||0)+(t.style==='BOSS'?(k==='instantDeath'?100:25):t.elite?25:0)+(t.statusBuildup?.[k]||0)+passive(t,'statusResist')+(k==='stun'?passive(t,'stunResist'):0)}
async function applyStatuses(u,t,a,token){if(!t.alive||t.hp<=0)return;for(const [k,label,duration] of [['poison','猛毒',3],['blind','盲目',3],['sleep','睡眠',2],['agitate','動揺',3],['stun','気絶',1],['headBind','頭封じ',2],['armBind','腕封じ',2],['legBind','脚封じ',2],['instantDeath','即死',0]]){if(!a[k])continue;const res=statusResist(t,k);if(!Number.isFinite(res)){observeStatus(t,k,'無効');continue}const st=statusStat(u,a,k),cap=k==='instantDeath'?(t.style==='BOSS'?5:t.elite?10:35):95,p=clamp(a[k]+.75*(st-t.MND)+passive(u,'statusBonus')+buff(u,'status')*100-res,5,cap),ok=Math.random()*100<p;t.statusBuildup[k]=(t.statusBuildup[k]||0)+(ok?(t.style==='BOSS'?50:35):10);observeStatus(t,k,ok?'成功':'失敗');if(!ok)continue;if(k==='instantDeath'){t.hp=0;await defeated(t,token);return}t.status[k]=Math.max(t.status[k]||0,t.style==='BOSS'?Math.max(1,duration-1):duration);t.statusHold[k]=k!=='poison'&&t.actedRound===round;if(k==='poison')t.statusPower.poison=st;if(k==='legBind')t.comboSetup={kind:'bound',by:u.id,expires:round+2};await say(t.name+'に'+label+'！',token,'sys');if((k==='stun'||k==='headBind')&&t.casting){cancelCasting(t);await say(t.name+'の詠唱が中断された。',token,'sys')}}}
function observeStatus(t,k,outcome){if(!t.enemy)return;t.observed=t.observed||{attributes:{},statuses:{}};t.observed.statuses[k]=outcome}
function observeDamage(t,a,d){if(!t.enemy)return;t.observed=t.observed||{attributes:{},statuses:{}};for(const x of (Array.isArray(a.attr)?a.attr:[a.attr]))t.observed.attributes[x]=affinity(t,x);if(d.weak)discoveredWeakness.add(enemyBaseName(t.name)+'：'+(Array.isArray(a.attr)?a.attr.join('＋'):a.attr))}
function forceMoveChance(u,t,a){const st=u[a.stat]||u.PHY,sz={small:-10,normal:0,large:20,huge:40}[t.size||'normal'];return clamp((a.moveChance||70)+st-t.PHY-sz-passive(t,'moveResist')+(terrain.cliffBonus?10:0),5,95)}
async function breakCasting(t,dmg,token){if(!t.casting)return;const block=t.status.headBind>0||t.status.stun>0,chance=block?100:dmg>=t.maxHp*.25?Math.max(0,60-passive(t,'castStability')):0;if(Math.random()*100<chance){cancelCasting(t);await say(t.name+'の詠唱が妨害された。',token,'sys')}}
function partDefinitions(name){const defs={迷宮守護機:[['arms','駆動腕',.3,'壊','大薙ぎ停止'],['core','術式核',.22,'闇','全体術停止'],['legs','脚部',.22,'突','行動速度低下']],辺境の巨獣:[['arms','大角',.3,'突','突進停止'],['core','喉',.22,'斬','咆哮停止'],['legs','後肢',.22,'壊','行動速度低下']],深淵樹母:[['arms','大蔓',.28,'斬','蔓薙ぎ停止'],['core','花冠',.24,'火','瘴気術停止'],['legs','根',.24,'壊','行動速度低下']],黄金王墓の番人:[['arms','王笏',.28,'壊','王撃停止'],['core','冠',.24,'闇','審判術停止'],['legs','脚甲',.22,'突','行動速度低下']]};return defs[name]||defs.迷宮守護機}
function makeParts(u){return Object.fromEntries(partDefinitions(u.name).map(([id,name,p,attr,effect])=>[id,{id,name,maxHp:Math.floor(u.maxHp*p),hp:Math.floor(u.maxHp*p),weak:{[attr]:2},effect}]))}
async function damagePart(u,id,value,token){const p=u.parts?.[id];if(!p||p.hp<=0)return;p.hp=Math.max(0,p.hp-value);if(p.hp===0){if(id==='legs'){u.tempSpeed=(u.tempSpeed||0)-12;u.size='large';u.span=1}u.partBreaks=(u.partBreaks||0)+1;await say(p.name+'を破壊！ '+p.effect,token,'ok');if(u.casting?.action.partKey===id)cancelCasting(u)}}
async function comboBefore(u,t,a,token){let bonus=1;const setup=t.comboSetup;if(setup&&setup.by!==u.id&&setup.expires>=round){if(a.comboBonus){bonus+=a.comboBonus;t.comboSetup=null;}if(setup.kind==='pulled'&&a.push){bonus=1.3;t.comboSetup=null;await say('連携：引寄せ → 吹飛ばし',token,'ok')}else if(setup.kind==='bound'&&a.range==='far'&&['突','斬'].includes(a.attr)){bonus=1.2;t.comboSetup=null;await say('連携：脚封じ → 精密攻撃',token,'ok')}}if(t.fireMark&&t.fireMark.by!==u.id&&t.fireMark.expires>=round&&(Array.isArray(a.attr)?a.attr:[a.attr]).includes('風')){bonus*=1.25;t.fireMark=null;await say('連携：火 → 風で炎上拡大',token,'ok')}return bonus}
async function followup(u,t,token){const source=live(actorSide(u)).find(x=>x.id!==u.id&&x.interrupts<1&&Object.values(x.timed||{}).some(b=>b.key==='follow')&&x.status.stun<=0&&x.status.sleep<=0&&!blocked(x,normal(x))&&canReach(x,t,x.weapon.range));if(!source||!t.alive)return;source.interrupts++;const d=damage(source,t,{...normal(source),mult:.45});t.hp=Math.max(0,t.hp-d.value);await say(source.name+'の追撃号令！ '+d.value,token,'ok');await defeated(t,token)}
async function reaction(t,u,a,token){if(!t.alive||!u.alive||t.interrupts>=1||!passive(t,'counter')||t.status.stun>0||t.status.sleep>0||blocked(t,normal(t))||!canReach(t,u,t.weapon.range))return;t.interrupts++;const d=damage(t,u,{...normal(t),mult:.65*(1+passive(t,'counterBonus'))});u.hp=Math.max(0,u.hp-d.value);await say(t.name+'の反撃！ '+d.value,token,t.enemy?'bad':'ok');await defeated(u,token)}
async function interceptHit(u,a,token){if(a.target!=='enemy'||a.range==='far'||a.kind==='spell')return false;const g=live(opponentSide(u)).find(x=>x.interrupts<1&&passive(x,'intercept')&&x.status.stun<=0&&x.status.sleep<=0&&!blocked(x,normal(x))&&canReach(x,u,x.weapon.range));if(!g)return false;g.interrupts++;const d=damage(g,u,{...normal(g),mult:.5});u.hp=Math.max(0,u.hp-d.value);await say(g.name+'の迎撃！ '+d.value,token,'sys');await defeated(u,token);return !u.alive}
function protectedTarget(t,a){if(a.scope!=='single'||a.target!=='enemy')return t;const g=live(actorSide(t)).find(x=>x.id!==t.id&&x.interrupts<1&&passive(x,'cover')&&x.status.sleep<=0&&x.status.stun<=0&&x.status.armBind<=0&&(x.row===t.row||x.row==='front'));if(g){g.interrupts++;return g}return t}
async function defeated(u,token){if(u.hp>0||!u.alive)return;if(passive(u,'survive')&&!u.survived){u.survived=true;u.hp=1;await say(u.name+'は踏ん張った！',token,'sys');return}u.hp=0;u.alive=false;cancelCasting(u);u.defending=false;await say(u.name+'は戦闘不能。',token,'sys');render()}
function spendAction(u,a){if(a.costType)u[a.costType.toLowerCase()]-=actionCost(u,a);if(a.itemCost)recordCarryUse(a.itemCost);if(a.once){u.usedSkills=u.usedSkills||{};u.usedSkills[a.name]=true}if(a.bloodCost)u.hp=Math.max(1,u.hp-Math.ceil(u.maxHp*a.bloodCost))}
async function execute(u,q,token){check(token);if(!q||!u.alive||u.hp<=0)return;u.actedRound=round;if(u.status.stun>0||u.status.sleep>0||q.type==='skip'){if(q.type==='cast')cancelCasting(u);await say(u.name+'は行動できない。',token,'sys');return}if(q.type==='defend'||q.type==='row'||q.type==='swap')return;if(q.type==='escape'){if(u.status.legBind>0||EXPCTX?.boss||EXPCTX?.noEscape){await say(u.name+'は逃走できない。',token,'sys');return}if(Math.random()*100<escapeChance())await finish('escape',token);else await say(u.name+'の逃走は失敗。',token,'sys');return}
 if(q.type==='carry'){await executeItem(u,q,token);return}
 let a=q.type==='attack'?normal(u):q.action;const completing=q.type==='cast';if(completing){if(!u.casting)return;a=u.casting.action;u.casting=null}if(!a)return;const r=blocked(u,a);if(r){await say(u.name+'は'+r+'で行動できない。',token,'sys');return}if(!completing&&(!enough(u,a)||a.once&&u.usedSkills?.[a.name]||a.itemCost&&(carryRemaining[a.itemCost]||0)<=0)){await say(u.name+'は資源不足・使用済み。',token,'sys');return}
 if(a.kind!=='attack'&&a.kind!=='throw'&&u.status.agitate>0&&Math.random()<.2){if(!completing)spendAction(u,a);await say(u.name+'は動揺で発動に失敗。',token,'sys');return}
 if(!completing&&a.cast){spendAction(u,a);u.casting={action:copy(a),targetId:q.targetId,partId:q.partId,ready:round+1};await say(u.name+'は'+a.name+'の詠唱開始。',token,'sys');return}
 let ts=targets(u,a),t=ts.find(x=>x.id===q.targetId)||ts[0];if(!t){await say(u.name+'の行動は対象・射程を失った。',token,'sys');return}if(!completing)spendAction(u,a);if(await interceptHit(u,a,token))return;
 await say(u.name+'：'+a.name,token,'',{actorId:u.id},false);
 if(a.summon){summons=summons.filter(x=>x.owner!==u.id);summons.push({owner:u.id,name:a.name,type:a.summon,power:u[a.stat]||u.ARC,turns:3,enemy:u.enemy});await say(a.name+'が出現（3ラウンド）。',token,'ok');return}
 const affected=affectedTargets(u,t,a);if(a.reposition){const done=new Set();for(const z of affected){if(done.has(z.id)||z.status.legBind>0)continue;const side=actorSide(z),dest=z.row==='front'?'back':'front',pair=live(side).find(x=>x.row===dest&&col(x)===col(z));if(pair)done.add(pair.id);done.add(z.id);await moveTo(z,dest,token)}return}
 for(let z of affected){if(a.revive){if(!z.alive){z.alive=true;z.hp=Math.max(1,Math.floor(z.maxHp*.25));z.status={};await say(z.name+'を蘇生。',token,'ok')}continue}
  if(a.target==='ally'||a.target==='self'){if(a.heal){const ranks={small:[8,.5],standard:[12,.8],large:[20,1.2]},k=ranks[a.heal]||ranks.standard,n=Math.min(z.maxHp-z.hp,Math.floor((k[0]+u.MND*k[1])*(1+passive(u,'healBoost'))));z.hp+=n;await say(z.name+'のHP +'+n,token,'ok')}
   if(a.cleanse){z.status={};z.statusPower={};z.statusHold={}}
   if(a.buff)setTimed(z,a.buff,a.magnitude,3,a.name);
   if(a.barrier)setTimed(z,'guard',a.barrier,3,a.name);
   if(a.bless){setTimed(z,'guard',.12,3,a.name);setTimed(z,'status',.1,3,a.name)}
   if(a.regen)setTimed(z,'regen',a.regen,3,a.name);
   if(a.followOrder)setTimed(z,'follow',1,3,a.name);
   if(a.guardAction){u.defending=true;setTimed(u,'guard',.1,1,a.name)}
   if(a.taunt)setTimed(u,'taunt',1,3,a.name);
   if(a.alchemy){z.hp=Math.min(z.maxHp,z.hp+25);z.sp=Math.min(z.maxSp,z.sp+12);z.mp=Math.min(z.maxMp,z.mp+8)}
   if(a.resourceRecovery)for(const [key,val] of Object.entries(a.resourceRecovery))z[key]=Math.min(z['max'+key[0].toUpperCase()+key.slice(1)],z[key]+val);
   continue}
  if(!z.alive)continue;const covered=protectedTarget(z,a);if(covered!==z){await say(covered.name+'が'+z.name+'を庇う。',token,'sys');z=covered}
  if(Math.random()*100>=hit(u,z,a)){await say(z.name+'は回避。',token,'sys');continue}
  const cb=await comboBefore(u,z,a,token);const totalHits=a.hits||1;let sum=0,weak=false;
  for(let i=0;i<totalHits&&z.alive&&u.alive;i++){const selected=z===t&&['single','pierce'].includes(a.scope||'single')?q.partId:null,p=z.parts?.[selected],target=p&&p.hp>0?{...z,weak:{...z.weak,...p.weak}}:z;const d=a.mult===0?{value:0,weak:false,crit:false,aff:affinity(target,a.attr)}:damage(u,target,{...a,mult:a.mult*cb/totalHits});sum+=d.value;weak=weak||d.weak;z.hp=Math.max(0,z.hp-d.value);if(!u.enemy)observeDamage(z,a,d);if(d.value>0){if(z.status.sleep>0)z.status.sleep=0;await damagePart(z,selected,d.value,token);await say(z.name+'に '+d.value+(d.weak?' WEAK':'')+(d.crit?' CRITICAL':''),token,u.enemy?'bad':'ok',{targetId:z.id,value:d.value});await breakCasting(z,d.value,token)}await defeated(z,token)}
  if(a.drain&&sum)u.hp=Math.min(u.maxHp,u.hp+Math.floor(sum*a.drain));
  if(z.alive){await applyStatuses(u,z,a,token);if(a.debuff)setTimed(z,a.debuff,a.magnitude,3,a.name);if((a.push||a.pull)&&Math.random()*100<forceMoveChance(u,z,a)){const moved=await moveTo(z,a.push?'back':'front',token);if(moved&&a.pull)z.comboSetup={kind:'pulled',by:u.id,expires:round+2}}
   if((Array.isArray(a.attr)?a.attr:[a.attr]).includes('火')&&sum>0)z.fireMark={by:u.id,expires:round+2};
   if(weak){if(passive(u,'weakRecovery')&&u.weakTriggerRound!==round){u.weakTriggerRound=round;u.sp=Math.min(u.maxSp,u.sp+3)}await followup(u,z,token)}
   if(sum>0)await reaction(z,u,a,token)}
 }
 render()
}
function recordCarryUse(x){carryRemaining[x]=Math.max(0,(carryRemaining[x]||0)-1);if(EXPCTX){EXPCTX.usedCarry=EXPCTX.usedCarry||{};EXPCTX.usedCarry[x]=(EXPCTX.usedCarry[x]||0)+1;localStorage.setItem('rpg.exploreBattle',JSON.stringify(EXPCTX))}}
async function executeItem(u,q,token){const x=q.item;if((carryRemaining[x]||0)<=0){await say(x+'が不足。',token,'sys');return}const target=party.find(t=>t.id===q.targetId&&t.alive)||u;if(x==='回復薬'&&target.hp===target.maxHp||x==='解毒薬'&&!target.status.poison){await say('使用が必要な対象なし。',token,'sys');return}recordCarryUse(x);if(x==='回復薬')target.hp=Math.min(target.maxHp,target.hp+Math.floor(target.maxHp*.35));if(x==='薬瓶'){target.hp=Math.min(target.maxHp,target.hp+25);target.sp=Math.min(target.maxSp,target.sp+12)}if(x==='解毒薬'){target.status.poison=0;target.statusPower.poison=0}if(x==='煙玉'){for(const e of live(enemies))await applyStatuses(u,e,{blind:75,stat:'SKL'},token)}if(x==='爆弾'){const t=enemies.find(e=>e.id===q.targetId&&e.alive)||live(enemies)[0];if(t){const d=damage(u,t,{kind:'throw',power:20,stat:'SKL',attr:'火',mult:1,range:'far',scope:'single',target:'enemy'});t.hp=Math.max(0,t.hp-d.value);await say(t.name+'に爆弾 '+d.value,token,'ok');await defeated(t,token)}}await say(u.name+'が'+x+'を使用。',token,'ok')}
function useCarry(){if(!editable())return;const u=current(),x=u.carry;if(throwAction(u)){getDraft(u).key='throw';render();return}if((carryRemaining[x]||0)<=0)return notify('携行具がありません');const side=x==='爆弾'?live(enemies):x==='煙玉'?[u]:live(party);$('sheetTitle').textContent=x+' / 対象';$('sheetKicker').textContent='道具・1行動';$('sheetList').replaceChildren();for(const t of side){const b=document.createElement('button');b.className='member-option';b.textContent=t.name+'　HP '+t.hp+'/'+t.maxHp;b.onclick=()=>{if(setCommand(u,{type:'carry',item:x,targetId:t.id})){closeSheet();advance()}};$('sheetList').append(b)}sheet.showModal()}
async function switchWeapon(){if(!editable())return;const u=current();if(u.status.armBind>0)return notify('腕封じで換装できません');u.wi=u.wi?0:1;if(u.handSets)applyHandSet(u);else{u.weapon={...(W[u.weapons[u.wi]]||weaponByName('なし'))};updateEncumbrance(u)}if(['attack','skill','carry'].includes(u.queued?.type)){u.queued=null;u.defending=false}if(passive(u,'swapReaction')&&u.interrupts<1){u.interrupts++;setTimed(u,'evade',.1,1,'換装反応')}getDraft(u).key='attack';phase='command';render()}
function importSkill(n,u){const d=rulebook().meta(n);if(!d||d.mode!=='Active')return null;const a=copy(d);if(u&&a.kind==='spell'&&passive(u,'spellRange'))a.range={near:'mid',mid:'far'}[a.range]||a.range;return a}
function applyMasteryPassive(u,i){const selected=EXPCTX?.skillSet?.[i]??u.skills.map(s=>s.name);u.masteries=[...new Set(u.masteries||selected)].filter(n=>rulebook().meta(n));u.masteryOwned=EXPCTX?.masteryOwned?.[i]||{};u.physDef=u.PHY+(ARM[u.armor]?.p||0);u.magDef=u.ARC+u.MND+(ARM[u.armor]?.m||0);u.physDef+=passive(u,'physicalDef');u.magDef+=passive(u,'magicDef');u.mpOnceAvailable=passive(u,'mpOnce')>0}
function applyExploreContext(){const ctx=EXPCTX;if(!ctx){carryRemaining={回復薬:6,解毒薬:3,爆弾:2,煙玉:2,薬瓶:2,投げナイフ:10,鉄針:10,投石:10};for(const [i,u] of party.entries()){u.carry=i===1?'投げナイフ':'回復薬';u.masteries=u.skills.map(s=>s.name);u.skills=u.skills.map(s=>importSkill(s.name,u)).filter(Boolean);applyMasteryPassive(u,i);updateEncumbrance(u)}return}carryRemaining={...ctx.carryInventory};for(const [i,u] of party.entries()){const a=ctx.stats?.[i]||[u.PHY,u.SKL,u.ARC,u.MND];[u.PHY,u.SKL,u.ARC,u.MND]=a;const d=rulebook().derived(a),v=ctx.vitals?.[i]||d;u.maxHp=d.hp;u.maxSp=d.sp;u.maxMp=d.mp;u.hp=clamp(Number(v.hp)||0,0,d.hp);u.sp=clamp(Number(v.sp)||0,0,d.sp);u.mp=clamp(Number(v.mp)||0,0,d.mp);u.alive=u.hp>0;u.status={...u.status,...copy(v.status||{})};u.statusPower=copy(v.statusPower||{});u.armor={魔装:'magic',軽装:'light',重装:'heavy'}[ctx.armor?.[i]]||u.armor;u.row=ctx.rows?.[i]==='前列'?'front':'back';u.handSets=ctx.equipment?.[i]?copy(ctx.equipment[i]):null;u.carry=ctx.carrySet?.[i]||'';let set=Array.isArray(ctx.skillSet?.[i])?ctx.skillSet[i]:u.skills.map(s=>s.name);set=[...new Set(set)].filter(n=>rulebook().meta(n));while(set.length&&!rulebook().fits(a,set))set.pop();u.masteries=set;u.skills=set.map(n=>importSkill(n,u)).filter(Boolean);applyHandSet(u);applyMasteryPassive(u,i);u.masteries=set;u.exploreResist=ctx.resist?.[i]||{};updateEncumbrance(u)}let fc=0,bc=0;for(const u of party)u.slot=u.row==='front'?++fc:3+(++bc);if(fc>3||bc>3)party.forEach((u,i)=>{u.row=i<3?'front':'back';u.slot=i+1});const spec=TERRAINS.find(t=>t.name===ctx.terrain)||TERRAINS.find(t=>t.name==='開所');terrain={...spec};configureEncounter();applyDungeonGimmick();uMorale=ctx.morale||'なし';for(const u of party){if(uMorale==='歌唱')setTimed(u,'regen',.04,3,'野営歌');if(uMorale==='舞踏'){setTimed(u,'speed',.1,3,'野営舞');setTimed(u,'evade',.1,3,'野営舞')}if(uMorale==='奏楽')u.sp=Math.min(u.maxSp,u.sp+4);if(uMorale==='号令')setTimed(u,'attack',.1,3,'野営号令');if(ctx.runBuff==='看破')setTimed(u,'weak',.15,1,'看破の印')}if(ctx.runBuff==='先制')for(const u of party)setTimed(u,'speed',.15,1,'先制の印');if(ctx.runBuff==='守護')for(const u of party)setTimed(u,'guard',.1,1,'守護の印')}
function configureEncounter(){if(!EXPCTX)return;if(EXPCTX.boss){const name={古代迷宮:'迷宮守護機',辺境遺跡:'辺境の巨獣',深淵の樹海:'深淵樹母',沈黙の砂都:'黄金王墓の番人'}[EXPCTX.dungeonId]||'迷宮守護機',u=initUnit({id:'boss',name,style:'BOSS',row:'front',slot:1,hp:1280,PHY:70,SKL:42,ARC:52,MND:52,physDef:92,magDef:84,weak:{壊:2},resist:{斬:.5},size:'huge',weapon:{name:'固有攻撃',attr:'壊',range:'mid',power:24,hit:0,speed:-5},skills:[]},true);u.span=3;u.parts=makeParts(u);enemies=[u];PORTRAITS.boss='enemy_guard';return}const front=EXPCTX.enemyFront||['重装','獣'],back=EXPCTX.enemyBack||['魔術師'],all=front.concat(back);enemies=all.map((tag,i)=>{const magic=/魔術師|呪術師|神官|精霊|死霊/.test(tag),ranged=/弓|飛行/.test(tag),seed=ET.find(e=>magic?e.id==='mage':ranged?e.id==='arch':e.id==='g1'),src=copy(seed);src.id='enc'+i;src.name=tag+' '+(i+1);src.style=tag;src.row=i<front.length?'front':'back';src.slot=i<front.length?i+1:4+i-front.length;src.weak={};src.resist={};src.hp=magic?100:ranged?110:/ゴーレム|重装/.test(tag)?170:135;src.hp+=Math.max(0,(EXPCTX.threat||1)-1)*10;src.weapon=magic?{name:'術杖',power:8,range:'near',attr:'壊',hit:0,speed:0}:ranged?{name:'射撃',power:16,range:'far',attr:'突',hit:5,speed:5}:src.weapon;src.size='normal';src.span=1;const u=initUnit(src,true);u.statusResist=/亡者|死霊/.test(tag)?{poison:50,sleep:50}:{};u.observed={attributes:{},statuses:{}};PORTRAITS[u.id]=magic?'enemy_mage':ranged?'enemy_archer':'enemy_guard';return u});if(EXPCTX.battleType==='elite'&&enemies[0]){const u=enemies[0];u.elite=true;u.size='large';u.hp=u.maxHp=Math.floor(u.maxHp*1.75);u.PHY+=10;u.physDef+=8}}
function makeBossTelegraph(u){const phase=u.hp/u.maxHp<=.4?3:u.hp/u.maxHp<=.7?2:1;if(u.bossPhase!==phase){u.bossPhase=phase;if(phase===3){terrain.extraDesc='ボス第3段階：崩れる足場';terrain.bossRubble=true}}let a;if(round%3===0&&u.parts.core.hp>0){a={...importSkill('爆炎',u),name:'術式解放',attr:/樹母/.test(u.name)?'土':'光',cast:0,cost:0,scope:'all',mult:.8,partKey:'core',body:['head']}}else if(u.parts.arms.hp>0){a={...normal(u),name:'大薙ぎ',kind:'skill',scope:round%2===0?'row':'single',mult:phase===3?1.7:1.25,partKey:'arms',body:['arms'],speed:-10}}else{a={...normal(u),name:'体当たり',scope:'single',mult:.85,body:['legs']}}a.targetRow=a.scope==='row'?'front':null;a.telegraphText=a.name+' / '+(a.scope==='all'?'全体':a.scope==='row'?'前列':'単体')+(a.partKey?' / '+u.parts[a.partKey].name+'破壊で阻止':'');u.telegraph=a;return a}
function planEnemy(u){if(u.style==='BOSS'){const a=makeBossTelegraph(u),ts=targets(u,a),t=ts.find(x=>a.targetRow?x.row===a.targetRow:true)||ts[0];return {type:'skill',action:a,targetId:t?.id}}if(u.casting)return {type:'cast',action:u.casting.action,targetId:u.casting.targetId};const magic=/魔術師|神官|呪術師|精霊|死霊/.test(u.style),ranged=/弓|飛行/.test(u.style);if(ranged&&u.row==='front'&&freeColumn('back',enemies)&&u.status.legBind<=0)return {type:'row'};if(/重装/.test(u.style)&&round%3===1)return {type:'defend'};let a=magic?importSkill(/呪術師/.test(u.style)?'猛毒呪':/神官/.test(u.style)?'聖光':'火球',u):normal(u);if(magic&&round%3===0){a={...a,cast:1,mult:1.6,scope:'row',cost:16}}if(!enough(u,a)||blocked(u,a))a=normal(u);if(u.elite&&round%2===0)a={...normal(u),kind:'skill',name:'強敵の制圧',scope:'row',mult:.95,stun:40,cost:0};let ts=targets(u,a);const taunt=ts.find(t=>Object.values(t.timed||{}).some(b=>b.key==='taunt'));const t=taunt||(/獣/.test(u.style)?ts.slice().sort((a,b)=>a.hp-b.hp)[0]:ranged?ts.find(t=>t.row==='back')||ts[0]:ts[(round+u.slot)%Math.max(1,ts.length)]);return {type:a.kind==='attack'?'attack':'skill',action:a,targetId:t?.id}}
function preparePlans(){for(const u of live(enemies)){u.plan=planEnemy(u);u.defending=u.plan.type==='defend'}for(const u of party){u.queued=!u.alive?null:u.casting?{type:'cast',action:u.casting.action,targetId:u.casting.targetId,partId:u.casting.partId}:null;if(u.alive&&(u.status.sleep>0||u.status.stun>0))u.queued={type:'skip'}}}
async function endRound(token){for(const u of [...party,...enemies]){if(!u.alive)continue;if(u.status.poison>0){const n=Math.max(1,Math.floor(u.maxHp*.04*(u.style==='BOSS'?.5:1)+(u.statusPower.poison||0)*.04));u.hp=Math.max(0,u.hp-n);await say(u.name+'に猛毒 '+n,token,'sys');await defeated(u,token)}if(!u.alive)continue;const r=buff(u,'regen');if(r>0)u.hp=Math.min(u.maxHp,u.hp+Math.ceil(u.maxHp*r));for(const k of Object.keys(u.status)){if(u.status[k]>0){if(u.statusHold[k])u.statusHold[k]=false;else u.status[k]--}}for(const k of Object.keys(u.statusBuildup))u.statusBuildup[k]=Math.max(0,u.statusBuildup[k]-10);tickTimed(u);if(u.mpOnceAvailable&&u.mp<u.maxMp){u.mp=Math.min(u.maxMp,u.mp+passive(u,'mpOnce'));u.mpOnceAvailable=false}}
 if(await checkEnd(token))return;
 for(const sm of summons){const owner=[...party,...enemies].find(u=>u.id===sm.owner);if(!owner?.alive){sm.turns=0;continue}const side=sm.enemy?enemies:party,opp=sm.enemy?party:enemies,t=live(opp)[0];if(sm.type==='guard'){for(const u of live(side))setTimed(u,'guard',.1,1,sm.name)}else if(t){const n=Math.max(1,Math.floor(sm.power*.25));t.hp=Math.max(0,t.hp-n);if(sm.type==='undead')owner.hp=Math.min(owner.maxHp,owner.hp+Math.floor(n*.3));await say(sm.name+'の追撃 '+n,token,'sys');await defeated(t,token)}sm.turns--;if(await checkEnd(token))break}summons=summons.filter(s=>s.turns>0)
}
async function resolve(){if(!editable()||!live(party).length||!live(party).every(u=>u.queued))return;const token=session;busy=true;phase='resolve';closeSheet();setBattle(true);try{const inputs=party.map(u=>({u,q:u.queued})).concat(enemies.map(u=>({u,q:u.plan||planEnemy(u)})));for(const {u,q} of inputs){if(!u.alive||!q||u.status.sleep>0||u.status.stun>0||u.status.legBind>0)continue;if(['row','swap'].includes(q.type)&&/泥濘|岩場|瓦礫|罠床/.test(terrain.name)&&!passive(u,'moveSpeed')){if(u.sp<2){await say(u.name+'は悪路移動のSP不足。',token,'sys');continue}u.sp-=2}if(q.type==='row'){await moveTo(u,u.row==='front'?'back':'front',token,false);u.actedRound=round}if(q.type==='swap'){const t=party.find(x=>x.id===q.swapId&&x.alive);if(t&&t.row!==u.row&&t.status.legBind<=0){await animateSwap(u,t,u.name+'と'+t.name+'が交代。',token)}u.actedRound=round}}
 const order=inputs.filter(({u,q})=>u.alive&&q&&!['defend','row','swap'].includes(q.type)).map(e=>({...e,s:speed(e.u,e.q)})).sort((a,b)=>b.s-a.s);for(const {u,q} of order){await execute(u,q,token);if(await checkEnd(token))break}if(!over){await endRound(token);if(!over){round++;for(const u of [...party,...enemies]){u.defending=false;u.interrupts=0}preparePlans();idx=party.findIndex(u=>u.alive&&!u.queued);if(idx<0)idx=Math.max(0,party.findIndex(u=>u.alive));phase=live(party).every(u=>u.queued)?'ready':'command';log('Round '+round,'sys')}}}catch(e){if(e!==CANCEL){console.error(e);notify('戦闘処理にエラー：'+e.message);over=true;phase='done'}}finally{if(session===token){busy=false;paused=false;setBattle(false);render()}}}
function autoRound(){if(!editable())return;for(const u of live(party)){if(u.queued)continue;const a=[normal(u),...u.skills].find(a=>a.target==='enemy'&&!unavailable(u,a));u.queued=a?{type:a.kind==='attack'?'attack':'skill',action:copy(a),targetId:targets(u,a)[0]?.id}:{type:'defend'};u.defending=!a}phase='ready';render();return resolve()}
async function finish(type,token){if(over)return;over=true;phase='done';for(const u of party)u.defending=false;render();const ctx=EXPCTX;if(ctx){ctx.result=type;ctx.discoveredWeakness=[...discoveredWeakness];ctx.vitals=party.map(u=>({hp:u.hp,sp:u.sp,mp:u.mp,status:Object.fromEntries(['poison','blind','sleep','agitate'].map(k=>[k,u.status[k]||0])),statusPower:{poison:u.statusPower.poison||0}}));ctx.enemyKnowledge=ctx.enemyKnowledge||{};for(const e of enemies){const name=enemyBaseName(e.name),old=ctx.enemyKnowledge[name]||{};ctx.enemyKnowledge[name]={...old,seen:(old.seen||0)+1,attributes:{...old.attributes,...e.observed?.attributes},statuses:{...old.statuses,...e.observed?.statuses},parts:e.parts?Object.values(e.parts).map(p=>({name:p.name,broken:p.hp===0,effect:p.effect})):old.parts}}localStorage.setItem('rpg.exploreBattle',JSON.stringify(ctx));$('returnExplore').hidden=false}await say({win:'勝利',lose:'敗北：街へ撤退',escape:'逃走成功'}[type],token,type==='win'?'ok':'sys');$('history').dataset.result=type}
function enemyIntent(){return live(enemies).filter(e=>e.telegraph||e.casting||e.elite).map(e=>e.name+'：'+(e.telegraph?.telegraphText||e.casting?.action.name+' 詠唱中'||'強敵')).join(' ｜ ')}
function openEnemyInfo(){if(!editable())return;$('sheetKicker').textContent='敵情報 / 部位選択';$('sheetTitle').textContent='敵 '+live(enemies).length+'体';const list=$('sheetList');list.replaceChildren();for(const e of enemies){const known=EXPCTX?.enemyKnowledge?.[enemyBaseName(e.name)]||{},attrs={...known.attributes,...e.observed?.attributes},statuses={...known.statuses,...e.observed?.statuses},div=document.createElement('div');div.className='skill-option';div.innerHTML='<b>'+esc(e.name)+'</b><span class="skill-meta">'+esc(e.style)+' / '+(e.row==='front'?'前列':'後列')+'</span><span class="skill-effect">属性 '+esc(Object.entries(attrs).map(([k,v])=>k+' '+({0:'無効',.5:'耐性',1:'通常',2:'弱点'}[v]||v)).join(' / ')||'未判明')+'<br>状態 '+esc(Object.entries(statuses).map(([k,v])=>k+' '+v).join(' / ')||'未判明')+'</span>';list.append(div);const btn=document.createElement('button');btn.className='skill-option';btn.textContent='本体を狙う';btn.onclick=()=>{getDraft(current()).targetId=e.id;getDraft(current()).partId=null;closeSheet();render()};list.append(btn);for(const p of Object.values(e.parts||{})){const b=document.createElement('button');b.className='skill-option';b.disabled=p.hp<=0;b.innerHTML='<b>'+esc(p.name)+'　'+p.hp+'/'+p.maxHp+'</b><span class="skill-effect">'+esc(p.effect)+(p.hp<=0?' / 破壊済み':'')+'</span>';b.onclick=()=>{const d=getDraft(current());d.targetId=e.id;d.partId=p.id;closeSheet();render()};list.append(b)}}sheet.showModal()}
function openSheet(mode='skills'){if(!editable())return;const u=current(),list=$('sheetList');$('sheetKicker').textContent=u.name;$('sheetTitle').textContent=mode==='members'?'メンバー':'行動';list.replaceChildren();if(mode==='members'){for(const m of party){const b=document.createElement('button');b.className='member-option';b.textContent=m.name+' / '+(m.alive?m.queued?.type==='defend'?'防御を予約':m.queued?'入力済み':'未入力':'戦闘不能');b.disabled=!m.alive;b.onclick=()=>{closeSheet();selectActor(m.id)};list.append(b)}}else{if(u.casting){const b=document.createElement('button');b.className='skill-option';b.textContent='詠唱中止（MPは返還しない）';b.onclick=()=>{cancelCasting(u);closeSheet();render()};list.append(b)}for(const [key,a] of [['attack',normal(u)],...(throwAction(u)?[['throw',throwAction(u)]]:[]),...u.skills.map((a,i)=>[String(i),a])]){const r=unavailable(u,a),b=document.createElement('button');b.className='skill-option';b.setAttribute('aria-disabled',!!r);b.innerHTML='<b>'+esc(a.name)+'</b><span class="cost">'+(a.costType?a.costType+' '+actionCost(u,a):'消費なし')+'</span><span class="skill-meta">'+scopeName(a)+' / '+rangeName(a.range)+' / '+esc(String(a.attr))+'</span><span class="skill-effect">'+esc(r||effectText(a))+'</span>';b.onclick=()=>{if(r)return notify(r);getDraft(u).key=key;ensureTarget(u,a);closeSheet();render()};list.append(b)}}sheet.showModal()}
function render(){renderCards();$('round').innerHTML='R<span>'+round+'</span>';$('actorName').textContent=over?'戦闘終了':current()?.name||'';$('actorJob').textContent=current()?.casting?'詠唱中':current()?.queued?.type==='defend'?'防御・1行動':'';for(const id of ['actor','auto','queue','swap','rowChange','defend','escape','switch','actionButton','carry','enemyInfo'])if($(id))$(id).disabled=!editable()||!current()?.alive;$('resolve').disabled=!editable()||!live(party).length||!live(party).every(u=>u.queued);$('defend').title='1行動を使い防御。攻撃・道具との併用不可';$('terrainEffect').textContent=terrain.name+' / '+terrain.desc;$('enemyIntent').textContent=enemyIntent();$('pace').textContent=paceOptions[paceIndex].name;if(!editable()||!current()?.alive)return;const u=current(),a=actionFor(u),r=unavailable(u,a);ensureTarget(u,a);$('actionName').textContent=a.name;$('actionMeta').textContent=scopeName(a)+' / '+rangeName(a.range)+(a.costType?' / '+a.costType+' '+actionCost(u,a):'');$('queue').disabled=!!r;$('switch').disabled=u.status.armBind>0;$('escape').disabled=u.status.legBind>0||!!EXPCTX?.boss||!!EXPCTX?.noEscape;const d=getDraft(u),t=[...party,...enemies].find(t=>t.id===d.targetId),p=t?.parts?.[d.partId];$('targetHint').textContent=r||'→ '+(t?.name||'対象なし')+(p?' / '+p.name+' '+p.hp+'/'+p.maxHp:'');highlightTargets()}
function fresh(){session++;const token=session;for(const a of activeAnimations)a.cancel();activeAnimations.clear();closeSheet();clearEffects();nodes.clear();drafts.clear();for(const id of ['eb','ef','pf','pb'])$(id).replaceChildren();summons=[];discoveredWeakness=new Set();switchCounts={};uMorale='なし';moraleRecoveryRounds=0;round=1;idx=0;busy=false;over=false;phase='command';paused=false;skip=false;logCount=0;party=HT.map(u=>initUnit(u));enemies=ET.map(u=>initUnit(u,true));for(const u of [...party,...enemies]){u.span=u.span||1;u.usedSkills={};u.statusHold={};u.statusBuildup={};u.statusPower={};u.timed={}}terrain={...TERRAINS.find(t=>t.name==='開所')};$('log').replaceChildren();$('history').open=false;$('notice').hidden=true;$('returnExplore').hidden=true;applyExploreContext();for(const u of [...party,...enemies]){u.span=u.span||1;u.usedSkills=u.usedSkills||{};u.statusHold=u.statusHold||{};u.statusBuildup=u.statusBuildup||{};u.statusPower=u.statusPower||{};u.timed=u.timed||{}}preparePlans();idx=Math.max(0,party.findIndex(u=>u.alive));setBattle(false);log('戦闘開始 / 防御は1行動','sys');$('new').hidden=!!EXPCTX;render();if(!live(party).length)finish('lose',token)}
