function rules(){return window.RPG_RULES}
function ranksFor(i){if(!window.masteryRanks)window.masteryRanks=names.map(()=>({}));return window.masteryRanks[i]||(window.masteryRanks[i]={})}
function hesc(x){return String(x).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function initializeProgression(d){for(const [g,data] of Object.entries(rules().masteries)){if(['武器','防具'].includes(data.category))GEAR[g]=data.branches;else TREE[g]=data.branches}window.masteryRanks=Array.isArray(d?.masteryRanks)&&d.masteryRanks.length===6?d.masteryRanks:names.map(()=>({}));window.legacySkills=Array.isArray(d?.legacySkills)?d.legacySkills:names.map(()=>[]);if(d?.gearDefinitions)Object.assign(WM,d.gearDefinitions);for(const n of ['投げナイフ','鉄針','投石'])inventory.tools[n]=inventory.tools[n]||0;
 for(let i=0;i<6;i++){learned[i]=[...new Set(learned[i]||['通常攻撃','防御'])];skillSet[i]=[...new Set(skillSet[i]||[])].filter(n=>rules().meta(n));if(!d?.progressionVersion){const old=learned[i].filter(n=>rules().meta(n));window.legacySkills[i]=old.slice();for(const n of old){const paths=rules().meta(n).unlocks||[],owned=Object.values(masteryOwned[i]).flat(),u=paths.find(u=>owned.includes(u.mastery))||paths.find(u=>['武器','防具'].includes(rules().masteries[u.mastery].category));if(u)ranksFor(i)[u.mastery]=Math.max(ranksFor(i)[u.mastery]||0,u.rank)}if(old.length===0){const starter=[['破砕撃','盾打'],['毒刃','急所突き'],['火炎剣','貫穿'],['速射','脚封じ射ち'],['火球','障壁'],['頭封じの符','治癒祈祷']][i];for(const n of starter){learned[i].push(n);learnedTree[i].push(n);skillSet[i].push(n);const paths=rules().meta(n).unlocks||[],preferred=i===5?'符術':i===4?'魔術':null,u=paths.find(u=>u.mastery===preferred)||paths[0];if(u){ranksFor(i)[u.mastery]=Math.max(ranksFor(i)[u.mastery]||0,5);const type=rules().masteries[u.mastery].category;if(['源泉','術法','技能'].includes(type)&&!masteryOwned[i][type].includes(u.mastery)&&masteryOwned[i][type].length<(type==='源泉'?1:2))masteryOwned[i][type].push(u.mastery)}}window.legacySkills[i]=starter.slice()}}
  for(const k of Object.keys(ranksFor(i))){if(!rules().masteries[k])delete ranksFor(i)[k];else ranksFor(i)[k]=Math.min(50,Math.max(0,Math.floor(Number(ranksFor(i)[k])||0)))}
  while(skillSet[i].length&&!rules().fits(stats[i],skillSet[i]))skillSet[i].pop()
 }
 rebuildSkillWeaponMap()
}
function loadGame(){const raw=localStorage.getItem('rpg.exploration.save1');let d=null;try{d=raw?JSON.parse(raw):null}catch(e){console.warn('破損したセーブは上書き前にバックアップします',e);try{localStorage.setItem('rpg.exploration.corrupt',raw)}catch(_){} }legacyLoadGame();initializeProgression(d)}
function saveGame(){legacySaveGame();try{const d=JSON.parse(localStorage.getItem('rpg.exploration.save1')||'{}');d.saveVersion=6;d.progressionVersion=6;d.masteryRanks=window.masteryRanks||names.map(()=>({}));d.legacySkills=window.legacySkills||names.map(()=>[]);d.gearDefinitions=WM;localStorage.setItem('rpg.exploration.save1',JSON.stringify(d));return true}catch(e){console.error(e);return false}}
function persist(){saveGame();document.getElementById('money').textContent=gold.toLocaleString()+' G';renderRoster()}
function renderRoster(){document.querySelectorAll('#party .m').forEach((b,i)=>{const max=rules().derived(stats[i]).hp,hp=b.querySelector('.hp');if(hp){hp.style.width=Math.max(0,vitals[i].hp/max*100)+'%';hp.style.background=vitals[i].hp<=0?'#805b63':'#3bad67'}b.title=names[i]+' / HP '+vitals[i].hp+'/'+max;b.classList.toggle('down',vitals[i].hp<=0)})}
function townStatus(){let hurt=vitals.filter((v,i)=>{const d=rules().derived(stats[i]);return v.hp<d.hp||v.sp<d.sp||v.mp<d.mp||Object.values(v.status||{}).some(x=>x>0)}).length,done=quests.filter(q=>q.state===2).length,active=quests.filter(q=>q.state===1).length;return {hurt,done,active,appraisal:loot.古器+rareGear.length,text:(done?'報告 '+done+'件':'依頼 '+active+'件')+' / '+(hurt?'消耗 '+hurt+'人':'全員万全')}}
function mastery(i){show('<h2>'+names[i]+' / Mastery</h2><p class="small">'+mp[i]+' Pt / 成長 +5 に1 Pt / 上限50</p>'+['武器','防具','源泉','術法','技能'].map(t=>'<button class="row" onclick="masteryType('+i+',\''+t+'\')"><b>'+t+'</b></button>').join('')+'<div class="actions"><button onclick="character('+i+')">戻る</button></div>')}
function masteryType(i,t){show('<h2>'+t+' Mastery</h2><p class="small">'+mp[i]+' Pt'+(t==='源泉'?' / 1系統まで':['術法','技能'].includes(t)?' / 2系統まで':'')+'</p>'+Object.entries(rules().masteries).filter(([g,d])=>d.category===t).map(([g,d])=>'<button class="row" onclick="growMastery('+i+',\''+g+'\')"><b>'+g+'　'+(ranksFor(i)[g]||0)+'/50</b><span class="small">'+Object.keys(d.branches).join(' / ')+'</span></button>').join('')+'<div class="actions"><button onclick="mastery('+i+')">戻る</button></div>')}
function growMastery(i,g){const data=rules().masteries[g];if(!data)return;const rank=ranksFor(i)[g]||0;show('<h2>'+g+'　'+rank+'/50</h2><p class="small">Mastery Pt '+mp[i]+' / +5ごとに1 Pt<br>5 基礎 / 15 初級 / 25 中級 / 35 上級 / 45 最高位 / 50 完成</p><button class="row" '+(rank>=50?'disabled':'onclick="trainMastery('+i+',\''+g+'\')"')+'><b>成長 +5</b><span class="small">1 Pt / スキル習得は別途1 Pt</span></button>'+Object.entries(data.branches).map(([b,ns])=>'<button class="row" onclick="masterySkills('+i+',\''+g+'\',\''+b+'\')"><b>'+b+'</b><span class="small">'+ns.join(' / ')+'</span></button>').join('')+'<div class="actions"><button onclick="masteryType('+i+',\''+data.category+'\')">戻る</button></div>')}
function trainMastery(i,g){const def=rules().masteries[g];if(!def)return;if(mp[i]<1)return note('Mastery Pt不足');const r=ranksFor(i)[g]||0;if(r>=50)return note('Masteryは50が上限');if(['源泉','術法','技能'].includes(def.category)){const own=masteryOwned[i][def.category],limit=def.category==='源泉'?1:2;if(!own.includes(g)){if(own.length>=limit)return note(def.category+'は'+limit+'系統まで');own.push(g)}}ranksFor(i)[g]=Math.min(50,r+5);mp[i]--;persist();growMastery(i,g)}
function gearBranches(i,g){growMastery(i,g)}
function masteryBranches(i,g){growMastery(i,g)}
function gearSkills(i,g,b){masterySkills(i,g,b)}
function masterySkills(i,g,b){const ns=rules().masteries[g]?.branches[b];if(!ns)return;show('<h2>'+g+' / '+b+'</h2><p class="small">Rank '+(ranksFor(i)[g]||0)+' / 50　'+mp[i]+' Pt</p>'+ns.map(n=>{const d=rules().meta(n),u=d.unlocks.find(u=>u.mastery===g&&u.branch===b),owned=learned[i].includes(n),ok=rules().canLearn(n,g,ranksFor(i),stats[i]);return '<button class="row" '+(owned?'onclick="skills('+i+')"':ok?'onclick="learnSkill('+i+',\''+g+'\',\''+b+'\',\''+n+'\')"':'disabled')+'><b>'+(owned?'✓ ':'')+n+'</b><span class="small">'+d.mode+' / Cost '+d.setCost+' / '+(d.costType?d.costType+' '+d.cost:'常時効果')+'<br>要求：Rank '+u.rank+' / '+u.stat+' '+u.value+' / 習得1 Pt<br>'+hesc(skillDescription(d))+'</span></button>'}).join('')+'<div class="actions"><button onclick="growMastery('+i+',\''+g+'\')">戻る</button></div>')}
function learnSkill(i,g,b,n){const d=rules().meta(n);if(!d||!rules().masteries[g]?.branches[b]?.includes(n))return note('不正なスキル');if(learned[i].includes(n))return note('習得済み');if(mp[i]<1)return note('Mastery Pt不足');if(!rules().canLearn(n,g,ranksFor(i),stats[i]))return note('Masteryランクまたは能力値が不足');const category=rules().masteries[g].category;if(['源泉','術法','技能'].includes(category)&&!masteryOwned[i][category].includes(g))return note('系統を先に取得してください');mp[i]--;learned[i].push(n);learnedTree[i].push(n);persist();masterySkills(i,g,b)}
function learnGear(i,g,b,n){learnSkill(i,g,b,n)}
function charMastery(i){show('<h2>'+names[i]+' / Mastery</h2><p class="small">残り '+mp[i]+' Pt</p>'+Object.entries(ranksFor(i)).filter(([g,v])=>v>0).map(([g,v])=>'<button class="row" onclick="growMastery('+i+',\''+g+'\')"><b>'+g+'　'+v+'/50</b></button>').join('')+'<div class="actions"><button onclick="mastery('+i+')">育成する</button><button onclick="character('+i+')">戻る</button></div>')}
function skillDescription(d){if(d.mode==='Passive')return d.description;const s=[d.mult>0?'威力'+d.mult+(d.hits?'（'+d.hits+'段合計）':''):'',d.scope==='all'?'全体':d.scope==='row'?'1列':d.scope==='pierce'?'前後貫通':d.scope==='adjacent'?'隣接':'単体',d.stat,d.cast?'詠唱1ラウンド':'',d.once?'1戦1回':'',d.push?'吹飛ばし':d.pull?'引寄せ':'',d.heal?'HP回復':'',d.summon?'召喚3ラウンド':''];return s.filter(Boolean).join(' / ')}
function skillMeta(n){const d=rules().meta(n);return d?[d.setCost,d.mode]:[0,'Active']}
function skillCap(i){return rules().capacity(stats[i],skillSet[i])}
function effectiveCost(i,n){return rules().cost(n,skillSet[i])}
function skillCost(i){return rules().setCost(skillSet[i])}
function skillUsable(i,n){const d=rules().meta(n);if(!d)return false;const req=d.weapons;if(!req?.length)return true;const held=eq[i].slice(0,4).map(x=>weaponKind(x.split('：')[1]));if(req.includes('格闘')&&((held[0]==='なし'&&held[1]==='なし')||held.includes('格闘')))return true;if(req.includes('投擲')&&['投げナイフ','鉄針','投石'].includes(eq[i][9].split('：')[1]))return true;return req.some(x=>held.includes(x))}
function skills(i,filter='All'){const ns=learned[i].filter(n=>rules().meta(n)&&(filter==='All'||rules().meta(n).mode===filter));show('<h2>'+names[i]+' / スキルセット</h2><p class="small">Cost '+skillCost(i)+'/'+skillCap(i)+' / パッシブもセット中だけ有効</p><div class="actions"><button onclick="skills('+i+')">すべて</button><button onclick="skills('+i+',\'Active\')">Active</button><button onclick="skills('+i+',\'Passive\')">Passive</button></div>'+ns.map(n=>{const d=rules().meta(n),on=skillSet[i].includes(n);return '<button class="row" onclick="toggleLearnedSkill('+i+',\''+n+'\')"><b>'+(on?'✓ ':'○ ')+n+'</b><span class="small">'+d.mode+' / Cost '+effectiveCost(i,n)+(d.costType?' / '+d.costType+' '+d.cost:'')+'<br>'+hesc(skillDescription(d))+(!skillUsable(i,n)?'<br>対応装備が必要':'')+'</span></button>'}).join('')+'<div class="actions"><button onclick="mastery('+i+')">習得・育成</button><button onclick="character('+i+')">戻る</button></div>')}
function toggleLearnedSkill(i,n){if(!learned[i].includes(n)||!rules().meta(n))return;const next=skillSet[i].includes(n)?skillSet[i].filter(x=>x!==n):skillSet[i].concat(n);if(!rules().fits(stats[i],next))return note('Cost上限を超えます。他のスキルを先に外してください');skillSet[i]=next;persist();skills(i)}
function hasSkill(s){const groups={敵察知:'scout',索敵:'scout',鑑識:'appraise',鑑定:'appraise',遺物調査:'appraise',罠解除:'unlock',解錠:'unlock',隠密:'stealth',潜伏:'stealth'};return skillSet.some(a=>a.includes(s)||(groups[s]&&rules().effect(a,groups[s])>0))}
function rebuildSkillWeaponMap(){skillWeapon={};for(const [n,d] of Object.entries(rules().skills))if(d.weapons?.length===1)skillWeapon[n]=d.weapons[0]}
function calcResist(i){const r={...resist[i]},armor=eq[i][4].split('：')[1];if(armor==='魔装')for(const k of ['火','水','風','土','光','闇'])r[k]=(r[k]||0)+10;if(armor==='重装')for(const k of ['斬','突','壊'])r[k]=(r[k]||0)+12;return r}
function weightInfo(i){const slots=[0,1,4,5,6,7,8],raw=slots.reduce((s,k)=>{const n=eq[i][k].split('：')[1];return s+(WM[n]?.[2]??ARM[n]?.[0]??(n==='なし'?0:1))},0),weight=Math.round(raw*(1-Math.min(.4,rules().effect(skillSet[i],'loadReduction')))*100)/100,limit=stats[i][0],ratio=weight/limit,level=ratio<=1?0:ratio<=1.2?1:ratio<=1.5?2:3;return {weight,limit,ratio,level,text:['重量正常','速度・回避-5 / 武器95%','速度・回避-15 / 武器90%','速度・回避-30 / 武器80%'][level]}}
function addStat(i,k){if(statPt[i]<1||![0,1,2,3].includes(k))return note('Stat Pt不足');const old=rules().derived(stats[i]);stats[i][k]++;statPt[i]--;const now=rules().derived(stats[i]);for(const key of ['hp','sp','mp'])if(key!=='hp'||vitals[i].hp>0)vitals[i][key]+=now[key]-old[key];persist();charAbility(i)}
function toolShop(){const goods=[['回復薬',120],['解毒薬',100],['爆弾',280],['煙玉',220],['薬瓶',240],['投げナイフ',40],['鉄針',30],['投石',20]];show('<h2>道具</h2>'+goods.map(([n,p])=>'<button class="row" onclick="buyTool(\''+n+'\','+p+')"><b>'+n+'　'+p+'G</b><span class="small">所持 '+(inventory.tools[n]||0)+'</span></button>').join('')+'<div class="actions"><button onclick="market()">戻る</button></div>')}
function equipChoice(i,k){const list=k<4?['なし',...inventory.weapons]:k>=4&&k<=7?inventory.armor:k===9?['なし',...Object.keys(inventory.tools)]:['なし','護符'];show('<h2>装備候補</h2>'+list.map(n=>{const m=WM[n],idx={PHY:0,SKL:1,ARC:2,MND:3}[m?.[3]],valid=k>=4||(!m||m[3]==='―'||stats[i][idx]>=m[4])&&handEquipAllowed(i,k,n);return '<button class="row" '+(valid?'onclick="setEquip('+i+','+k+',\''+n+'\')"':'disabled')+'><b>'+hesc(n)+'</b><span class="small">'+(m?m[0]+' / '+m[1]+' / 重量'+m[2]+' / '+m[3]+' '+m[4]:'')+(k===9?' / 所持'+(inventory.tools[n]||0):'')+'</span></button>'}).join('')+'<div class="actions"><button onclick="equip('+i+')">戻る</button></div>')}
function swapMain(i){const labels=['主武器','副手','予備主','予備副'],v=eq[i].slice(0,4).map(x=>x.split('：')[1]);eq[i][0]=labels[0]+'：'+v[2];eq[i][1]=labels[1]+'：'+v[3];eq[i][2]=labels[2]+'：'+v[0];eq[i][3]=labels[3]+'：'+v[1];persist();prepMember(i)}
function prepMember(i){show('<h2>'+names[i]+' / 戦闘準備</h2><p class="small">'+rows[i]+' / '+eq[i][0]+'＋'+eq[i][1]+'</p><button class="row" onclick="swapMain('+i+')"><b>主副セット ⇄ 予備セット</b></button><button class="row" onclick="toggleRow('+i+')"><b>隊列を変更</b></button><button class="row" onclick="skills('+i+')"><b>スキル</b></button><div class="actions"><button onclick="battlePrep()">戻る</button></div>')}
function useTool(n,i){if(!inventory.tools[n])return note('道具がありません');if(!['回復薬','薬瓶','解毒薬'].includes(n))return note('この携行具は戦闘で使用します');const valid=j=>vitals[j].hp>0&&(n==='解毒薬'?(vitals[j].status?.poison||0)>0:n==='薬瓶'?vitals[j].hp<rules().derived(stats[j]).hp||vitals[j].sp<rules().derived(stats[j]).sp:vitals[j].hp<rules().derived(stats[j]).hp);if(i==null){show('<h2>'+n+' / 対象</h2>'+names.map((x,j)=>valid(j)?'<button class="row" onclick="useTool(\''+n+'\','+j+')"><b>'+x+'</b><span class="small">HP '+vitals[j].hp+'/'+rules().derived(stats[j]).hp+'</span></button>':'').join('')+'<div class="actions"><button onclick="items()">戻る</button></div>');return}if(!valid(i))return note('使用が必要な対象ではありません');inventory.tools[n]--;const v=vitals[i],d=rules().derived(stats[i]);if(n==='解毒薬'){v.status.poison=0;v.statusPower={}}else{v.hp=Math.min(d.hp,v.hp+(n==='回復薬'?Math.ceil(d.hp*.35):25));if(n==='薬瓶')v.sp=Math.min(d.sp,v.sp+12)}persist();items()}
function itemCategory(t){if(t==='道具')return show('<h2>道具</h2>'+Object.entries(inventory.tools).map(([n,v])=>'<button class="row" onclick="useTool(\''+n+'\')"><b>'+n+' ×'+v+'</b></button>').join('')+'<div class="actions"><button onclick="items()">戻る</button></div>');if(t==='素材')return show('<h2>素材</h2>'+Object.entries(loot).map(([n,v])=>'<div class="row"><b>'+n+' ×'+v+'</b></div>').join('')+'<div class="actions"><button onclick="items()">戻る</button></div>');show('<h2>装備</h2><p class="small">'+inventory.weapons.join(' / ')+'</p><div class="actions"><button onclick="partyMenu()">装備変更</button><button onclick="items()">戻る</button></div>')}
function battleDemo(){if(!expeditionActive)return note('探索を開始してください');if(!vitals.some(v=>v.hp>0))return returnTown('敗北');for(let i=0;i<6;i++)if(!rules().fits(stats[i],skillSet[i]))return note(names[i]+'のスキルCostを確認してください');const td=themeData(),idx=routeDone[routeDone.length-1],enc=encounterData(td),ctx={schema:6,battleId:Date.now()+'-'+Math.random().toString(36).slice(2),battleType:pendingBattleType,runBuff,morale,floor,themes:floorThemes,routeOpen,routeDone,routePattern,nodeTerrain,nodeThreat,nodeEncounter,campUsed,stealthSkip,expeditionEvents,expeditionStartLoot,expeditionActive:true,activeMembers:[0,1,2,3,4,5],terrain:nodeTerrain[idx]||terrainPool(td.t)[0],enemy:td.enemy,enemyFront:enc.front,enemyBack:enc.back,threat:nodeThreat[idx]||1,rows,stats,vitals,resist:names.map((_,i)=>calcResist(i)),enemyKnowledge:journal.enemyData,masteryOwned,masteryRanks:window.masteryRanks,learnedTree,upgrades,traits,gearMeta:WM,dungeonId,armor:eq.map(x=>x[4].split('：')[1]),equipment:eq,carryInventory:inventory.tools,carrySet:eq.map(x=>x[9].split('：')[1]),skillSet,boss:pendingBattleType==='boss',result:null};runBuff='なし';morale='なし';persist();try{localStorage.setItem('rpg.exploreBattle',JSON.stringify(ctx));location.href='../index.html'}catch(e){note('戦闘の保存に失敗しました。空き容量を確認してください')}}
function resumeBattle(){let ctx;try{ctx=JSON.parse(localStorage.getItem('rpg.exploreBattle')||'null')}catch(_){return false}if(!ctx?.result)return false;if(ctx.enemyKnowledge){for(const [n,d] of Object.entries(ctx.enemyKnowledge)){journal.enemyData[n]={...journal.enemyData[n],...d};addUnique(journal.enemies,n)}}return legacyResumeBattle()}
function enemyBook(){show('<h2>敵図鑑</h2>'+journal.enemies.map(n=>{const d=journal.enemyData[n]||{},attrs=d.attributes||{},status=d.statuses||{};return '<div class="row"><b>'+hesc(n)+'</b><span class="small">'+hesc(Object.entries(attrs).map(([a,v])=>a+' '+({0:'無効',.5:'耐性',1:'通常',2:'弱点'}[v]||v)).join(' / ')||'属性未判明')+'<br>'+hesc(Object.entries(status).map(([a,v])=>a+' '+v).join(' / ')||'状態未判明')+(d.parts?'<br>'+hesc(d.parts.map(p=>p.name+(p.broken?'破壊済み':'')).join(' / ')):'')+'</span></div>'}).join('')+'<div class="actions"><button onclick="records()">戻る</button></div>')}
function merchantNode(){const goods=[['回復薬',180],['解毒薬',120],['煙玉',240],['魔力結晶',500]],discount=hasSkill('窃盗')?.8:1;show('<h2>旅商人</h2>'+goods.map(([n,p])=>'<button class="row" onclick="merchantBuy(\''+n+'\','+Math.floor(p*discount)+')"><b>'+n+' '+Math.floor(p*discount)+'G</b></button>').join('')+'<div class="actions"><button onclick="closeM();drawDungeon()">探索へ</button></div>')}
function merchantBuy(n,p){if(gold<p)return note('所持金不足');gold-=p;if(n==='魔力結晶')loot.結晶++;else inventory.tools[n]=(inventory.tools[n]||0)+1;persist();merchantNode()}
function setMorale(n){const available={歌唱:['鼓舞歌','回復歌','戦歌'],舞踏:['回避舞','速度舞','連携舞'],奏楽:['旋律','律動','SP支援'],号令:['攻勢号令','防勢号令','追撃号令']}[n];if(!available?.some(hasSkill))return note('対応スキルをセットしてください');morale=n;persist();camp()}
