/* Exercise common and secondary windows with real layout at each viewport. */
(async()=>{
const results=[],saved=collectSave();
const routes=['inn()','roomMenu()','conversation()','npcMenu()','memberTalk(0)','npcTalk("受付")','guild()','guildMembers()','appraiseMenu()','guildSellMenu()','guildSellMenu("materials")','guildSellMenu("tools")','guildSellMenu("weapons")','questMenu("open")','market()','toolShop()','toolQuantity("回復薬")','weaponShop()','armorShop()','craftMenu()','storageMenu()','items()','records()','settings()','partyMenu()','character(0)','equip(0)','equipChoice(0,0)','skills(4)','charAbility(4)','mastery(4)','resistView(4)','dungeon()'];
for(const route of routes){
 try{
  closeM();(0,eval)(route);
  const p=document.querySelector('#panel'),footer=p.querySelector('.panel-footer'),body=p.querySelector('.panel-body');
  const r=p.getBoundingClientRect(),f=footer.getBoundingClientRect();
  const buttons=[...footer.querySelectorAll('button')].filter(b=>!b.hidden),sizes=buttons.map(b=>b.getBoundingClientRect());
  const ok=Math.abs(r.height-innerHeight)<=1&&r.top>=-1&&r.bottom<=innerHeight+1&&f.bottom<=innerHeight+1&&f.top>=innerHeight-(p.querySelector('.fitting-controls')?200:150)&&sizes.every(x=>x.height>=44&&x.width>=44)&&!p.querySelector('.panel-head button:not(.icon-button)')&&body.scrollWidth<=body.clientWidth+1;
  results.push({name:'Touch navigation '+route+' '+innerWidth+'x'+innerHeight,ok,measurements:{panel:r.height,footerTop:f.top,overflow:body.scrollWidth-body.clientWidth,buttons:sizes.map(x=>[x.width,x.height])}});
 }catch(e){results.push({name:'Touch navigation '+route,ok:false,error:String(e)})}
}
try{
 closeM();market();toolShop();const before=gold;
 confirmAction('購入の確認','テスト用。実行しません。','buyTool',['回復薬',1]);
 const cancel=document.querySelector('.panel-footer .panel-back');
 if(!cancel)throw Error('Back navigation is missing');
 cancel.click();
 results.push({name:'Bottom cancel restores previous screen without purchase',ok:gold===before&&document.querySelector('#modal').classList.contains('on')&&HUB_UI.state.route.name==='toolShop'});
}catch(e){results.push({name:'Bottom cancel',ok:false,error:String(e)})}
try{closeM();equipChoice(0,0,'長槍');const panel=document.querySelector('#panel'),body=panel.querySelector('.panel-body'),hero=panel.querySelector('.fitting-summary'),controls=panel.querySelector('.fitting-controls'),footer=panel.querySelector('.panel-footer');const top=hero.getBoundingClientRect().top;body.scrollTop=body.scrollHeight;const after=hero.getBoundingClientRect();results.push({name:'Pinned equipment comparison and right confirmation '+innerWidth,error:JSON.stringify({hero:hero.getBoundingClientRect().toJSON(),controls:controls.getBoundingClientRect().toJSON(),body:body.getBoundingClientRect().toJSON(),footer:footer.getBoundingClientRect().toJSON()}),ok:controls.scrollHeight<=controls.clientHeight+1&&after.top===top&&controls.getBoundingClientRect().bottom<=hero.getBoundingClientRect().top+1&&hero.getBoundingClientRect().right<=body.getBoundingClientRect().left+1&&hero.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1&&body.clientHeight>=65&&!footer.querySelector('.actions')&&panel.querySelector('.equipment-right .fitting-confirm [data-hub="fittingApply"]')&&body.scrollWidth<=body.clientWidth+1});}catch(e){results.push({name:'Pinned fitting',ok:false,error:String(e)})}
try{equip(0);const p=document.querySelector('#panel'),swap=p.querySelector('.reserve-slots [data-hub="fittingSwap"]'),reserve=p.querySelector('.reserve-slots>div'),confirm=p.querySelector('.fitting-confirm').getBoundingClientRect(),body=p.querySelector('.equipment-right>.panel-body').getBoundingClientRect();results.push({name:'Equipment slots one line and confirm below list '+innerWidth,ok:swap.getBoundingClientRect().top>=reserve.getBoundingClientRect().bottom&&confirm.top>=body.bottom-1&&[...p.querySelectorAll('.fitting-controls [data-hub="equipChoice"]')].every(e=>{const a=e.querySelector('small').getBoundingClientRect(),b=e.querySelector('b').getBoundingClientRect();return Math.abs((a.top+a.bottom)/2-(b.top+b.bottom)/2)<3})});}catch(e){results.push({name:'Equipment confirmation layout',ok:false,error:String(e)})}
for(let i=0;i<6;i++){try{closeM();character(i);const p=document.querySelector('#panel'),hero=p.querySelector('.status-cover').getBoundingClientRect(),basic=p.querySelector('.status-basics').getBoundingClientRect(),tabs=p.querySelector('.actor-tabs').getBoundingClientRect(),body=p.querySelector('.panel-body');results.push({name:'Status portrait layout without scrolling '+i+' '+innerWidth,ok:hero.height>=innerHeight*.45&&hero.bottom<=basic.top+1&&basic.bottom<=tabs.top+1&&p.scrollHeight<=p.clientHeight+1&&body.scrollHeight<=body.clientHeight+1});charAbility(i);const b=p.querySelector('.panel-body');results.push({name:'Growth keeps only Mastery guidance fixed '+i+' '+innerWidth,ok:!p.querySelector('.stats-grid')&&!!p.querySelector('.actor-fixed')});}catch(e){results.push({name:'Status layout '+i,ok:false,error:String(e)})}}
for(const action of [()=>skills(0),()=>masteryType(0,'武器'),()=>growMastery(0,'剣')]){try{action();const p=document.querySelector('#panel'),f=p.querySelector('.actor-fixed'),b=p.querySelector('.panel-body'),before=f.getBoundingClientRect().top;b.scrollTop=200;results.push({name:'Character explanation stays fixed '+HUB_UI.state.route.name+' '+innerWidth,ok:f.getBoundingClientRect().top===before&&f.getBoundingClientRect().bottom<=b.getBoundingClientRect().top+1&&b.clientHeight>=65&&p.scrollHeight<=p.clientHeight+1});}catch(e){results.push({name:'Character fixed explanation',ok:false,error:String(e)})}}
try{masteryType(0,'武器');growMastery(0,'剣');const p=document.querySelector('#panel'),left=p.querySelector('.mastery-left').getBoundingClientRect(),right=p.querySelector('.mastery-right').getBoundingClientRect(),branches=p.querySelector('.mastery-training').getBoundingClientRect(),footer=p.querySelector('.panel-footer').getBoundingClientRect();results.push({name:'Mastery split layout '+innerWidth,ok:left.right<=right.left&&branches.bottom<=footer.top+1&&p.querySelectorAll('.mastery-right .branch-toggle').length===4&&[...p.querySelectorAll('.mastery-right .branch-toggle,.mastery-training button')].every(b=>b.getBoundingClientRect().height>=44)&&p.scrollHeight<=p.clientHeight+1});}catch(e){results.push({name:'Mastery split layout',ok:false,error:String(e)})}
for(let i=0;i<6;i++)for(const tab of ['basic','resist']){try{actorAttributes(i,tab);if(tab==='basic')attributeAdjust(i,0,1);const p=document.querySelector('#panel'),b=p.querySelector('.panel-body');results.push({name:'All attributes fit '+i+' '+tab+' '+innerWidth,error:JSON.stringify({body:[b.clientWidth,b.scrollWidth,b.clientHeight,b.scrollHeight],panel:[p.clientHeight,p.scrollHeight],fixed:p.querySelector('.actor-fixed').getBoundingClientRect().height,buttons:[...p.querySelectorAll('.allocation-stat button,.allocation-bar button')].map(x=>x.getBoundingClientRect().height)}),ok:p.querySelectorAll('.attribute-cell').length>0&&[...p.querySelectorAll('.allocation-stat button,.allocation-bar button')].every(x=>x.getBoundingClientRect().height>=44)&&b.scrollHeight<=b.clientHeight+1&&p.scrollHeight<=p.clientHeight+1&&b.scrollWidth<=b.clientWidth+1});}catch(e){results.push({name:'Attributes layout',ok:false,error:String(e)})}}

installSave(saved);closeM();town();
return results;
})();
